### PR TITLE
Prohibit adding a cache group with no servers to a topology

### LINKED ISSUE #5143: Traffic Ops should prohibit adding a cache group with no servers to a topology
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

You can create a topology that contains a cachegroup with no servers in it, even though a delivery service that uses such a topology will not work.

## New behavior:

Users should be prohibited from creating topologies whose cachegroups do not each contain at least one server.

## Minimal reproduction of the problem with instructions:

1. Make topology with servers in it
2. Delete servers, then update the topology. This should return a 400 response but returns a 200 response.

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5143
- This PR adds validation to require that each cachegroup in a topology contains at least 1 server.

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

- Run the Traffic Ops API tests
- Try to create a topology that contains a cachegroup with no servers in it, make sure the POST fails
- Try to update a topology that contains a cachegroup with no servers in it, make sure the PUT fails

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR includes documentation
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by zrhoffman** [comment]
Got CDN in a Box working in 10424bb410. I'm making this PR a draft until the API tests pass.

**Comment by zrhoffman** [comment]
Removed draft status, PR is ready for review.

**Review by mitchell852 — COMMENTED** [review]
did a quick manual test. tried to add a cache group w/ no servers and got:

'empty cachegroups' cachegroups with no servers in them: no-servers

👍

File: traffic_ops/traffic_ops_golang/topology/topologies.go [hunk 1]
```diff
@@ -146,13 +149,61 @@ func (topology *TOTopology) Validate() error {
...
+			log.Errorf(systemError, err.Error())
+			return baseError
+		}
+		if serverCount != 0 {
+			break
+		}
+		cacheGroups = append(cacheGroups, cacheGroup)
+	}
+
+	if cacheGroups != nil {
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/topology/topologies.go:188]: nit: might read better as `len(cacheGroups) > 0`

File: traffic_ops/traffic_ops_golang/topology/topologies.go [hunk 2]
```diff
@@ -563,6 +614,23 @@ JOIN topology_cachegroup tc on t.name = tc.topology
...
+		SELECT c."name", COUNT((
+			SELECT s2.id FROM server s2
+			JOIN "type" t ON s."type" = t.id
+			WHERE s2.id = s.id
+		)) server_count
+		FROM cachegroup c
+		LEFT JOIN "server" s ON c.id = s.cachegroup
+		WHERE c."name" = ANY(CAST(:cachegroup_names AS TEXT[]))
+		GROUP BY c."name"
+		ORDER BY server_count
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/topology/topologies.go:629]: Can this simply be
```
SELECT c."name", COUNT(*) AS server_count
        FROM cachegroup c
        LEFT JOIN "server" s ON c.id = s.cachegroup
        WHERE c."name" = ANY(CAST(:cachegroup_names AS TEXT[]))
        GROUP BY c."name"
        ORDER BY server_count;
```
instead?

**Review by rawlinp — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -21,6 +21,7 @@ The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/).
     - Traffic Ops: Added validation to prohibit assigning caches to topology-based delivery services
     - Traffic Ops: Added validation to prohibit removing a capability from a server if no other server in the same cachegroup can satisfy the required capabilities of the delivery services assigned to it via topologies.
     - Traffic Ops: Added validation to ensure that at least one server per cachegroup in a delivery service's topology has the delivery service's required capabilities.
+    - Traffic Ops: Added validation to ensure that at least one server exists in each cachegroup.
```
[the remark this answers is not in the document]
Comment (zrhoffman) [reply CHANGELOG.md]: Specified in d6417bfa6

File: traffic_ops/traffic_ops_golang/topology/topologies.go (hunk 1 above)
Comment (zrhoffman) [reply traffic_ops/traffic_ops_golang/topology/topologies.go]: Rewrote condition in 9f7b44cf5

File: traffic_ops/traffic_ops_golang/topology/topologies.go (hunk 2 above)
Comment (zrhoffman) [reply traffic_ops/traffic_ops_golang/topology/topologies.go]: Due to the `LEFT JOIN` making `COUNT(*)` include `NULL`s, it would need to be something like `COUNT(*) FILTER (WHERE s.id IS NOT NULL)`.

Simplified in 118863a5e

**Review by rawlinp — APPROVED** [review]
LGTM, checks passed
