### PR TITLE
TO fix anymap ds assignment

### LINKED ISSUE #3315: Assigning servers to ANY_MAP DS causes null pointer exception in TR
There appears to be a regression in the CRConfig generation process where if you add servers to an ANY_MAP DS, those assignments leak into the CRConfig which causes TR to throw a exception.  The suspected source is that DS assignments exist for a DS that shouldn't exist in the CRConfig.

Found in the 3.x RC4 release and head of master at a86195f

Exception thrown in TR (snipped):
```
WARN  2019-02-08T18:01:09.898 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater -
java.lang.NullPointerException
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.populateZoneMap(ZoneManager.java:642)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.generateZones(ZoneManager.java:364)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.initZoneCache(ZoneManager.java:187)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.<init>(ZoneManager.java:113)
	at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter.<init>(TrafficRouter.java:114)
	at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouterManager.setCacheRegister(TrafficRouterManager.java:103)
	at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.processConfig(ConfigHandler.java:227)
	at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher$2.update(TrafficMonitorWatcher.java:116)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.updateDatabase(PeriodicResourceUpdater.java:165)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:285)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater$UpdateHandler.onCompleted(PeriodicResourceUpdater.java:256)
... snipped ...
```

If you remove the server assignments, then TR will be ok.  However this also means that the ANY_MAP DS doesn't do anything.

You can create an ANY_MAP DS as follows to reproduce:
1. Create and link the following parameters to your ATS Server profile:
```
    a. name: location | configFile: anymap_hdr_rw.config | value: "/opt/trafficserver/etc/trafficserver"
    b. name: data | configFile: anymap_hdr_rw.config | value: "cond %{SEND_RESPONSE_HDR_HOOK} __RETURN__ add-header ATS_ANYMAP_GLOBAL 'Anymap_Global_Match' [L]"
```
2. Create an ANY_MAP DS as normal using the following raw remap text field: `map / http://<replace.with.some.valid.origin>/ @plugin=header_rewrite.so @pparam=anymap_hdr_rw.config`
3. Assign some ATS Servers
4. Queue/snap the CDN containing your ANY_MAP DS:
    * This is presently where it will break TR.  You will see that the server assignments are part of the snapshot diff in TP
5. Badass your ATS Servers to pull down the new anymap header rewrite config
6. Run a test curl against the ATS server fqdn for a known asset and observe that you now have a ATS_ANYMAP_GLOBAL header in your response as well as your known asset body.

### PR DESCRIPTION
**Pull request by rawlinp**
#### What does this PR do?

This fixes the TO CRConfig generation to not include ANY_MAP DS-server assignments. The Traffic Router fix to be more defensive against this scenario will be done in a separate PR.

Fixes #3315

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### What is the best way to verify this PR?
Run the TO API integration tests.

#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3202/
Test PASSed.

**Comment by rob05c** [comment]
For the record, I have no objections to merging this instead. I didn't realize it was being worked on when I made my PR, sorry

**Comment by rawlinp** [comment]
@rob05c thanks, I probably should've assigned the issue to myself when I started working on it. I keep forgetting that I have the ability to do that now.

File: traffic_ops/traffic_ops_golang/crconfig/servers.go [hunk 1]
```diff
@@ -190,10 +191,12 @@ select s.host_name, ds.xml_id
 from deliveryservice_server as dss
 inner join server as s on dss.server = s.id
 inner join deliveryservice as ds on ds.id = dss.deliveryservice
+inner join type as dt on dt.id = ds.type
```
Comment (rob05c) [inline traffic_ops/traffic_ops_golang/crconfig/servers.go]: Nitpick: an inline `and ds.type <> (select id from type where name = " + string(tc.DSTypeAnyMap) + ")` is faster than a join, because the query optimizer can't know beforehand that there's only one row.

File: traffic_ops/traffic_ops_golang/crconfig/servers.go [hunk 2]
```diff
@@ -190,10 +191,12 @@ select s.host_name, ds.xml_id
...
 inner join profile as p on p.id = s.profile
 inner join status as st ON st.id = s.status
 where ds.cdn_id = (select id from cdn where name = $1)
-and ds.active = true
+and ds.active = true` +
+		fmt.Sprintf(" and dt.name != '%s' ", tc.DSTypeAnyMap) + `
```
Comment (rob05c) [inline traffic_ops/traffic_ops_golang/crconfig/servers.go]: Nitpick: `+ string(tc.DSTypeAnyMap) +` is both easier to read and faster

Comment (rob05c) [inline traffic_ops/traffic_ops_golang/crconfig/servers.go]: Nitpick: `!=` isn't standard SQL, better to use the standard-compliant `<>`.

File: traffic_ops/traffic_ops_golang/crconfig/servers.go (hunk 1 above)
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/crconfig/servers.go]: Interesting...I'm trying to understand that. Can you elaborate a bit more please? What do you mean that there's only one row? Do you mean one column -- `type.name`?

File: traffic_ops/traffic_ops_golang/crconfig/servers.go (hunk 2 above)
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/crconfig/servers.go]: Agreed. I think I did it this way because it's how the other ANY_MAP query fix was done too.

Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/crconfig/servers.go]: Thanks, I will try to remember that next time.
