### PR TITLE
Rewrote jobs endpoints to go

### LINKED ISSUE #3116: Read-Only users can create invalidation jobs
The endpoint at `api/1.x/user/current/jobs` doesn't check roles if tenancy is enabled - thus any user to whom a Delivery Service is assigned and is also a member of the tenancy which owns said Delivery Service is permitted to create content invalidation jobs. This means that technically, Portal, Steering, Extension, and Monitor users may also create content invalidation jobs, though I think it's more distressing that the ability is given to a user permission group literally named "Read-Only".

### LINKED ISSUE #3416: deliverservice_stats endpoint cannot parse ISO date/times with milliseconds
If you make a request to the `deliveryservice_stats` endpoint with `startDate` and/or `endDate` set to ISO 8601 Extended Format-compliant strings with non-zero milliseconds, it will generate an internal server error and barf up a legacy UI page complaining about `cannot set 'id' of undefined` (paraphrased). For example, the URL
```
https://trafficops.domain.test/api/1.4/deliveryservice_stats?interval=60s&metricType=kbps&serverType=edge&deliveryServiceName=dsXML_ID&startDate=2019-03-18T06:00:00.000Z&endDate=2019-03-18T15:02:09.529Z
```
will fail miserably whereas
```
https://trafficops.domain.test/api/1.4/deliveryservice_stats?interval=60s&metricType=kbps&serverType=edge&deliveryServiceName=dsXML_ID&startDate=2019-03-18T06:00:00.000Z&endDate=2019-03-18T15:02:09.000Z
```
works just fine. 

My guess is the server is failing to parse the non-zero millisecond values for some reason, which is truly bizarre because it's perfectly happy to _accept_ millisecond values - as long as they're exactly zero. Expected behavior is that arbitrary ISO 8601-format strings should parse without breaking.

### LINKED ISSUE #3802: Rewrite /jobs to Go
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/jobs` is handled by Perl

## Expected / new behavior:
`/jobs` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

### LINKED ISSUE #3803: Rewrite /jobs/{{id}} to Go
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/jobs/{{id}}` is handled by Perl

## Expected / new behavior:
`/jobs/{{id}}` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

### LINKED ISSUE #3804: Rewrite /user/current/jobs to Go
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/user/current/jobs` is handled by Perl

## Expected / new behavior:
`/user/current/jobs` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?

- [x] This PR resolves #1867, fixes #3116, closes #3803, closes #3804 and closes #3802 

Rewrites the "Jobs" endpoints from Perl to Go. This includes

- /jobs
    - `DELETE` method - *NEW* deletes an existing Job. Queues reval_pending on all servers.
    - `GET` method
    - `PUT` method - *NEW* replaces an existing Job. Queues reval_pending on all servers.
    - `POST` method - *NEW* creates a new Job. Queues reval_pending on all servers.
- /user/current/jobs
    - `GET` method
    - `POST` method - now requires privilege Role >= Portal, regardless of tenancy. No longer checks DS-to-user assignments when considering permissions.

Input timestamps are now accepted in RFC3339 format (with or without nanosecond precision) as well as our proprietary format used for "Last Updated" fields.

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops
- Traffic Ops Client (Go)
- Traffic Portal

## What is the best way to verify this PR?
Creating, deleting, editing, replacing and viewing Jobs. Output and behavior should match the provided documentation. Client code has associated tests, which should pass when run.

## The following criteria are ALL met by this PR
- [x] This PR includes tests
- [x] This PR includes documentation
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3998/
Test FAILed.

**Comment by ocket8888** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3999/
Test PASSed.

**Comment by mitchell852** [comment]
confused.  how does this relate to #3416 and #3187

**Comment by ocket8888** [comment]
No idea... that shouldn't be there

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4073/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4074/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4078/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4080/
Test PASSed.

**Comment by mitchell852** [comment]
@ocket8888 - can you update your PR description?

Queues reval_pending on all servers (for the cdn in which the ds belongs to)
PUT method - NEW replaces an existing Job (if not active?)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4084/
Test PASSed.

**Comment by mitchell852** [comment]
I'm getting a 500 error when curling `GET api/1.4/jobs`

File: traffic_ops/testing/api/v14/jobs_test.go [hunk 1]
```diff
@@ -103,3 +126,44 @@ func GetTestJobs(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("cannot GET DeliveryServices: %v - %v\n", err, toDSes)
+	}
+
+	dsIDNames := map[uint]string{}
+	for _, ds := range toDSes {
+		if ds.ID <= 0 {
+			t.Fatalf("Erroneous Delivery Service - has invalid ID: %+v\n", ds)
+		}
+		dsIDNames[uint(ds.ID)] = ds.XMLID
```
Comment (mhoppa) [inline traffic_ops/testing/api/v14/jobs_test.go]: is this map used all at?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 2]
```diff
@@ -0,0 +1,928 @@
...
+	if err := rows.Err(); err != nil {
+		return nil, nil, fmt.Errorf("Parsing db responses: %v", err), http.StatusInternalServerError
+	}
+
+	// This cannot be done in the scanning loop, because pq will throw an error if you try to make
+	// another query before exhausting the rows returned by an earlier query
+	filtered := []interface{}{}
+	for _, r := range returnable {
+		userErr, sysErr, errCode := IsUserAuthorizedToModifyDSXMLID(job.APIInfo(), *r.DeliveryService)
+		if sysErr != nil {
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: I know now the function will always return a sysErr if a userErr is returned but to protect ourselves going forward I wonder if this should change to `sysErr != nil || userErr != nil`

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 3]
```diff
@@ -0,0 +1,928 @@
...
+	job := tc.InvalidationJobInput{}
+	cType := r.Header.Get(http.CanonicalHeaderKey("content-type"))
+	if cType == tc.ApplicationJson || cType == "" {
+		decoder := json.NewDecoder(r.Body)
+		if err := decoder.Decode(&job); err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusBadRequest, errors.New("Unable to parse Invalidation Job"), fmt.Errorf("parsing jobs/ POST: %v", err))
+			return
+		}
+	} else {
+		w.Header().Set(http.CanonicalHeaderKey("accept"), strings.Join([]string{tc.ApplicationJson, "application/x-www-form-urlencoded", "multipart/form-data"}, ";"))
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: I think this is returning to the user this is the headers we support on content? (ignore if not) It says here we support `"application/x-www-form-urlencoded", "multipart/form-data"` but this handler will error out if it is not ApplicationJson?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 4]
```diff
@@ -0,0 +1,928 @@
...
+
+	w.Header().Set(http.CanonicalHeaderKey("content-type"), tc.ApplicationJson)
+	if errs := job.Validate(inf.Tx.Tx); len(errs) > 0 {
+		response := []tc.Alert{}
+		for _, e := range errs {
+			response = append(response, tc.Alert{e, tc.ErrorLevel.String()})
+		}
+
+		resp, err := json.Marshal(struct {
+			Alerts []tc.Alert `json:"alerts"`
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: isnt alerts defined in the lib package?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 5]
```diff
@@ -0,0 +1,928 @@
...
+		decoder := json.NewDecoder(r.Body)
+		if err := decoder.Decode(&input); err != nil {
+			userErr = fmt.Errorf("Unable to parse input: %v", err)
+			sysErr = fmt.Errorf("parsing input to PUT jobs?id=%s: %v", inf.Params["id"], err)
+			errCode = http.StatusBadRequest
+			api.HandleErr(w, r, inf.Tx.Tx, errCode, userErr, sysErr)
+			return
+		}
+	} else {
+		w.Header().Set(http.CanonicalHeaderKey("accept"), strings.Join([]string{tc.ApplicationJson, "application/x-www-form-urlencoded", "multipart/form-data"}, ";"))
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: same question here as above

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 6]
```diff
@@ -0,0 +1,928 @@
...
+			},
+		},
+		job,
+	}
+
+	resp, err := json.Marshal(response)
+	if err != nil {
+		sysErr = fmt.Errorf("encoding response: %v", err)
+		errCode = http.StatusInternalServerError
+		api.HandleErr(w, r, inf.Tx.Tx, errCode, nil, sysErr)
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: return here?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 7]
```diff
@@ -0,0 +1,928 @@
...
+		api.HandleErr(w, r, inf.Tx.Tx, errCode, userErr, sysErr)
+		return
+	}
+
+	if err := setRevalFlags(dsid, inf.Tx.Tx); err != nil {
+		api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, fmt.Errorf("setting reval flags: %v", err))
+	} else {
+		resp, err := json.Marshal(apiResponse{[]tc.Alert{{"Invalidation Job creation was successful", tc.SuccessLevel.String()}}, result})
+		if err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, fmt.Errorf("Marshaling JSON: %v", err))
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: return here?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 8]
```diff
@@ -0,0 +1,928 @@
...
+		w.Write(resp)
+		w.Write([]byte{'\n'})
+	}
+
+	api.CreateChangeLogRawTx(api.ApiChange, api.Updated+"content invalidation job: #"+strconv.FormatUint(*job.ID, 10), inf.User, inf.Tx.Tx)
+}
+
+// Used by DELETE requests to `/jobs`, deletes an existing content invalidation job
+func Delete(w http.ResponseWriter, r *http.Request) {
+	inf, userErr, sysErr, errCode := api.NewInfo(r, []string{"id"}, []string{"id"})
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: if a path always requires a query parameter should we make it part of the path?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 9]
```diff
@@ -0,0 +1,928 @@
...
+		&result.StartTime)
+	if err != nil {
+		sysErr = fmt.Errorf("deleting job #%s: %v", inf.Params["id"], err)
+		errCode = http.StatusInternalServerError
+		api.HandleErr(w, r, inf.Tx.Tx, errCode, nil, sysErr)
+		return
+	}
+
+	if err = setRevalFlags(dsid, inf.Tx.Tx); err != nil {
+		userErr = errors.New("Something wicked happened... Please queue server updates (or set reval_pending=true) manually to avoid problems!")
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: unsure if we should use the verbiage _Something wicked happened_ to the user  :P

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 10]
```diff
@@ -0,0 +1,928 @@
...
+		sysErr = fmt.Errorf("setting reval_pending after deleting job #%s: %v", inf.Params["id"], err)
+		errCode = http.StatusInternalServerError
+		api.HandleErr(w, r, inf.Tx.Tx, errCode, userErr, sysErr)
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: return here?

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go [hunk 11]
```diff
@@ -0,0 +1,928 @@
...
+	} else {
+		response := apiResponse{[]tc.Alert{tc.Alert{"Content invalidation job was deleted", tc.SuccessLevel.String()}}, result}
+		resp, err := json.Marshal(response)
+		if err != nil {
+			sysErr = fmt.Errorf("encoding response: %v", err)
+			errCode = http.StatusInternalServerError
+			api.HandleErr(w, r, inf.Tx.Tx, errCode, nil, sysErr)
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: return here?

File: traffic_ops/traffic_ops_golang/invalidationjobs/userinvalidationjobs.go [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+					Level: tc.SuccessLevel.String(),
+					Text: "Invalidation Job creation was successful.",
+				},
+				api.DeprecationWarning("POST /jobs"),
+			},
+			result,
+		}
+		resp, err := json.Marshal(respObj)
+		if err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, fmt.Errorf("Marshaling JSON: %v", err))
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/userinvalidationjobs.go]: return here?

File: traffic_ops/traffic_ops_golang/invalidationjobs/userinvalidationjobs.go [hunk 13]
```diff
@@ -0,0 +1,202 @@
...
+	}
+
+	type userResponse struct {
+		Alerts []tc.Alert `json:"alerts"`
+		Response []tc.UserInvalidationJob `json:"response"`
+	}
+
+	resp, err := json.Marshal(userResponse{[]tc.Alert{api.DeprecationWarning("GET /jobs?userId=")}, filtered})
+	if err != nil {
+		api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, fmt.Errorf("encoding user jobs response: %v", err))
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/invalidationjobs/userinvalidationjobs.go]: return here?

File: docs/source/api/jobs.rst [hunk 14]
```diff
@@ -21,78 +21,470 @@
...
+	User-Agent: python-requests/2.20.1
+	Accept-Encoding: gzip, deflate
+	Accept: */*
+	Connection: keep-alive
+	Cookie: mojolicious=...
+	Content-Length: 188
+	Content-Type: application/json
+
+	{
+		"assetUrl": "http://origin.infra.ciab.test/.*",
```
Comment (mitchell852) [inline docs/source/api/jobs.rst]: this is related to one of my earlier comments. if we allow assetUrl to be origin fqdn + path, can't somebody create an invalidation content request for an origin that is not theirs?

File: lib/go-tc/invalidationjobs_test.go [hunk 15]
```diff
@@ -0,0 +1,42 @@
...
+import "fmt"
+
+func ExampleInvalidationJobInput_TTLHours_duration() {
+	j := InvalidationJobInput{nil, nil, nil, "121m"}
+	ttl, e := j.TTLHours()
+	if e != nil {
+		fmt.Printf("Error: %v\n", e)
+	}
+	fmt.Println(ttl)
+	// Output: 2
```
[the remark this answers is not in the document]
Comment (ocket8888) [reply lib/go-tc/invalidationjobs_test.go]: That's how examples work, the testing runtime checks it for me.

[the remark this answers is not in the document]
Comment (mhoppa) [reply lib/go-tc/invalidationjobs_test.go]: I didnt know that cool!

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go (hunk 3 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: Oh, that was a part of an earlier, misguided effort to make this the place where content negotiation takes place. It shouldn't still be in there.

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go (hunk 4 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: yep

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go (hunk 6 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: Actually, I don't return here so that the changelog is created whether or not an encoding error occurs. If this error occurs, the job has already been created, so it's too late to bail.

Comment (mhoppa) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: we roll back though https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/api/api.go#L111?

Comment (mhoppa) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: yeah that ^ :)

File: traffic_ops/testing/api/v14/jobs_test.go (hunk 1 above)
Comment (ocket8888) [reply traffic_ops/testing/api/v14/jobs_test.go]: I think I planned to at one point, but no, it seems not.

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go (hunk 2 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: Nah. I can do better. That function should just return a boolean and an error. There's no reason to try to parse all that junk out in there, it's a useless mess.

File: docs/source/api/jobs.rst [hunk 16]
```diff
@@ -21,78 +21,470 @@
...
+	| id   | yes      | The integral, unique identifier of the content invalidation job being modified |
+	+------+----------+--------------------------------------------------------------------------------+
+
+:assetUrl: A regular expression - matching URLs will be operated upon according to ``keyword``
+
+	.. note:: Unlike in the payloads of POST_ and PATCH_ requests to this endpoint, this must be a **full** URL regular expression, as it is **not** combined with the :ref:`ds-origin-url` of the :term:`Delivery Service` identified by ``deliveryService``.
+
+:createdBy:       The username of the user who initiated the job\ [#readonly]_
+:deliveryService: The :ref:`ds-xmlid` of the :term:`Delivery Service` on which this job operates\ [#readonly]_ - unlike POST_ and PATCH_ request payloads, this cannot be an integral, unique identifier
+:id:              An integral, unique identifier for this job\ [#readonly]_
```
[the remark this answers is not in the document]
Comment (ocket8888) [reply docs/source/api/jobs.rst]: In a `PUT` request, you must provide a full representation of the object, even if fields are unchanged.

File: docs/source/api/jobs.rst (hunk 14 above)
Comment (ocket8888) [reply docs/source/api/jobs.rst]: If you _don't_ allow that, then Delivery Services with multiple origins can potentially be incapable of content revalidations. It's not ideal, but changing it means redefining what a job does, which potentially involves a loss of functionality.

This behavior is consistent with the current method of job creation under `/user/current/jobs`, so any 'fix' here wouldn't be effective.

File: docs/source/api/jobs.rst [hunk 17]
```diff
@@ -21,78 +21,470 @@
...
+-----------------
+.. table:: Query Parameters
+
+	+------+----------+--------------------------------------------------------------------------------+
+	| Name | Required | Description                                                                    |
+	+======+==========+================================================================================+
+	| id   | yes      | The integral, unique identifier of the content invalidation job being modified |
+	+------+----------+--------------------------------------------------------------------------------+
+
+:assetUrl: A regular expression - matching URLs will be operated upon according to ``keyword``
```
[the remark this answers is not in the document]
Comment (ocket8888) [reply docs/source/api/jobs.rst]: I think you've gotten your PUT and POST confused. POST expects a relative path regex, while PUT allows you to input a full URL.

File: lib/go-tc/invalidationjobs.go [hunk 18]
```diff
@@ -0,0 +1,361 @@
...
+	if job.StartTime == nil {
+		errs = append(errs, "'startTime' is a required field!")
+	} else if job.StartTime.Time.Before(time.Now()) {
+		errs = append(errs, "'startTime' must be in the future!")
+	}
+
+	if job.TTL == nil {
+		errs = append(errs, "'ttl' is a required field!")
+	} else if _, err := job.TTLHours(); err != nil {
+		errs = append(errs, "'ttl' must be a number of hours, or a duration string e.g. '48h'!")
```
[the remark this answers is not in the document]
Comment (ocket8888) [reply lib/go-tc/invalidationjobs.go]: To some degree, yes. I've done what can be done with ozzo's library.

File: traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go (hunk 8 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go]: Mainly because it's less endpoints to document. But also because it's not necessarily true that the query parameter will always be required, for example suppose we want to DELETE all jobs where the start time is at least a week ago and the time to live is less than a week.

File: docs/source/api/jobs.rst (hunk 14 above)
Comment (mitchell852) [reply docs/source/api/jobs.rst]: ok, so is there some type of check that when i'm doing a PUT to a job, that the assetUrl lines up with one of the origins of the delivery service? if not, this would expose a security hole imo.

Comment (ocket8888) [reply docs/source/api/jobs.rst]: So, Job creation specifically combines the Regex with the Delivery Service's primary origin from the origin table - that's the only one I'll be checking, then.

**Comment by ocket8888** [comment]
Ozzo validations are broken, this is untestable until I fix them.

**Comment by ocket8888** [comment]
Fixed the ozzo problems. It can't handle `Required` on `*time.Time` fields of structs - probably actually anything that isn't an integral, floating point, or string, if I were to guess.

**Comment by ocket8888** [comment]
You need to use the primary origin, it's the only one that'll work.

**Comment by mitchell852** [comment]
> You need to use the primary origin, it's the only one that'll work.

Maybe the alert needs to say "primary"

**Comment by mitchell852** [comment]
> You need to use the primary origin, it's the only one that'll work.

also, `one.two.com` is my primary and `three.four.com` is the 2nd origin i added to the ds.

**Comment by ocket8888** [comment]
Content invalidation jobs have never worked that way for MSO Delivery Services - at least not through the API. I think changing that is better left to a later feature request PR.

**Comment by mitchell852** [comment]
> Content invalidation jobs have never worked that way for MSO Delivery Services - at least not through the API. I think changing that is better left to a later feature request PR.

Well, this is a new endpoint, right? (POST /api/jobs) Why not build it to work in all scenarios?

I guess you could just leave it to create ONE job and then later if the mailing list is ok with it change it to create X jobs, right? without that being considered an api breaking change. 

I just worry about APIs getting written and then being set in versioning stone.

**Comment by ocket8888** [comment]
I'm not sure, but I think more thought needs to go into the implementation either way. Should it automatically create one job for each origin? Or make you specify the full URL pattern and make sure it conforms to at least one origin, so you need to use the endpoint 4 times for one Delivery Service? But what if you wanted different patterns operating on different origins? Or maybe the user should just have to also specify an origin or list of origins, the default behavior being "all"?

**Comment by mitchell852** [comment]
> I'm not sure, but I think more thought needs to go into the implementation either way. Should it automatically create one job for each origin? Or make you specify the full URL pattern and make sure it conforms to at least one origin, so you need to use the endpoint 4 times for one Delivery Service? But what if you wanted different patterns operating on different origins? Or maybe the user should just have to also specify an origin or list of origins, the default behavior being "all"?

Ok so what to do with this PR? you want to ask those questions on the mailing list? I'm pretty sure I'd just vote for the simple solution: If you create a "job" for a DS that has 4 origins, behind the scenes 4 jobs are created (one for each origin)...

**Comment by ocket8888** [comment]
idk, sounds like a feature request on top of a rewrite, to me. To be fair, so was a lot of the stuff I put into this.

**Comment by mitchell852** [comment]
> idk, sounds like a feature request on top of a rewrite, to me. To be fair, so was a lot of the stuff I put into this.

i can buy that. want to create an issue capturing how invalidate content on ds's with multiple origins doesn't really work? i guess it's a bug?

**Comment by ocket8888** [comment]
#3969
