### PR TITLE
Fixed CiaB build issue

### LINKED ISSUE #4246: Service 'trafficops-perl' failed to build: [...] dial tcp: lookup geolite.maxmind.com: No address associated with hostname
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [x] CDN in a Box
- [x] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The `trafficops-perl` Docker image for CDN-in-a-Box fails to build because the geolite.maxmind.com subdomain no longer resolves.

## Expected / new behavior:

`trafficops-perl` should build successfully.

## Minimal reproduction of the problem with instructions:

```shell script
docker rmi cdn-in-a-box_perl;
docker-compose build trafficops-perl;
```

Failed build log follows:
```shell script
Building trafficops-perl
Step 1/16 : FROM centos:7
 ---> 5e35e350aded
Step 2/16 : LABEL   name="Traffic Ops Perl"         maintainer="dev@trafficcontrol.apache.org"
 ---> Using cache
 ---> cfa2c7d6e139
Step 3/16 : EXPOSE 443
 ---> Using cache
 ---> f20b3afea2b4
Step 4/16 : ENV MOJO_MODE production
 ---> Using cache
 ---> 07c71701c21e
Step 5/16 : RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 &&     rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 &&     rpm --import https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG &&     yum -y update ca-certificates &&     yum-config-manager --add-repo https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64 &&     yum install -y         epel-release         pgdg-redhat-latest &&     yum install -y         bind-utils         cpanminus         expat-devel         gcc-c++         gettext         git         iproute         jq         libcurl         libcurl-devel         libidn-devel         libpcap-devel         mkisofs         net-tools         nmap-ncat         openssl         openssl-devel         perl         perl-core         perl-Crypt-ScryptKDF         perl-DBD-Pg         perl-DBI         perl-DBIx-Connector         perl-Digest-SHA1         perl-JSON         perl-JSON-PP         perl-libwww-perl         perl-TermReadKey         perl-Test-CPAN-Meta         perl-WWW-Curl         postgresql96         postgresql96-devel         postgresql96-libs         tar &&    yum -y clean all
 ---> Using cache
 ---> 9c6488d6690d
Step 6/16 : ADD https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz /
ERROR: Service 'trafficops-perl' failed to build: ADD failed: Get https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz: dial tcp: lookup geolite.maxmind.com: No address associated with hostname
```

## Anything else:

MaxMind no longer publicly hosts their downloads, instead requiring you to register (for free). See: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

This also affects the [Traffic Ops post-install script](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/install/bin/_postinstall#L666).

[Docs](https://github.com/apache/trafficcontrol/commit/6d3deddf35#diff-85c97264f817e3f1ae5561fdc60f58a1R169-R171) will need to be updated to remove references to geolite.maxmind.com.

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #4246 

Instead of download the Maxmind database, this PR changes the TO Perl build for CiaB to use the database that's bundled into the Traffic Router test package.

## Which Traffic Control components are affected by this PR?
- CDN in a Box

## What is the best way to verify this PR?
Build CDN-in-a-Box, notice no errors and that TR works

## If this is a bug fix, what versions of Traffic Control are affected?
- master
- 4.0.0 (RC1)

## The following criteria are ALL met by this PR
- [x] Tests are unnecessary
- [x] Documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: infrastructure/cdn-in-a-box/traffic_ops/trafficops-init.sh [hunk 1]
```diff
@@ -102,7 +102,7 @@ load_data_from() {
 load_data_from /traffic_ops_data
 
 # Copy the free MaxMind GeoLite DB to TrafficOps public directory
-tar -C /var/tmp -zxpvf /GeoLite2-City.tar.gz
-geo_dir=$(find /var/tmp -maxdepth 1 -type d -name GeoLite2-City\*)
-gzip -c "$geo_dir/GeoLite2-City.mmdb" > "$TO_DIR/public/GeoLite2-City.mmdb.gz"
-chown trafops:trafops "$TO_DIR/public/GeoLite2-City.mmdb.gz"
+# tar -C /var/tmp -zxpvf /GeoLite2-City.tar.gz
```
Comment (mhoppa) [inline infrastructure/cdn-in-a-box/traffic_ops/trafficops-init.sh]: should we just remove this code instead of commenting out?

Comment (ocket8888) [reply infrastructure/cdn-in-a-box/traffic_ops/trafficops-init.sh]: yes
