### PR TITLE
Traffic Monitor excessive log errors fix

### LINKED ISSUE #4825: TM error log spam for "incomparable stat type int"
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

This error message is currently getting spammed in the TM logs:
```
ERROR: stat.go:292: 2020-06-24T15:22:54.408932036Z: Adding result from mycache-01: some stats could not be added: cannot add stat system.inf.speed: incomparable stat type int; cannot add stat system.configReloads: incomparable stat type int; cannot add stat system.lastReload: incomparable stat type int; cannot add stat system.astatsLoad: incomparable stat type int; cannot add stat system.configReloadRequests: incomparable stat type int; cannot add stat system.lastReloadRequest: incomparable stat type int
```
It seems to be new as of TM 4.1.0 and is unclear what the actual effects of the bug are.

## Expected / new behavior:

This error message should be investigated and fixed.

## Minimal reproduction of the problem with instructions:

Start up TM (master or 4.1.0) in your environment and wait for it to start polling caches. This error message appears to be printed for every cache polled.

## Anything else:

From @zrhoffman:

> issue is at line 193 in /trafficcontrol/traffic_monitor/threadsafe/resultstathistory.go
it won't let you compare history[0].Val and stat as int type even though they are both ints

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #4825

## Which Traffic Control components are affected by this PR?
- Traffic Monitor

## What is the best way to verify this PR?
Run Traffic Monitor with some caches to poll, observe no error spam in the logs.

## If this is a bug fix, what versions of Traffic Control are affected?
- master
- 4.1

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: traffic_monitor/cache/astats.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ import (
 	"github.com/apache/trafficcontrol/lib/go-log"
 	"github.com/apache/trafficcontrol/traffic_monitor/dsdata"
 	"github.com/apache/trafficcontrol/traffic_monitor/todata"
-	"github.com/json-iterator/go"
+	jsoniter "github.com/json-iterator/go"
```
Comment (rawlinp) [inline traffic_monitor/cache/astats.go:41]: Why is this necessary?

Comment (ocket8888) [reply traffic_monitor/cache/astats.go:41]: It wasn't, I didn't do it - at least not intentionally. I installed an IDE to help me wade through the confusing naming schemes of TM code, and I'd bet it did that for me automatically.

I can change it back if you want

Comment (rawlinp) [reply traffic_monitor/cache/astats.go:41]: Ok, it doesn't seem to be affecting anything but it doesn't appear to be used either, which is weird because Go won't let you compile with unused imports. I guess it must be `init`ing something.
