### PR TITLE
TO: Give a better error message when deleting an object being referenced

### LINKED ISSUE #2729: Improve Error Message when attempting to delete a Division that has assigned Regions
If you create a new Division, then assign a Region to it and then attempt to delete the Division, you get a _database access error_. We should provide a better error message in the client to improve the user experience. Something like, "Division <xyz> has Regions associated with it and can not be deleted."

### LINKED ISSUE #3410: Deleting a profile assigned to a server results in internal server error
ERROR:  update or delete on table "profile" violates foreign key constraint "fk_contentserver_atsprofile1" on table "server"

instead a 400 should be returned with a message like "can't delete profiles that are currently in use"

### PR DESCRIPTION
**Pull request by moltzaum**
## Which issue is fixed by this PR? If not related to an existing issue, what does this PR do?

Known Examples:
* deleting coordinate with a cachegroup
* deleting profile with a server (Fixes #3410)
* deleting division with assigned region (Fixes #2729)

Any endpoint that uses the generic cruder should be fixed (though, the disclaimer comment at the top of the function should also be read). An endpoint that doesn't use the generic cruder can use api.ParseDBError to get the same result.

## Which TC components are affected by this PR?

-  Traffic Ops

### (If no tests are part of this PR, please provide explanation as to why no tests are included.)

* Test the specific cases mentioned in the issues.
* Run the integration tests.
* Analyze the comment and understand the assumptions it makes.
If the current assumptions are not reasonable the logic can instead be handled outside `api.ParseDBError`, even being privatized to the generic delete function.

I made a test for the divisions-regions issue. Divisions use the generic delete, so the test pretty much tests the generic function.

## Check all that apply

- [x] This PR includes new tests
- [x] This PR does not need to include documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [x] This PR includes all required license headers
- [x] This PR does not include a database migration
- [x] This PR does not fix a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3412/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3414/
Test PASSed.

File: traffic_ops/testing/api/v14/divisions_test.go [hunk 1]
```diff
@@ -16,19 +16,42 @@ package v14
...
+	WithObjs(t, []TCObj{Parameters, Divisions, Regions}, func() {
+		TryToDeleteDivision(t)
 		UpdateTestDivisions(t)
 		GetTestDivisions(t)
 	})
 }
 
+func TryToDeleteDivision(t *testing.T) {
+	division := testData.Divisions[0]
+	resp, _, err := TOSession.DeleteDivisionByName(division.Name)
```
Comment (rob05c) [inline traffic_ops/testing/api/v14/divisions_test.go]: Doesn't compile, `resp` isn't used, needs to be `_, _, err := TOSession.DeleteDivisionByName(division.Name)`

File: traffic_ops/testing/api/v14/divisions_test.go [hunk 2]
```diff
@@ -16,19 +16,42 @@ package v14
...
+		t.Errorf("should not be able to delete a division prematurely")
+		return
+	}
+
+	if strings.Contains(err.Error(), "Resource not found.") {
+		t.Errorf("division with name %v does not exist", division.Name)
+		return
+	}
+
+	if strings.Contains(err.Error(), "This division is currently used by regions.") {
```
Comment (rob05c) [inline traffic_ops/testing/api/v14/divisions_test.go]: The test doen't compile, but it looks like this won't pass, needs to be `cannot delete division because it is being used by a region`.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3469/
Test FAILed.

File: traffic_ops/testing/api/v14/divisions_test.go (hunk 2 above)
Comment (moltzaum) [reply traffic_ops/testing/api/v14/divisions_test.go]: Looks like I need to use `DeleteRegionByID`. Should I use a status code instead of looking at the error message so that this is less brittle? A bad request does not necessarily indicate the error I'm actually testing for, so I'm not sure what the best way is.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3470/
Test PASSed.
