### PR TITLE
Fix bug that causes DS requests to fulfill immediately while other requests are still open

### LINKED ISSUE #2595: trying to delete a ds that has an open ds request is successful
With ds requests turned on in traffic_portal_properties.json, all changes to a ds (create, update or delete) result in the creation of a ds request.

however, if you are an admin, you can select "fulfill immediately" for the ds request. this will result in:

1. creating a ds request to delete the ds and immediately marking it as complete
2. deleting the ds

#1 should fail if an existing ds request is open (status != complete) for the ds which it does but #2 still succeeds (which it should not).

UPDATE:
@dsouza93 found this issue as well (#3717), the underlying issue sounds the same:

When there is an open delivery service request for a delivery service, and a user attempts to change a value on the delivery service and "fulfill immediately", Traffic Portal displays an error that there is an active delivery service request open for said delivery service. The delivery service data is then updated anyway. I am not sure if this is intended behavior and is to serve as a warning or if it supposed to prevent updates, but thought I'd bring it up.

My specific use case was when there was a delivery service request in the "pending" status with the only action left was to "complete" the request. I then set the delivery service itself to "active"/"fulfill immediately" without completing the delivery service request.

I am unsure if this will occur when other fields are altered or if it will occur when DS requests are in other states.

### PR DESCRIPTION
**Pull request by alexluckerman**
I also made a small tweak to the DS requests TP test as it seemed to be failing locally for me because it wasn't waiting long enough for TP to change its URL

## What does this PR (Pull Request) do?

- [x] This PR fixes #2595

## Which Traffic Control components are affected by this PR?

- Traffic Portal

This is a small bug that should not require documentation or a changelog entry

## What is the best way to verify this PR?

Enable DS requests in TP and run the DS requests TP test, then manually verify that updating or deleting a DS while at least one DS request for that same DS is open fails

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

File: traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js [hunk 1]
```diff
@@ -22,6 +22,21 @@ var FormEditDeliveryServiceController = function(deliveryService, origin, type,
 	// extends the FormDeliveryServiceController to inherit common methods
 	angular.extend(this, $controller('FormDeliveryServiceController', { deliveryService: deliveryService, dsCurrent: deliveryService, origin: origin, type: type, types: types, $scope: $scope }));
 
+	var confirmNoOutstandingRequests = function(deliveryService) {
+		deliveryServiceRequestService.getDeliveryServiceRequests()
+		.then(
+			function(dsRequests) {
+				// search all requests for those that are not completed and share the same deliveryservice id
+				angular.forEach(dsRequests, function(value) {
+					if (value.status != 'complete' && value.deliveryService.id == deliveryService.id) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: you should short circuit this condition by putting this as the first check as it will fail in most instances and then the 2nd check is never evaluated (might get you a little performance for free)

`if (value.deliveryService.id == deliveryService.id && value.status != 'complete') {`

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: also, if you rename the function something like `hasOpenRequest` and check for the statuses we know to be open (draft, submitted or pending), i think your other condition will read a little nicer

`if (options.status.id == $scope.COMPLETE && !hasOpenRequest(deliveryService))`

the reason i mention this is because this ds request code is a bit of a mess already as i'm sure you noticed, so easy to understand naming will make everyone's life easier.

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: so i've been thinking about this a bit more. the way you are performing this check is rather expensive. you are fetching all the DS requests (open or closed) and then looping thru them to determine if there is an open one for this ds when instead this problem could easily be solved by fixing the order of operations. check out the current code:

`				if (options.status.id == $scope.COMPLETE) {
					deliveryServiceService.updateDeliveryService(deliveryService).
						then(
							function() {
								$state.reload(); // reloads all the resolves for the view
								messageModel.setMessages([ { level: 'success', text: 'Delivery Service [ ' + deliveryService.xmlId + ' ] updated' } ], false);
								createDeliveryServiceUpdateRequest(dsRequest, options.comment, true);
							},
							function(fault) {
								$anchorScroll(); // scrolls window to top
								messageModel.setMessages(fault.data.alerts, false);
							}
						);
				} else {
					createDeliveryServiceUpdateRequest(dsRequest, options.comment, false);
				}
`

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: so i've been thinking about this a bit more. the way you are performing this check is rather expensive. you are fetching all the DS requests (open or closed) and then looping thru them to determine if there is an open one for this ds when instead this problem could easily be solved by fixing the order of operations. check out the current code:

```if (options.status.id == $scope.COMPLETE) {
					deliveryServiceService.updateDeliveryService(deliveryService).
						then(
							function() {
								$state.reload(); // reloads all the resolves for the view
								messageModel.setMessages([ { level: 'success', text: 'Delivery Service [ ' + deliveryService.xmlId + ' ] updated' } ], false);
								createDeliveryServiceUpdateRequest(dsRequest, options.comment, true);
							},
							function(fault) {
								$anchorScroll(); // scrolls window to top
								messageModel.setMessages(fault.data.alerts, false);
							}
						);
				} else {
					createDeliveryServiceUpdateRequest(dsRequest, options.comment, false);
				}```

The order is simply backwards. Currently, it tries to update the ds (which succeeds) and THEN it tries to create a ds request (which fails because there is already one open).

So if  you simply flip the order around and only make it update the ds IF the creation of the ds request succeeds, then problem solved.

File: traffic_portal/test/end_to_end/DeliveryServiceRequests/delivery-service-requests-spec.js [hunk 2]
```diff
@@ -144,6 +144,7 @@ describe('Traffic Portal Delivery Service Requests', function() {
 		pageData.deleteButton.click();
 		pageData.confirmWithNameInput.sendKeys(mockVals.xmlId + ' request');
 		pageData.deletePermanentlyButton.click();
+		browser.sleep(250);
 		expect(browser.getCurrentUrl().then(commonFunctions.urlPath)).toEqual(commonFunctions.urlPath(browser.baseUrl)+"#!/delivery-service-requests");
```
Comment (ocket8888) [inline traffic_portal/test/end_to_end/DeliveryServiceRequests/delivery-service-requests-spec.js]: What's the problem being solved here? A comparison before the promise resolves? Or is `browser.getCurrentUrl()` returning the wrong value if you don't wait a bit first? If it's the former I'm gonna open an issue to get this stuff converted to `async`/`await`, because that'd make waiting for all these things much easier.

Comment (alexluckerman) [reply traffic_portal/test/end_to_end/DeliveryServiceRequests/delivery-service-requests-spec.js]: Based off the test I was working on this morning, it seems to me that `expect()` will wait until promises are resolved before performing its comparisons, so the issue is just `browser.getCurrentUrl()` needs a bit of wait before it returns the correct value. But I couldn't find anything to corroborate that online, so ¯\\\__(ツ)__/¯

File: traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js (hunk 1 above)
Comment (alexluckerman) [reply traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: Thanks, that makes things a lot easier

File: traffic_portal/test/end_to_end/DeliveryServiceRequests/delivery-service-requests-spec.js (hunk 2 above)
Comment (ocket8888) [reply traffic_portal/test/end_to_end/DeliveryServiceRequests/delivery-service-requests-spec.js]: As far as I could tell from their terrible docs, it doesn't do anything special with Promises. I guess I can always just try it, and if I'm wrong things should randomly break.

File: traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js [hunk 3]
```diff
@@ -201,18 +197,16 @@ var FormEditDeliveryServiceController = function(deliveryService, origin, type,
 				// if the user chooses to complete/fulfill the update request immediately, the ds will be updated and behind the
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: can you rewrite this comment? it's not true anymore.

File: traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js [hunk 4]
```diff
@@ -61,44 +61,40 @@ var FormEditDeliveryServiceController = function(deliveryService, origin, type,
 
 			// if the user chooses to complete/fulfill the delete request immediately, the ds will be deleted and behind the
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: can you update this comment as well. it's backwards.

**Comment by mitchell852** [comment]
@alexluckerman - is this the command you are running to run the single ds request UI test?

`protractor conf.js --specs DeliveryServiceRequests/delivery-service-requests-spec.js` 

because i'm getting

`11 specs, 11 failures`

**Comment by alexluckerman** [comment]
@mitchell852 I've been using `protractor conf-delivery-service-requests.js`, I believe it's in a separate file since DS requests are an optional feature in TP

**Comment by mitchell852** [comment]
This change also fixed #3512
