### PR TITLE
Fixes service_categories response to POST API

### LINKED ISSUE #7130: POST to `service_categories` returns blank name
## This Bug Report affects these Traffic Control components:
- Traffic Ops

## Current behavior:
```
$ topost -kp service_categories '{"name": "test"}'
{
	"alerts": [
		{
			"text": "serviceCategory was created.",
			"level": "success"
		}
	],
	"response": {
		"lastUpdated": "2022-10-12 17:57:14+00",
		"name": ""
	}
}
```

## Expected behavior:
According to the docs (and what would make sense) the `name` field is supposed to be populated with the name it actually created. Since the current docs example shows it working that way, I'm going to assume that it used to so this is a regression bug.

## Steps to reproduce:
`topost -kp service_categories '{"name": "test"}'`

### PR DESCRIPTION
**Pull request by jagan-parthiban**
Fixes #7130

<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Run a `/POST` call to `/api/4.0/service_categories"` and confirm that success response includes name. As well ensure existing functionality (CRUDER, eg: `/server_capabiilities` ) still works as intended.

## If this is a bugfix, which Traffic Control versions contained the bug?

7.0.1

## PR submission checklist
- [ ] This PR has tests 
- [ ] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/api/generic_crud.go [hunk 1]
```diff
@@ -119,19 +119,39 @@ func GenericCreateNameBasedID(val GenericCreator) (error, error, int) {
...
 	rowsAffected := 0
-	for resultRows.Next() {
-		rowsAffected++
-		if err := resultRows.Scan(&lastUpdated); err != nil {
-			return nil, errors.New(val.GetType() + " create scanning: " + err.Error()), http.StatusInternalServerError
+
+	// Only when the type is of serviceCategory, &name is scanned and returned from the DB.
+	// Else return only &lastUpdated.
+	if val.GetType() == "serviceCategory" {
+		for resultRows.Next() {
```
Comment (rimashah25) [inline traffic_ops/traffic_ops_golang/api/generic_crud.go:129]: You can place the if get type block after for loop, so as to not to repeat the same code twice.

Comment (jagan-parthiban) [reply traffic_ops/traffic_ops_golang/api/generic_crud.go]: Suggestion Implemented

**Review by rimashah25 — APPROVED** [review]
LGTM. Tested it on local and see the actual name in alert response.
