### PR TITLE
Fail install_goose.sh if installing goose fails

### LINKED ISSUE #4592: install_goose.sh returns exit code 0 when it fails
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [x] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

If installing Goose fails, `install_goose.sh` still returns an exit code of 0.

## Expected / new behavior:

`install_goose.sh` should return a nonzero exit code if any part of it fails.

## Minimal reproduction of the problem with instructions:

1. Disconnect from Internet

2.
    ```shell script
    ./install_goose.sh
    echo $?
    ```

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4592

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Traffic Ops

## What is the best way to verify this PR?

Verify `install_goose.sh` returns a nonzero exit code when it fails and 0 when it succeeds

## If this is a bug fix, what versions of Traffic Control are affected?

- master (6d8cbe9c60)
- 4.0.0

## The following criteria are ALL met by this PR

- [x] I have explained why tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

* install_goose.sh has no tests
* Documentation is unnecessary because intended behavior does not change.

### CODE REVIEW

File: traffic_ops/install/bin/install_goose.sh [hunk 1]
```diff
@@ -14,11 +14,13 @@
...
+export GOPATH=/opt/traffic_ops/go;
+mkdir -p $GOPATH;
 
-go get bitbucket.org/liamstask/goose/cmd/goose
-go get github.com/lib/pq
+go get bitbucket.org/liamstask/goose/cmd/goose;
+go get github.com/lib/pq;
 
-echo "Successfully installed goose to $GOPATH/bin/goose"
+echo "Successfully installed goose to $GOPATH/bin/goose";
```
Comment (rawlinp) [inline traffic_ops/install/bin/install_goose.sh:26]: why the `;`?

Comment (zrhoffman) [reply traffic_ops/install/bin/install_goose.sh:26]: Why generally? I personally find semicolons nice if I am copying and pasting an entire script into a terminal, because if the TTY misses a newline, it still works. Since that is not related to this PR though, I can remove them.

Comment (zrhoffman) [reply traffic_ops/install/bin/install_goose.sh]: Removed in 6d3edb9c66

Comment (rawlinp) [reply traffic_ops/install/bin/install_goose.sh]: Yeah, I was just curious why generally since I haven't seen that as a style before.
