### PR TITLE
Removing restangular

### LINKED ISSUE #3571: TP: remove Restangular dependency
At one point, I added Restangular (https://github.com/mgonto/restangular) to help simplify the TP services (traffic_portal/app/src/common/api), however, many of the services use Restangular and others do not. It might make sense to just remove the dependency on Restangular altogether so the service code can be consistent and one less dependency.

### LINKED ISSUE #4194: TP: Generate ISO view won't resolve
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Clicking on the `Generate ISO` menu item does nothing.

image

## Expected / new behavior:
Clicking on the `Generate ISO` menu item should display the form required to generate an ISO.

## Minimal reproduction of the problem with instructions:
1. Click on the `Generate ISO` menu item

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
Removes a dependency that Traffic Portal had on Restangular.

- [x] This PR resolves #3571 and fixes #4194 

## Which Traffic Control components are affected by this PR?
- Traffic Portal

Traffic Portal dependencies are not individually documented, and so no changes are necessary.

## What is the best way to verify this PR?
No functionality should have changed (except that errors will now be logged instead of ignored in many cases), so the existing tests should all pass.

Jeremy: actually, the only way to truly verify that the functionality did not change is to:
1. run the UI tests (which is a very small subset of all TP functionality)
2. manually verify the functionality associated with ALL the services functions that changed just to be sure all is well.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3717/
Test PASSed.

File: traffic_portal/app/src/common/api/ASNService.js [hunk 1]
```diff
@@ -17,54 +17,75 @@
...
-                },
-                function(fault) {
-                    messageModel.setMessages(fault.data.alerts, false);
-                }
-            );
+        return $http.post(ENV.api['root'] + 'asns', asn).then(
+            function(result) {
+                messageModel.setMessages([{level: 'success', text: 'ASN created' }], true);
+                console.info("created new ASN: ", result.data.response);
+                return result;
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/ASNService.js]: this isn't navigating back to the asns table after create. probably because your `return` is before the navigatetoPath

File: traffic_portal/app/src/common/api/AuthService.js [hunk 2]
```diff
@@ -21,56 +21,48 @@ var AuthService = function($rootScope, $http, $state, $location, $q, $state, htt
...
                 }
-            );
+            },
+            function(err) {
+               console.error(err);
+            }
+        );
     };
 
     this.tokenLogin = function(token) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/AuthService.js]: i would just leave the tokenLogin function alone unless your sure this doesn't change behavior. seems like it would.

File: traffic_portal/app/src/common/api/CDNService.js [hunk 3]
```diff
@@ -17,252 +17,199 @@
...
+            function(result) {
+                return result.data.response;
+            },
+            function(err) {
+                console.error(err);
+            }
+        );
     };
 
     this.generateDNSSECKeys = function(dnssecKeysRequest) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/CDNService.js]: this doesn't seem to work

https://localhost:8442/#!/cdns/2/dnssec-keys/generate and hit regenerate:

```
shared-libs.js?built=1558556756347:66530 TypeError: Cannot read property 'then' of undefined
    at generate (FormGenerateCdnDnssecKeysController.js:25)
```

File: traffic_portal/app/src/common/api/CDNService.js [hunk 4]
```diff
@@ -17,252 +17,199 @@
...
+            function(result) {
+                return result;
+            },
+            function(err) {
+                messageModel.setMessages(err.data.alerts, false);
+            }
+        );
     };
 
 	this.regenerateKSK = function(kskRequest, cdnKey) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/CDNService.js]: this is not working either. same sort of error:

```
shared-libs.js?built=1558556756347:66530 TypeError: Cannot read property 'then' of undefined
    at generate (FormRegenerateKskController.js:25)
```

File: traffic_portal/app/src/common/api/CapabilityService.js [hunk 5]
```diff
@@ -17,68 +17,69 @@
...
+			function(err) {
+				console.error(err);
+				return err;
+			}
+		);
 	};
 
 	this.getCapability = function(name) {
-		return Restangular.one("capabilities", name).get();
+		return $http.get(ENV.api['root'] + 'capabilities/' + cap).then(
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/CapabilityService.js]: this is broken. i think replace cap with name.

File: traffic_portal/app/src/common/api/CoordinateService.js [hunk 6]
```diff
@@ -17,66 +17,60 @@
  * under the License.
  */
 
-var CoordinateService = function($http, $q, Restangular, locationUtils, messageModel, ENV) {
+var CoordinateService = function($http, locationUtils, messageModel, ENV) {
 
     this.getCoordinates = function(queryParams) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/CoordinateService.js]: not sure what's up here but https://localhost:8442/#!/coordinates looks like

image

File: traffic_portal/app/src/common/api/AuthService.js (hunk 2 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/api/AuthService.js]: actually,  nm. i think this is fine

File: traffic_portal/app/src/common/api/CoordinateService.js (hunk 6 above)
Comment (ocket8888) [reply traffic_portal/app/src/common/api/CoordinateService.js]: I think I fixed that - will check in a second

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3721/
Test PASSed.

File: traffic_portal/app/src/common/api/CoordinateService.js (hunk 6 above)
Comment (ocket8888) [reply traffic_portal/app/src/common/api/CoordinateService.js]: yep, fixed.

File: traffic_portal/app/src/common/api/ChangeLogService.js [hunk 7]
```diff
@@ -17,19 +17,25 @@
...
 		return httpService.get(ENV.api['root'] + 'logs/newcount', { ignoreLoadingBar: true });
 	};
 
 	this.getChangeLogs = function(queryParams) {
-		// broadcast an event that will zero out the change log count immediately
 		$rootScope.$broadcast('changeLogService::getChangeLogs');
-		return Restangular.all('logs').getList(queryParams);
+		return $http.get(ENV.api['root'] + 'logs', {params: queryParams}).then(
+			function(result) {
+				return result.data.response;
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/ChangeLogService.js]: shared-libs.js?built=1558639738692:66530 TypeError: Cannot read property 'data' of undefined
    at ChangeLogModel.js:45

File: traffic_portal/app/src/common/api/AuthService.js [hunk 8]
```diff
@@ -21,56 +21,48 @@ var AuthService = function($rootScope, $http, $state, $location, $q, $state, htt
...
-                    $rootScope.$broadcast('trafficPortal::exit');
-                    if ($state.current.name == 'trafficPortal.public.login') {
-                        messageModel.setMessages(result.alerts, false);
-                    } else {
-                        messageModel.setMessages(result.alerts, true);
-                        $state.go('trafficPortal.public.login');
-                    }
-                    return result;
+        httpService.post(ENV.api['root'] + 'user/logout').then(
+            function(result) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/AuthService.js]: keep getting result is undefined on logout

File: traffic_portal/app/src/common/api/DeliveryServiceService.js [hunk 9]
```diff
@@ -17,168 +17,184 @@
...
-            .then(
-                function() {
-                    messageModel.setMessages([ { level: 'success', text: 'Steering target deleted' } ], true);
-                    locationUtils.navigateToPath('/delivery-services/' + dsId + '/targets');
-                },
-                function(fault) {
-                    messageModel.setMessages(fault.data.alerts, true);
-                }
-            );
+        return $http.delete(ENV.api['root'] + 'steering/', dsId + '/targets/' + targetId).then(
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/DeliveryServiceService.js]: deleting a ds target is not working

File: traffic_portal/app/src/common/api/DeliveryServiceService.js [hunk 10]
```diff
@@ -17,168 +17,184 @@
...
-            .then(
-                function() {
-                    messageModel.setMessages([ { level: 'success', text: 'Delivery service and server were unlinked.' } ], false);
-                },
-                function(fault) {
-                    messageModel.setMessages(fault.data.alerts, true);
-                }
-            );
+        return httpService.delete(ENV.api['root'] + 'deliveryservice_server/' + dsId + '/' + serverId).then(
+            function(result) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/DeliveryServiceService.js]: shared-libs.js?built=1558641564542:66530 TypeError: Cannot read property 'data' of undefined
    at DeliveryServiceService.js:163

File: traffic_portal/app/src/common/api/DeliveryServiceSslKeysService.js [hunk 11]
```diff
@@ -17,10 +17,10 @@
  * under the License.
  */
 
-var DeliveryServiceSslKeysService = function($http, $q, locationUtils, messageModel, ENV) {
+var DeliveryServiceSslKeysService = function($http, locationUtils, messageModel, ENV) {
 	this.generateSslKeys = function(deliveryService, sslKeys, generateSslKeyForm) {
 		if (sslKeys.hasOwnProperty('version')){
-			generateSslKeyForm.version = parseInt(sslKeys.version) + 1;
+			generateSslKeyForm.version = parseInt(sslKeys.version, 10) + 1;
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/DeliveryServiceSslKeysService.js]: seems unrelated to restangular

File: traffic_portal/app/src/common/api/DeliveryServiceUriSigningKeysService.js [hunk 12]
```diff
@@ -17,17 +17,31 @@
  * under the License.
  */
 
-var DeliveryServiceUriSigningKeysService = function(Restangular) {
+var DeliveryServiceUriSigningKeysService = function($http, ENV) {
 
 	this.getKeys = function(id) {
-		return Restangular.one("deliveryservices", id).one("urisignkeys").get();
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/DeliveryServiceUriSigningKeysService.js]: TypeError: keys.plain is not a function
    at new DeliveryServiceUriSigningKeysController (DeliveryServiceUriSigningKeysController.js:23)

File: traffic_portal/app/src/common/api/DeliveryServiceSslKeysService.js (hunk 11 above)
Comment (ocket8888) [reply traffic_portal/app/src/common/api/DeliveryServiceSslKeysService.js]: It is, but [using `parseInt` without passing an explicit radix is dangerous](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Octal_interpretations_with_no_radix) so I wanted to fix it asap.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3728/
Test PASSed.

File: traffic_portal/app/src/common/api/CDNService.js [hunk 13]
```diff
@@ -17,252 +17,207 @@
...
-                    } else {
-                        response = _.filter(result.data.response, function(cdn) {
-                            return cdn.name != 'ALL';
-                        });
-                    }
-                    request.resolve(response);
-                },
-                function(fault) {
-                    request.reject();
+        return $http.get(ENV.api['root'] + 'cdns').then(
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/CDNService.js]: so i'm seeing some weird errors and i think it's because of the way the angular-ui-router's "resolves" work. for example, if you try to go here (when you are unauthorized/logged in) - https://localhost:8442/#!/cdns - the way I built TP with the help of angular-ui-router is it works its way down the resolve chain.

it first tries to resolve these resolves:

https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/modules/private/index.js#L45

specifically, it first tries to fetch "current user" and if that fails, the next resolve should NOT even be attempted:

https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/modules/private/cdns/list/index.js#L29

but with your changes (removing $q.defer()), it's not stopping after the first resolve failure...instead it just keeps going down the resolve chain. maybe that's not a problem...but maybe it is. will need to do some more testing. 

but i do think this format works and it has no restangular (your goal of this PR)

`    this.getCDNs = function(all) {
        var request = $q.defer();
        $http.get(ENV.api['root'] + "cdns")
            .then(
                function(result) {
                    var response;
                    if (all) { // there is a CDN called "ALL" that is not really a CDN but you might want it...
                        response = result.data.response;
                    } else {
                        response = _.filter(result.data.response, function(cdn) {
                            return cdn.name != 'ALL';
                        });
                    }
                    request.resolve(response);
                },
                function(fault) {
                    request.reject(fault);
                }
            );

        return request.promise;
    };
`

Comment (mitchell852) [reply traffic_portal/app/src/common/api/CDNService.js]: UserService.js#getCurrentUser() needs to be implemented like this (or something with similar behavior) so if it fails, the remaining resolves are not attempted at all:

```
    this.getCurrentUser = function() {
        const deferred = $q.defer();
        $http.get(ENV.api['root'] + "user/current")
            .then(
                function(result) {
                    userModel.setUser(result.data.response);
                    deferred.resolve(result.data.response);
                },
                function(fault) {
                    deferred.reject(fault);
                }
            );
        return deferred.promise;
    };
```

File: traffic_portal/app/src/common/api/UserService.js [hunk 14]
```diff
@@ -17,143 +17,148 @@
  * under the License.
  */
 
-var UserService = function(Restangular, $http, $location, $q, authService, httpService, locationUtils, userModel, messageModel, ENV) {
+var UserService = function($http, locationUtils, userModel, messageModel, ENV) {
 
-    var service = this;
+    const service = this;
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/UserService.js]: you can get rid of this. it's not used anywhere.

File: traffic_portal/app/src/common/api/CDNService.js (hunk 13 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/api/CDNService.js]: ^^ you can disregard all of that. see the comment attached to UserService.js

File: traffic_portal/app/src/common/api/UserService.js [hunk 15]
```diff
@@ -17,143 +17,148 @@
...
 
     this.getCurrentUser = function() {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/UserService.js]: getCurrentUser() needs to be implemented like this (or something with similar behavior) so if it fails, the remaining resolves are not attempted at all:

```
    this.getCurrentUser = function() {
        return $http.get(ENV.api['root'] + "user/current").then(
            function(result) {
                userModel.setUser(result.data.response);
                return result.data.response;
            },
            function(err) {
                console.error(err);
                return err;
            }
        );
    };
```

Comment (ocket8888) [reply traffic_portal/app/src/common/api/UserService.js]: TBH I'd consider asynchronous calls being done synchronously much weirder. But the problem is easily fixed - the interceptor will catch it immediately if you throw the error instead of returning it. Either way the promise is "rejected", but it seems like throwing resolves a call stack faster or something.

Regardless, I've got it no longer making other API calls on a page if it hits a 401. I had to decrease the `$timeout` on the redirect, otherwise the messages wouldn't show up. Not sure what that's about.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3734/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3735/
Test PASSed.

File: traffic_portal/app/src/app.js [hunk 16]
```diff
@@ -464,7 +464,7 @@ trafficPortal.factory('authInterceptor', function ($rootScope, $q, $window, $loc
                         messageModel.setMessages(alerts, true);
                         // forward the to the login page with ?redirect=page/they/were/trying/to/reach
                         $location.url('/login').search({ redirect: encodeURIComponent(url) });
-                    }, 200);
+                    }, 100);
```
Comment (mitchell852) [inline traffic_portal/app/src/app.js]: this whole timeout thing is weird. maybe it can be removed. i'll test it out. can't remember why i put it in here.

File: traffic_portal/app/src/common/api/UserService.js (hunk 15 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/api/UserService.js]: resolves aren't synchronous per se. they are a way to ensure that a state (or a nested state) does not resolve until certain dependencies are fetched. in this case i never want the "private" state (or any state under that) to resolve until the currentUser dependency resolves. you are making a lot of fundamental / architectural changes to this PR that is making me very hesitant  to merge it without a LOT of testing.

**Comment by mitchell852** [comment]
the more I think about it, I think this PR is just way too big / risky. it requires a lot of positive and negative testing to ensure it does not change/break functionality. imo you should tackle one "service" at a time. i.e. remove the use of restangular from cdnservice.js. and move down the list of "services" with a seperate PR until nothing uses restangular and the dependency can be removed altogether. otherwise, the risk is much too high given that TP doesn't have comprehensive regression tests in place.

File: traffic_portal/app/src/app.js (hunk 16 above)
Comment (ocket8888) [reply traffic_portal/app/src/app.js]: When I remove it it also doesn't show up messages

**Comment by ocket8888** [comment]
Alright man, you asked for it

I'm gonna leave this open as a draft - I'll rebase once the others are all merged and this will be the one that actually removes restangular entirely.

**Comment by mitchell852** [comment]
@ocket8888 to rebase

File: traffic_portal/app/src/common/api/ProfileParameterService.js [hunk 17]
```diff
@@ -35,6 +35,7 @@ var ProfileParameterService = function($http, messageModel, ENV) {
 	this.linkProfileParameters = function(profile, params) {
 		return $http.post(ENV.api['root'] + 'profileparameter', { profileId: profile.id, paramIds: params, replace: true }).then(
 			function(result) {
+				messageModel.setMessages([ { level: 'success', text: 'Parameters linked to profile' } ], false);
```
Comment (mitchell852) [inline traffic_portal/app/src/common/api/ProfileParameterService.js]: i dont think this is supposed to be in here as every call to linkProfileParameters takes care of the messaging.

plus, obviously not restangular related

Comment (ocket8888) [reply traffic_portal/app/src/common/api/ProfileParameterService.js]: I actually couldn't remember why I did that. Thanks for catching that.

Comment (mitchell852) [reply traffic_portal/app/src/common/api/ProfileParameterService.js]: yep, no worries. remove that and i'll merge this.
