### PR TITLE
Ensure server_capability can only be assigned to edges or mids

### LINKED ISSUE #4038: TP, TO: server capabilities are allowed to be assigned to any servers which are not mid or edge
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Server Capabilities is assignable to any server (like origin)
## Expected / new behavior:

Server Capabilities should be assignable only to edge or mid type servers 
## Minimal reproduction of the problem with instructions:

create server capabilities 
assign it to any server of type other than mid or edge

### PR DESCRIPTION
**Pull request by mhoppa**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4038 

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops
- Traffic Portal

## What is the best way to verify this PR?

Build traffic ops with PR and then attempt to assign a server_capability to a non EDGE/MID server. It should be blocked.

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR does not include an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### Demo

Oct-31-2019 10-26-06

### CODE REVIEW

**Comment by mhoppa** [comment]
need to do TP part here as well

**Comment by ocket8888** [comment]
Lmk when the "TP part" is done and I'll take off the WIP label.

File: traffic_ops/traffic_ops_golang/server/servers_server_capability.go [hunk 1]
```diff
@@ -165,3 +186,15 @@ server) VALUES (
...
+
+func scCheckServerTypeQuery() string {
+	return `
+SELECT EXISTS (
+	SELECT s.id
+	FROM server s
+	JOIN type t ON s.type = t.id
+	WHERE s.id = $1
+	AND t.use_in_table = 'server'
+	AND (t.name LIKE '%MID%' OR t.name LIKE '%EDGE%')
```
Comment (mitchell852) [inline traffic_ops/traffic_ops_golang/server/servers_server_capability.go]: I wonder if it should be:

`AND (t.name LIKE 'MID%' OR t.name LIKE 'EDGE%')`

If you look around the code base, I'm pretty sure we only consider EDGE* as an edge and not FOO_EDGE for example...

Comment (mitchell852) [reply traffic_ops/traffic_ops_golang/server/servers_server_capability.go]: we must not extend our system hacks! ;)

Comment (mhoppa) [reply traffic_ops/traffic_ops_golang/server/servers_server_capability.go]: will change :) good catch

Comment (rob05c) [reply traffic_ops/traffic_ops_golang/server/servers_server_capability.go]: I agree with @mitchell852, AFAIK most or all existing things check for the prefix. 

Checking anywhere would make this strictly more lenient than most other checks, which sounds nice, but if someone relies on it, then stuff elsewhere might not work that they don't expect.

Better to require a prefix everywhere I think.

Comment (rob05c) [reply traffic_ops/traffic_ops_golang/server/servers_server_capability.go]: Erm, sorry, didn't refresh to see the new comments before I posted that :|

**Comment by mhoppa** [comment]
@ocket8888 TP is done, @mitchell852 let me know if you were thinking something different then what I implemented included short demo video in PR `Additional Information` section

File: traffic_portal/app/src/common/modules/form/server/form.server.tpl.html [hunk 2]
```diff
@@ -34,8 +34,8 @@
                     <li><a ng-click="confirmStatusUpdate()">Update Status</a></li>
                     <li ng-show="isCache(server) && !server.updPending"><a ng-click="queueServerUpdates(server)">Queue Server Updates</a></li>
                     <li ng-show="isCache(server) && server.updPending"><a ng-click="clearServerUpdates(server)">Clear Server Updates</a></li>
-                    <li ng-show="isEdge(server) || isCache(server)" class="divider"></li>
-                    <li name="viewCapabilitiesMenuItem"><a ng-click="viewCapabilities()">Manage Capabilities</a></li>
+                    <li ng-show="isCache(server)" class="divider"></li>
+                    <li ng-show="isCache(server)" name="viewCapabilitiesMenuItem"><a ng-click="viewCapabilities()">Manage Capabilities</a></li>
                     <li><a ng-click="viewDeliveryServices()">Manage Delivery Services</a></li>
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/server/form.server.tpl.html]: I guess the `viewDeliveryServices` menu item should have had the `isEdge(server)` check because only edges can be assigned to delivery services.

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/server/form.server.tpl.html]: it's all very confusing :p

File: traffic_portal/app/src/common/modules/table/serverServerCapabilities/table.serverServerCapabilities.tpl.html [hunk 3]
```diff
@@ -25,7 +25,7 @@
             <li class="active">Capabilities</li>
         </ol>
         <div class="pull-right">
-            <button type="button" name="addCapabilityBtn" class="btn btn-primary" title="Add Server Capability" ng-click="addServerCapability()"><i class="fa fa-plus"></i></button>
+            <button ng-show="isCache(server)" type="button" name="addCapabilityBtn" class="btn btn-primary" title="Add Server Capability" ng-click="addServerCapability()"><i class="fa fa-plus"></i></button>
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/table/serverServerCapabilities/table.serverServerCapabilities.tpl.html]: i think ng-if would be fine as the server type will not be changing in this view

**Comment by mitchell852** [comment]
by the way, nice video in your PR description!
