### PR TITLE
Use `t3c` for cache configuration in CDN in a Box

### LINKED ISSUE #5831: CDN in a Box does not use an ORT implementation provided by the Traffic Ops ORT RPM
## I'm submitting a ...

-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  CDN in a Box

## Current behavior:

CDN in a Box runs the Python implementation of ORT on its caches.

## New behavior:

CDN in a Box should run `t3c` (the Go implementation of ORT) version of ORT on its caches. `t3c` will be the default ORT implementation when #5781 is merged.

## Minimal reproduction of the problem with instructions:

https://github.com/apache/trafficcontrol/blob/39ff1ada3180c7f2ab256d39865e4a41b74d988b/infrastructure/cdn-in-a-box/edge/init.d/99-run.sh#L78
https://github.com/apache/trafficcontrol/blob/39ff1ada3180c7f2ab256d39865e4a41b74d988b/infrastructure/cdn-in-a-box/mid/init.d/99-run.sh#L75
https://github.com/apache/trafficcontrol/blob/39ff1ada3180c7f2ab256d39865e4a41b74d988b/infrastructure/cdn-in-a-box/ort/traffic_ops_ort.crontab#L17

## Anything else:

The main challenge to overcome for #5831 is that `t3c` (as well as `traffic_ops_ort.pl`) relies on systemd in order to start and check the status of `trafficserver`. Systemd is relatively straightforward to use in a CentOS 8 Docker container, but not in CentOS 7. Example of an error in a CentOS 7 docker container without systemd support:

```go
ERROR: t3c.go:149: 2021-05-11T04:25:36.595138434Z: Error verifying system services: Unable to enable service trafficserver: Error executing '/bin/systemctl': Failed to get D-Bus connection: No such file or directory
```

Ideally, we wouldn't need to use systemd in Docker containers (see: #5829). Without a t3c flag to avoid systemd, though, the `edge`, `mid-01`, and `mid-02` services would need to [run systemd](https://github.com/docker-library/docs/tree/master/centos#systemd-integration) when built for either CentOS 8 or CentOS 7.

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5831 by using `t3c` to configure caching proxy servers in CDN in a Box (24e8c808fb).
- Moves the Python ORT implementation to the `/experimental` directory (01d6e52d17)
- Makes the systemctl shim used by the ORT Integration Tests start `trafficserver` (bf35702165) and adds it to CDN in a Box (cfd3bf3dd8)
- Adds a debugging configuration for the `t3c` components in CDN in a Box (f9fdfbcfdc)

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- ~Traffic Ops ORT (only changes `systemctl` shim used by tests)~ Now copies the `systemctl` shim and modifies only the copy
- CI tests (triggers the *Documentation Build* workflow when the Python ORT implementation is modified)

## What is the best way to verify this PR?

- Test the CDN in a Box Delivery Services
- Try to debug a `t3c` component, set a breakpoint, ensure it hits that breakpoint

## The following criteria are ALL met by this PR

- [x] CDN in a Box is a test, no further tests necessary
- [x] This PR includes documentation
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by ocket8888 — COMMENTED** [review]
Moving ORT.py like this breaks the autodoc for it, causing a bunch of broken links. See the docs build action output for details.

**Comment by zrhoffman** [comment]
> Moving ORT.py like this breaks the autodoc for it, causing a bunch of broken links. See the docs build action output for details.

Fixed `ortPath` in 04c5e66964.

File: infrastructure/cdn-in-a-box/cache/Dockerfile [hunk 1]
```diff
@@ -51,109 +54,84 @@ RUN dnf -y install epel-release && \
...
+COPY infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh /opt/init.d/
+
+FROM common-cache-config-layers AS edge
 COPY infrastructure/cdn-in-a-box/edge/init.d/ /opt/init.d/
+
+FROM edge AS edge-debug
+COPY --from=get-delve /root/go/bin /usr/bin
+COPY infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh /opt/init.d/
+
+FROM edge
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/Dockerfile:137]: what does this hanging `FROM` line do?

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+for t3c_tool in $(compgen -c t3c | sort | uniq); do
+	(path="$(type -p "$t3c_tool")"
+	cd "$(dirname "$path")"
+	dlv_script="${t3c_tool}.debug"
+	actual_binary="${t3c_tool}.actual"
+	touch "$dlv_script"
+	chmod +x "$dlv_script"
+	<<-DLV_SCRIPT cat > "$dlv_script"
+	#!/usr/bin/env bash
+	$(type maybe_debug | tail -n+2)
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:51]: Do you need to print the source of the function?

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+	exec "${command[@]}" "$@"
+}
+
+hostname="$(hostname --short)"
+for t3c_tool in $(compgen -c t3c | sort | uniq); do
+	(path="$(type -p "$t3c_tool")"
+	cd "$(dirname "$path")"
+	dlv_script="${t3c_tool}.debug"
+	actual_binary="${t3c_tool}.actual"
+	touch "$dlv_script"
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:47]: touch is unnecessary if you move the `chmod` below the `cat`.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+	chmod +x "$dlv_script"
+	<<-DLV_SCRIPT cat > "$dlv_script"
+	#!/usr/bin/env bash
+	$(type maybe_debug | tail -n+2)
+	maybe_debug "${hostname}" "${DEBUG_PORT}" "${actual_binary}" "\$@"
+	DLV_SCRIPT
+	mv "$t3c_tool" "$actual_binary"
+	ln -s "$dlv_script" "$t3c_tool"
+	)
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:56]: why wrap in <kbd>(</kbd>/<kbd>)</kbd>?

File: infrastructure/cdn-in-a-box/cache/run.sh [hunk 5]
```diff
@@ -17,14 +17,78 @@
...
+set-dns.sh
+insert-self-into-dns.sh
+
+source /to-access.sh
+
+# Wait on SSL certificate generation
+until [[ -f "$X509_CA_ENV_FILE" ]]
+do
+  echo "Waiting on Shared SSL certificate generation"
+  sleep 3
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/run.sh:33]: Inconsistent indentation using 2 spaces - existing code in this file used 4 spaces. I wouldn't object to switching to tabs (tabs > 4-space > 2-space >>> 8-space), but it should be done consistently and globally through the file

File: infrastructure/cdn-in-a-box/cache/run.sh [hunk 6]
```diff
@@ -17,14 +17,78 @@
...
+done
+
+# Source the CIAB-CA shared SSL environment
+until [[ -n "$X509_GENERATION_COMPLETE" ]]
+do
+  echo "Waiting on X509 vars to be defined"
+  sleep 1
+  source "$X509_CA_ENV_FILE"
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/run.sh:41]: Inconsistent indentation using 2 spaces - existing code in this file used 4 spaces. I wouldn't object to switching to tabs, but it should be done consistently and globally through the file

File: infrastructure/cdn-in-a-box/cache/run.sh [hunk 7]
```diff
@@ -17,14 +17,78 @@
...
+done
+
+# Trust the CIAB-CA at the System level
+cp "$X509_CA_CERT_FULL_CHAIN_FILE" /etc/pki/ca-trust/source/anchors
+update-ca-trust extract
+
+while ! to-ping 2>/dev/null; do
+	echo "waiting for Traffic Ops"
+	sleep 5
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/run.sh:50]: Inconsistent indentation using tabs - existing code in this file used 4 spaces. I wouldn't object to switching to tabs, but it should be done consistently and globally through the file

File: infrastructure/cdn-in-a-box/cache/run.sh [hunk 8]
```diff
@@ -17,14 +17,78 @@
...
 for f in /opt/init.d/*; do
     echo "$f"
-    $f
+    source "$f"
+done
+
+# Wait for SSL keys to exist
+until [[ $(to-get "api/2.0/cdns/name/$CDN_NAME/sslkeys" | jq '.response | length') -gt 0 ]]; do
+	echo 'waiting for SSL keys to exist'
+	sleep 3
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/run.sh:72]: Inconsistent indentation using tabs - existing code in this file used 4 spaces. I wouldn't object to switching to tabs, but it should be done consistently and globally through the file

File: infrastructure/cdn-in-a-box/cache/run.sh [hunk 9]
```diff
@@ -17,14 +17,78 @@
...
+# If /tmp/trafficcontrol-cache-config does not already exist when running t3c-apply, t3c-apply will create it and fail silently
+mkdir /tmp/trafficcontrol-cache-config
+
+# hostname is already defined in /etc/init.d/99-run.sh
+hostname="${hostname//-/_}" # replace - with _
+hostname="${hostname^^}" # uppercase
+debug_variable_name="T3C_DEBUG_COMPONENT_${hostname}"
+debug_binary="${!debug_variable_name}"
+if ! type -p "$debug_binary"; then
+	t3c apply --run-mode=badass --traffic-ops-url="$TO_URL" --traffic-ops-user="$TO_USER" --traffic-ops-password="$TO_PASSWORD" --git=yes --dispersion=0 --log-location-error=stdout --log-location-warning=stdout --log-location-info=stdout all || { echo "Failed"; }
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/run.sh:84]: Inconsistent indentation using tabs - existing code in this file used 4 spaces. I wouldn't object to switching to tabs, but it should be done consistently and globally through the file

File: infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile [hunk 10]
```diff
@@ -20,7 +20,7 @@
 ############################################################
 
 ARG RHEL_VERSION=8
-FROM centos:${RHEL_VERSION} as trafficmonitor
+FROM centos:${RHEL_VERSION} as trafficmonitor-dependencies
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile:23]: I think these types of changes are best left to a separate body of work, since they don't relate to _"Us[ing] `t3c` for cache configuration in CDN-in-a-Box"_

File: infrastructure/cdn-in-a-box/cache/uname [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+		releasever="$(rpm -q --qf '%{version}' -f $redhat_release)"
+		releasever="${releasever%%.*}"
+	else
+		releasever=${default_version}
+	fi;
+
+	echo "el${releasever}"
+}
+rhel_version="$(get_rhel_version)"
+kernel_version="3.10.0-862.11.6.${rhel_version}"
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/uname:33]: Do we need to spoof the kernel version? Things that need to interact with the kernel will actually be interacting with the host kernel, won't they?

File: infrastructure/cdn-in-a-box/cache/uname [hunk 12]
```diff
@@ -0,0 +1,35 @@
...
+architecture=x86_64
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/cache/uname:34]: Do we need to spoof the architecture? All running code will, in fact, be using the host's architecture, not necessarily `x86_64`.

File: infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json [hunk 13]
```diff
@@ -15,7 +15,7 @@
 			"configFile": "records.config",
 			"name": "CONFIG proxy.config.config_dir",
 			"secure": false,
-			"value": "STRING /etc/trafficserver"
+			"value": "STRING /opt/trafficserver/etc/trafficserver"
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json:18]: Does `t3c` not support installation to `/`?

File: infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json [hunk 14]
```diff
@@ -255,118 +255,176 @@
...
+			"name": "CONFIG proxy.config.ssl.server.private_key.path",
+			"secure": false,
+			"value": "STRING /opt/trafficserver/etc/trafficserver/ssl"
+		},
+		{
+			"configFile": "records.config",
+			"name": "CONFIG proxy.config.ssl.server.ticket_key.filename",
+			"secure": false,
+			"value": "STRING NULL"
+		},
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json:313]: Do these need to be added to the edge's profile as well?

**Review by ocket8888 — COMMENTED** [review]
Not that this has anything to do with whether or not I'd approve this PR, but do you have any idea if this made the resulting cache server images bigger or smaller? And if so, by how much?

File: infrastructure/cdn-in-a-box/cache/Dockerfile (hunk 1 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/Dockerfile:138]: Makes it so that the image builds using the `edge` target by default instead of the `edge-debug` target if no target is specified. Added a comment explaining why in 5c3def0336.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 3 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:47]: Moved `chmod` below the `cat` in 17b12aeae8.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 4 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:55]: To avoid having to `cd` back out

File: infrastructure/cdn-in-a-box/cache/run.sh (hunk 6 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/run.sh]: Spacing made consistent in 4d2c0da326.

File: infrastructure/cdn-in-a-box/cache/run.sh (hunk 8 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/run.sh:72]: Spacing made consistent in 4d2c0da326.

File: infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile (hunk 10 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile:23]: While it's true that  it doesn't *directly* relate to using `t3c` for cache configuration CDN in a Box, it is directly related to one of the changes that this PR involves. 942b4396de reorganizes the cache Dockerfile to avoid unnecessarily rebuilding the layer that installs `dlv`, and if that optimization was applied only to the cache Dockerfile, then the debugging stages across our CiaB Dockerfiles would be inconsistent.

So I'd say that including the changes to non-cache Dockerfiles in 942b4396de leads to less entropy over our CiaB Dockerfiles, not less. For the sake of consistency, I'd be tempted to not even apply that optimization to our cache Dockerfile in this PR if not applying it to the other ones in this PR.

File: infrastructure/cdn-in-a-box/cache/uname (hunk 11 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/uname:33]: Not for `t3c`, we don't. In `traffic_ops_ort.pl`, we did:

https://github.com/apache/trafficcontrol/blob/a289d9ce008df420b41f4b3ac488e094860b10f0/traffic_ops_ort/traffic_ops_ort.pl#L343-L348

Removed the `uname` shim in 549aa07ce5.

**Comment by zrhoffman** [comment]
Rebased onto master to get `t3c-check` from #5281.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 4 above)
Comment (ocket8888) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:55]: Is it going to mess with anything if it's indented?
```bash
(
    like;
    this;
)
```

File: infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json (hunk 14 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json:313]: Nah, they were already there. With these added, the only configuration difference between the Edge and Mid profiles is that Edge is a reverse proxy:

```diff
--- 010-ATS_EDGE_TIER_CACHE.json	2021-05-18 12:21:57.791484259 -0600
+++ 020-ATS_MID_TIER_CACHE.json	2021-05-18 12:21:57.791484259 -0600
@@ -1,7 +1,7 @@
 {
 	"cdnName": "$CDN_NAME",
-	"description": "Edge Cache - Apache Traffic Server",
-	"name": "EDGE_TIER_ATS_CACHE",
+	"description": "Mid Cache - Apache Traffic Server",
+	"name": "MID_TIER_ATS_CACHE",
 	"routingDisabled": false,
 	"type": "ATS_PROFILE",
 	"params": [
@@ -93,7 +93,7 @@
 			"configFile": "records.config",
 			"name": "CONFIG proxy.config.reverse_proxy.enabled",
 			"secure": false,
-			"value": "INT 1"
+			"value": "INT 0"
 		},
 		{
 			"configFile": "records.config",
```

File: infrastructure/cdn-in-a-box/cache/uname (hunk 12 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/uname]: You're right, no need to spoof. Still removed the `uname` shim in 549aa07ce.

File: infrastructure/cdn-in-a-box/cache/run.sh (hunk 9 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/run.sh:84]: Spacing made consistent in 4d2c0da326.

File: infrastructure/cdn-in-a-box/cache/run.sh (hunk 7 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/run.sh:50]: Spacing made consistent in 4d2c0da326.

File: infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile (hunk 10 above)
Comment (ocket8888) [reply infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile:23]: Yes I think ideally those optimizations would be made at a later date, but they're small enough that we can probably just squeeze them in here. Alternatively, if you have the time and it's not annoying, you could make the optimizations to the other services and submit that as a separate PR as a prerequisite to this one. I can promise to merge that today, if you so choose and once its checks pass.

Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile]: Opened #5866 for this optimization in the other Dockerfiles, removed it from this PR in 062205cfc4.

File: infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json (hunk 13 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json:18]: It does, but CDN in a Box also should use a newer ATS version (currently using ATS 7.1.4), and building `./pkg -vo ats` yields an ATS RPM that uses `/opt/trafficserver` as the TS root directory, so using `/opt/trafficserver` seems inevitable.

File: infrastructure/cdn-in-a-box/cache/Dockerfile [hunk 15]
```diff
@@ -51,109 +54,84 @@ RUN dnf -y install epel-release && \
...
-ADD infrastructure/cdn-in-a-box/ort /opt/ort/
-ADD traffic_control/clients/python /opt/Apache-TrafficControl/
-
-RUN touch /var/log/ort.log && \
-	pip3 install ./Apache-TrafficControl && \
-	pip3 install ./ort && \
-	cp ort/traffic_ops_ort.crontab /etc/cron.d/traffic_ops_ort-cron-template && \
-	cp ort/traffic_ops_ort.logrotate /etc/logrotate.d/ort
+ADD infrastructure/cdn-in-a-box/cache/traffic_ops_ort.crontab /etc/cron.d/traffic_ops_ort-cron-template
+ADD infrastructure/cdn-in-a-box/cache/traffic_ops_ort.logrotate /etc/logrotate.d/ort
```
[the remark this answers is not in the document]
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/Dockerfile]: Using `COPY` for local files in 41cb537aba.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 2 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:49]: Yes, otherwise it wouldn't be defined within `DLV_SCRIPT`.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 4 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:55]: That would work, or it could be grouped with the loop:

```shell
for t3c_tool in $(compgen -c t3c | sort | uniq); do (
	path="$(type -p "$t3c_tool")"
	# [...]
	ln -s "$dlv_script" "$t3c_tool"
) done
```

Thoughts?

File: cache-config/testing/docker/ort_test/systemctl.sh [hunk 16]
```diff
@@ -19,35 +19,33 @@
...
-  stop)
-    ;;
+case "$COMMAND" in
+  restart) command_found=true;;
+  start) command_found=true;;
+  status) command_found=true;;
+  stop) command_found=true;;
 esac
 
+if [[ "$command_found" == true ]]; then
```
[the remark this answers is not in the document]
Comment (zrhoffman) [reply cache-config/testing/docker/ort_test/systemctl.sh]: Exiting with an error if the command wasn't found in 749d9dee14.

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 4 above)
Comment (ocket8888) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:55]: I think the latter looks better, but could be confusing to people who just think you're trying to delimit the function contents in a manner similar to many programming languages. The former is more clearly defining scope

File: infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json (hunk 13 above)
Comment (ocket8888) [reply infrastructure/cdn-in-a-box/traffic_ops_data/profiles/020-ATS_MID_TIER_CACHE.json:18]: that's unfortunate

File: infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh (hunk 4 above)
Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/cache/init-debug-scripts.sh:56]: Indenting in c6bfe3da98

File: traffic_ops_ort/traffic_ops_ort.pl [hunk 17]
```diff
@@ -0,0 +1,2662 @@
+#!/usr/bin/perl
```
Comment (ocket8888) [inline traffic_ops_ort/traffic_ops_ort.pl:1]: Looks like you're necromancing, which while not strictly illegal has been banned guild-wide in all nine provinces by Arch Mage Hannibal Traven since 3E 431.

Best practice is to not practice necromancy.

Comment (zrhoffman) [reply traffic_ops_ort/traffic_ops_ort.pl]: Removed in 210a4027d3. There's a cache configs bug I have yet to report and I used `traffic_ops_ort.pl` in CDN in a Box (which works with the `uname` shim still there) to rule it being a regression from `traffic_ops_ort.pl` to `t3c`.

**Comment by zrhoffman** [comment]
Rebased to fix a merge conflict in CHANGELOG.md

**Comment by zrhoffman** [comment]
Updated the t3c integration tests GHA workflow to run when anything in `/cache-config/testing` is modified, since this PR updates `/cache-config/testing/docker/ort_test/systemctl.sh`. The updates to `systemctl.sh` cause the t3c integration tests to fail because `tc-fixtures.json` does not include a valid ATS version:

https://github.com/apache/trafficcontrol/blob/04b6bb59188be169f22ea575b1e37d3dd67a6fe8/cache-config/testing/ort-tests/tc-fixtures.json#L1759-L1765

GH issue incoming.

**Comment by zrhoffman** [comment]
The t3c integration tests don't seem to be built around Traffic Server running. Copied the `systemctl` shim into CDN in a Box and reverted the one used by the `t3c` integration tests in 65240c03a0.

File: infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile [hunk 18]
```diff
@@ -64,7 +63,7 @@ CMD /run.sh
 HEALTHCHECK --interval=10s --timeout=1s \
     CMD bash -c 'source /to-access.sh && [[ "$(curl -s http://trafficmonitor.infra.ciab.test/api/traffic-ops-uri)" == "$TO_URL" ]]'
 
-FROM trafficmonitor-dependencies as get-delve
+FROM trafficmonitor as get-delve
```
Comment (ocket8888) [inline infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile:66]: Seems like this is reverting the changes from #5866 

Same thing in Enroller/Ops etc.

Comment (zrhoffman) [reply infrastructure/cdn-in-a-box/traffic_monitor/Dockerfile]: Rebased and took out the commits that modify those files.

**Comment by jrushford** [comment]
> The t3c integration tests don't seem to be built around Traffic Server running. Copied the `systemctl` shim into CDN in a Box and reverted the one used by the `t3c` integration tests in [65240c0](https://github.com/apache/trafficcontrol/commit/65240c03a000d039807ca93eb682c73e5825de34).

@zrhoffman Until recently the t3c integration tests didn't really need Trafficserver running however, that will be changing.  In order to completely test t3c-apply, we will actually need to start Trafficserver.  I have a ticket, [CDN-13118](https://ccp.sys.comcast.net/browse/CDN-13118) to fix this.

**Comment by zrhoffman** [comment]
Awesome, can't wait.

**Comment by jrushford** [comment]
> Awesome, can't wait.

I'll work on it soon.  currently ATS won't start on the ort_test container and it looks like some additional parameters need to be added to tc-fixtures.json which ultimately has them added to the trafficserver records.config

**Comment by jrushford** [comment]
> Updated the t3c integration tests GHA workflow to run when anything in `/cache-config/testing` is modified, since this PR updates `/cache-config/testing/docker/ort_test/systemctl.sh`. The updates to `systemctl.sh` cause the t3c integration tests to fail because `tc-fixtures.json` does not include a valid ATS version:
> 
> https://github.com/apache/trafficcontrol/blob/04b6bb59188be169f22ea575b1e37d3dd67a6fe8/cache-config/testing/ort-tests/tc-fixtures.json#L1759-L1765
> 
> GH issue incoming. See [#5853 (comment)](https://github.com/apache/trafficcontrol/pull/5853#issuecomment-845263483)

Rob has a PR in to fix this issue.  the value "*" will be replaced with the original value "CHANGEME".  Somehow this was changed recently.  Anyway, after the GHA workflow builds the trafficserver RPM, "CHANGEME" is modified with a sed script to reflect the correct ATS version.

**Comment by zrhoffman** [comment]
> @zrhoffman Rob has a PR in to fix this issue, I think it's #5875. the value "*" will be replaced with the original value "CHANGEME". Somehow this was changed recently. Anyway, after the GHA workflow builds the trafficserver RPM, "CHANGEME" is modified with a sed script to reflect the correct ATS version.

@jrushford Related to that, I opened PR #5876 to use `jq` to manipulate the JSON to set the ATS RPM version in `jc-fixtures.json`, which carries the benefit not needing the placeholder text to be there in order to update it.

**Review by ocket8888 — APPROVED** [review]
My concerns were all addressed

**Review by jrushford — APPROVED** [review]
@zrhoffman looks good.  I like the jq change, your not subject to looking for a particular string such as 'CHANGEME'.  Should work no matter what is in the value field.
