### PR TITLE
'fixed' grafana scripted dashboard to use exact hostname instead of regular expression match

### LINKED ISSUE #4541: traffic_ops_server.js searches based on which= and can find data for multiple servers
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
The traffic_ops_server.js script pulls data to display using which=hostname.  However with a hostname "edge-01" and another "edge-010", using the script with "edge-01" finds data from both servers, and shows a very odd graph. If I fix the issue by using "edge-01.infra then the mem/cpu/netstat data is fine, but the count and bandwidth data are then not displayed.

## Expected / new behavior:
The script should discern each host, and not combine data from 2 hosts. 

## Minimal reproduction of the problem with instructions:
See the output of the script with a `which` parameter that is contained in multiple cache server names.

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4541

I _think_ this fixes the issue where it would select multiple servers when "which" is specified with something that is contained in the hostnames of multiple servers. I've tested it in CDN-in-a-Box and everything appeared to be working, but for some reason about half of the graphs are trying to source their data from "telegraf", which looks like some kind of hold-over from when this was a Comcast internal project.

## Which Traffic Control components are affected by this PR?
- Traffic Stats

## What is the best way to verify this PR?
Open the scripted dashboard with a "which" value that is contained in multiple cache server hostnames. Verify that only the cache server with a hostname exactly matching `which` is selected. Unless there are multiple with the same hostname, which is totally allowed and can happen. Idk what the dashboard is supposed to do in that case.

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] Documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: traffic_stats/grafana/traffic_ops_server.js [hunk 1]
```diff
@@ -13,1368 +13,1359 @@
...
+    from: "now-24h",
+    to: "now"
+  }
 };
 
-var which = 'argName';
+let which = 'argName';
 
-if(!_.isUndefined(ARGS.which)) {
+if(ARGS.which !== undefined) {
```
Comment (zrhoffman) [inline traffic_stats/grafana/traffic_ops_server.js:45]: Nit: Since the whole file is reformatted now, `if(` should be `if (`.

Comment (ocket8888) [reply traffic_stats/grafana/traffic_ops_server.js:45]: Oh god it is isn't it?

Comment (zrhoffman) [reply traffic_stats/grafana/traffic_ops_server.js:45]: It looks like the change that blew up the diff was removing the curly braces around `dashboard.rows.push()`. After adding those back and reformatting, it's way more straightforward to see what changed.

Comment (ocket8888) [reply traffic_stats/grafana/traffic_ops_server.js:45]: Yes... but also idk why that nested block was there in the first place. I'll have to put it back in, I suppose.

Comment (zrhoffman) [reply traffic_stats/grafana/traffic_ops_server.js:45]: The brackets were added in Comcast/traffic_control#592, before which `traffic_ops_server.js` was just [the `else if ( type == "server" ) {}` clause](https://github.com/apache/trafficcontrol/blob/958e32a0f6/traffic_stats/grafana/traffic_ops_scripted.js#L376-L523) of a big if/else statement in `traffic_ops_scripted.js`, so there is no reason to keep them. But yeah, better to save removing the brackets from this and the other scripted dashboards for a separate PR.
