### PR TITLE
PUT /snapshot?cdn=not-found returns 404

### LINKED ISSUE #4551: PUT request to snapshot endpoint returns Internal Server Error
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `PUT` request to `/snapshot` with the query parameter `cdn` set to a cdn name that doesn't exist, `i.e. /snapshot?cdn=doesntexist` the response returned is:
```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should return:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json
{
    "alerts": [
        {
            "text": "No CDN found with that name",
            "level": "error"
        }
    ]
}
```
## Anything else:

Error Log:
```ERROR: api.go:180: ... Error getting CDN info: Error querying CDN domain name: sql: no rows in result set```

### PR DESCRIPTION
**Pull request by mitchell852**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4551 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

- Run the API tests. Ensure they all pass.

## If this is a bug fix, what versions of Traffic Control are affected?
- master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/crconfig/handler.go [hunk 1]
```diff
@@ -174,6 +174,12 @@ func snapshotHandler(w http.ResponseWriter, r *http.Request, deprecated bool) {
 			return
 		}
 		cdn = name
+	} else {
+		_, _, err := getCDNInfo(cdn, inf.Tx.Tx)
+		if err != nil {
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/crconfig/handler.go]: The `getCDNInfo` func call doesnt differentiate between database query error (lets say the db was down) or the cdn not existing.  Those would call for different errors being returns to the user.

I would suggest using https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/dbhelpers/db_helpers.go#L485 as it returns if it exists or not in a separate var
