### PR TITLE
Traffic Ops Golang parent.config

### LINKED ISSUE #2725: Explicit MSO Parent Rank wrong
The parent.config file is being populated with explicitly ordered parents in the wrong order.  This leads to scenarios involving MSO Primary/Secondary selection when using mso.algorthm false or latched to be wrong.  Workaround is to add a weight parameter to Primary such that they take vast majority of traffic, but not all since it's a relative weight similar to steering.

### LINKED ISSUE #3071: Traffic Ops generates bad default parent.config
The default parent.config lines generated by Traffic Ops for cache servers sets `round_robin=urlhash`, which isn't valid in Apache Trafficserver versions 4.2-9.0, and so has no conceivable purpose. The code in question ([lines 2604-2613 of ApacheTrafficServer.pm](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L2604-L2613)):
```perl
if ( defined($parent_select_alg) && $parent_select_alg eq 'consistent_hash' ) {
	$default_dest_text .= "dest_domain=. ";
	$default_dest_text .= $parents . $secparents;
	$default_dest_text .= " round_robin=consistent_hash go_direct=false";
}
else {    # default to old situation.
	$default_dest_text .= "dest_domain=. ";
	$default_dest_text .= $parents;
	$default_dest_text .= " round_robin=urlhash go_direct=false";
}
```
this file generation should either be re-written in Go with a valid default (preferable, but risky and time-consuming), or patched with a valid default value (not preferable, but relatively safe).

### PR DESCRIPTION
**Pull request by rob05c**
#### What does this PR do?

Traffic Ops Golang parent.config

~Still WIP. I've tested against a single edge and mid; still need to test against a large number of configurations of edges and mids.~

Removing WIP - I think this is good to be merged. I've manually diffed versus the old Perl parent.config, against every edge and mid in our production CDN. 

The only differences vs Perl, are where duplicate origins exist with different configurations (a data bug), and Perl arbitrarily selects one with no warning or error. Go now logs an error when that happens. Unfortunately, Perl is ordering them by an internal Perl hash of the object, which isn't feasible to replicate in Go. But again, it's a data bug to have that scenario at all.

Fixes #3071 in https://github.com/apache/trafficcontrol/pull/3075/commits/48ba440ce7f79d9c7701ed3cdc381a666372216d
Does _not_ fix #2725 - that's a much more invasive fix, I think should be a separate PR.

Includes API tests.

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### Check all that apply

- [x] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2862/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2868/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2874/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2891/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2892/
Test FAILed.

File: traffic_ops/client/atsconfig.go [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+}
+
+func (to *Session) GetATSCDNConfigByName(cdnName string, fileName string) (string, ReqInf, error) {
+	return to.getConfigFile(apiBase + "/cdns/" + cdnName + "/configfiles/ats/" + fileName)
+}
+
+func (to *Session) getConfigFile(uri string) (string, ReqInf, error) {
+	resp, remoteAddr, err := to.request(http.MethodGet, uri, nil)
+	reqInf := ReqInf{CacheHitStatus: CacheHitStatusMiss, RemoteAddr: remoteAddr}
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/client/atsconfig.go]: It's ok, this is how `remoteAddr` works. `to.request` is specifically defined to return a nil-or-valid `remoteAddr` even if `err != nil`. 

It's a violation of the Go idiom that "if a non-nil err is returned, all other returned values are undefined", but there's no simple way to avoid it, without ugly and awkward Error types and typecasting.

[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/client/atsconfig.go]: We should probably add a GoDoc comment to `to.request` explaining that.

File: traffic_ops/client/atsconfig.go [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
+		return tc.ATSConfigMetaData{}, reqInf, err
+	}
+	return data, reqInf, nil
+}
+
+func (to *Session) GetATSServerConfigListByName(serverHostName string) (tc.ATSConfigMetaData, ReqInf, error) {
+	resp, remoteAddr, err := to.request(http.MethodGet, apiBase+"/servers/"+serverHostName+"/configfiles/ats", nil)
+	reqInf := ReqInf{CacheHitStatus: CacheHitStatusMiss, RemoteAddr: remoteAddr}
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/client/atsconfig.go]: As above, this is correct usage of `to.request`.

File: traffic_ops/client/atsconfig.go [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+	"net/http"
+	"strconv"
+
+	"github.com/apache/trafficcontrol/lib/go-tc"
+)
+
+func (to *Session) GetATSServerConfigList(serverID int) (tc.ATSConfigMetaData, ReqInf, error) {
+	resp, remoteAddr, err := to.request(http.MethodGet, apiBase+"/servers/"+strconv.Itoa(serverID)+"/configfiles/ats", nil)
+	reqInf := ReqInf{CacheHitStatus: CacheHitStatusMiss, RemoteAddr: remoteAddr}
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/client/atsconfig.go]: As above, this is correct usage of `to.request`.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3104/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3106/
Test FAILed.

**Comment by rob05c** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3241/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3275/
Test PASSed.

**Comment by ocket8888** [comment]
So, I tested this by starting up two CiaB instances, one with this change and one without. CiaB comes with a single edge server assigned to the only DS (HTTP, qstr=USE). I added an HTTP_LIVE_NATL DS (qstr=USE) with its own, new edge-tier server pointing at the built-in origin. Then I added a DNS DS (qstr=DROP, uses cache_range_requests plugin) and assigned it to both the built-in edge and the new one I created. Then I tested the following routes using the `compare` tool:

```text
/api/1.1/servers/edge/configfiles/ats/parent.config
/api/1.2/servers/edge/configfiles/ats/parent.config
/api/1.3/servers/edge/configfiles/ats/parent.config
/api/1.4/servers/edge/configfiles/ats/parent.config
/api/1.1/servers/mid/configfiles/ats/parent.config
/api/1.2/servers/mid/configfiles/ats/parent.config
/api/1.3/servers/mid/configfiles/ats/parent.config
/api/1.4/servers/mid/configfiles/ats/parent.config
/api/1.1/servers/test/configfiles/ats/parent.config
/api/1.2/servers/test/configfiles/ats/parent.config
/api/1.3/servers/test/configfiles/ats/parent.config
/api/1.4/servers/test/configfiles/ats/parent.config
```

For all API versions on both edges the `parent.config` file output was consistent between the Perl and Go implementations. The only thing of note is that as of APIv1.4 the Go rewrite drops character encoding in the `Content-Type` header; Perl reports it as `text/plain;charset=UTF-8`, while Go reports it as `text/plain`. This isn't a huge deal as that's neither documented nor something that affects the content of the files, and the encoding should be determinable from an examination of the response body.

I'm more troubled by the fact that lower API versions than 1.4 are still being proxied to Perl. That, and a diff that appeared in the Mid-tier cache server's `parent.config`:

```diff
1c1,2
< # DO NOT EDIT - Generated for mid by Traffic Ops (https://trafficops.infra.ciab.test:443/) on Thu Feb 28 21:11:58 UTC 2019
---
> # DO NOT EDIT - Generated for mid by Traffic Ops (https://trafficops.infra.ciab.test:443/) on Thu Feb 28 21:11:57 UTC 2019
> dest_domain=. parent="" round_robin=consistent_hash go_direct=false
```

`<` refers to the file generated by Perl whereas `>` refers to the file generated by Go. Seen here, the Perl-generated `parent.config` is notoriously empty, while the Go-generated file has that one line.

**Comment by rob05c** [comment]
>I'm more troubled by the fact that lower API versions than 1.4 are still being proxied to Perl.
@ocket8888 Ah, I did that for debugging, it needs set to 1.1 before this is merged. 

Though it might be easier for anyone reviewing if it's left at 1.4 until then, so you can request the parent.config from Perl from the same TO for comparison.

**Comment by ocket8888** [comment]
Provided that's changed before the merge that's fine. I'm testing between multiple instances, so I've no need for a way to bypass the Go server.

Can you explain/defend the extra emitted line?

**Comment by rob05c** [comment]
I'm not sure, I'll have to look at the Perl again. Might be a few days before I can find time. I know all our Mids diffed clean when I wrote it, it's possible the Perl changed since, or our configuration changed to expose it. I'll try to track down where the logic is different

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 4]
```diff
@@ -0,0 +1,1393 @@
...
+
+	hdr, err := headerComment(inf.Tx.Tx, serverInfo.HostName)
+	if err != nil {
+		api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting header comment: "+err.Error()))
+		return
+	}
+
+	textArr := []string{}
+	text := ""
+	// TODO put these in separate functions. No if-statement should be this long.
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: agreed. Would you like to tackle this before it gets merged?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 5]
```diff
@@ -0,0 +1,1393 @@
...
+	if serverInfo.IsTopLevelCache() {
+		log.Errorf("DEBUG PCGen isTopLevel\n")
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 6]
```diff
@@ -0,0 +1,1393 @@
...
+
+		data, err := getParentConfigDSTopLevel(inf.Tx.Tx, serverInfo.CDN)
+		if err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting parent config DS data: "+err.Error()))
+			return
+		}
+
+		parentInfos := map[string][]ParentInfo{} // TODO better names (this was transliterated from Perl)
+
+		log.Errorf("DEBUG PCGTL len(data) %+v\n", len(data))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 7]
```diff
@@ -0,0 +1,1393 @@
...
+					orgURI.Host += ":80"
+				} else if orgURI.Scheme == "https" {
+					orgURI.Host += ":443"
+				} else {
+					log.Errorln("parent.config generation: fds '" + string(ds.Name) + "' origin  URI: '" + orgURIStr + "' is unknown scheme '" + orgURI.Scheme + "', but has no port! Using as-is! ")
+				}
+			}
+
+			if _, ok := uniqueOrigins[ds.OriginFQDN]; ok {
+				// log.Errorf("DEBUG PCGT uniqueorigins skipping %+v\n", ds.OriginFQDN)
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 8]
```diff
@@ -0,0 +1,1393 @@
...
+				parentQStr = "consider"
+			}
+
+			orgURIStr := ds.OriginFQDN
+			orgURI, err := url.Parse(orgURIStr) // TODO verify origin is always a host:port
+			if err != nil {
+				log.Errorln("Malformed ds '" + string(ds.Name) + "' origin  URI: '" + orgURIStr + "', skipping! : " + err.Error())
+				continue
+			}
+			// TODO put in function, to remove duplication
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to tackle this in this PR?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 9]
```diff
@@ -0,0 +1,1393 @@
...
+				}
+			}
+
+			if _, ok := uniqueOrigins[ds.OriginFQDN]; ok {
+				// log.Errorf("DEBUG PCGT uniqueorigins skipping %+v\n", ds.OriginFQDN)
+				continue // TODO warn?
+			}
+			uniqueOrigins[ds.OriginFQDN] = struct{}{}
+
+			log.Errorf("DEBUG PCGTQ origin %+v\n", ds.OriginFQDN)
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 10]
```diff
@@ -0,0 +1,1393 @@
...
+
+			// log.Errorf("DEBUG PCGT uniqueorigins adding ds '%+v' ds.OriginfQDN '%+v' orgURI.Hostname '%+v'\n", ds.Name, ds.OriginFQDN, orgURI.Hostname())
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 11]
```diff
@@ -0,0 +1,1393 @@
...
+
+			if ds.OriginShield != "" {
+				log.Errorf("DEBUG PCGT ds '%+v' is origin shield\n", ds.Name)
+				// TODO fix to only call once
+				serverParams, err := getParentConfigServerProfileParams(inf.Tx.Tx, serverInfo.ID)
+				if err != nil {
+					api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting server params: "+err.Error()))
+					return
+				}
+				// log.Errorf("DEBUG PCGT getParentConfigServerProfileParams %+v len %+v\n", serverInfo.ID, len(serverParams))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 12]
```diff
@@ -0,0 +1,1393 @@
...
+					algorithm = "round_robin=" + parentSelectAlg
+				}
+				textLine += "dest_domain=" + orgURI.Hostname() + " port=" + orgURI.Port() + " parent=" + ds.OriginShield + " " + algorithm + " go_direct=true\n"
+			} else if ds.MultiSiteOrigin {
+				log.Errorf("DEBUG PCGT ds '%+v' is multisite\n", ds.Name)
+				textLine += "dest_domain=" + orgURI.Hostname() + " port=" + orgURI.Port() + " "
+				if len(parentInfos) == 0 {
+					// If we have multi-site origin, get parent_data once
+					parentInfos, err = getParentInfo(inf.Tx.Tx, serverInfo)
+					// log.Errorf("DEBUG PCGT getParentInfo len %+v\n", len(parentInfos))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 13]
```diff
@@ -0,0 +1,1393 @@
...
+			uniqueOrigins[ds.OriginFQDN] = struct{}{}
+
+			log.Errorf("DEBUG PCGTQ origin %+v\n", ds.OriginFQDN)
+
+			// log.Errorf("DEBUG PCGT uniqueorigins adding ds '%+v' ds.OriginfQDN '%+v' orgURI.Hostname '%+v'\n", ds.Name, ds.OriginFQDN, orgURI.Hostname())
+
+			textLine := ""
+
+			if ds.OriginShield != "" {
+				log.Errorf("DEBUG PCGT ds '%+v' is origin shield\n", ds.Name)
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 14]
```diff
@@ -0,0 +1,1393 @@
...
+				// TODO fix to only call once
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to tackle this before this gets merged?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 15]
```diff
@@ -0,0 +1,1393 @@
...
+						return
+					}
+				}
+
+				if len(parentInfos[orgURI.Hostname()]) == 0 {
+					// TODO error? emulates Perl
+					log.Warnln("ParentInfo: delivery service " + ds.Name + " has no parent servers")
+				}
+
+				// log.Errorf("DEBUG PCGT parentInfos len %+v\n", len(parentInfos))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 16]
```diff
@@ -0,0 +1,1393 @@
...
+					// log.Errorf("DEBUG PCGT getParentInfo len %+v\n", len(parentInfos))
+					if err != nil {
+						api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting server parent info: "+err.Error()))
+						return
+					}
+				}
+
+				if len(parentInfos[orgURI.Hostname()]) == 0 {
+					// TODO error? emulates Perl
+					log.Warnln("ParentInfo: delivery service " + ds.Name + " has no parent servers")
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I _think_ this what happens when an MSO delivery service isn't assigned to at least one ORG server? Does that sound right? Not really sure of a good way to prevent that when creating an MSO DS, but here we should probably just roll with it to let other good DSes continue to get updates.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 17]
```diff
@@ -0,0 +1,1393 @@
...
+							log.Errorln("Malformed unavailable_server_retry_responses parameter '" + ds.MSOUnavailableServerRetryResponses + "', not using!")
+						}
+						textLine += ` parent_retry=` + parentRetry
+					}
+					textLine += ` max_simple_retries=` + ds.MSOMaxSimpleRetries + ` max_unavailable_server_retries=` + ds.MSOMaxUnavailableServerRetries
+				}
+				textLine += "\n"
+				textArr = append(textArr, textLine)
+			} else {
+				// log.Errorf("DEBUG PCGT ds '%+v' neither origin shield nor multisite\n", ds.Name)
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: should this else block be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 18]
```diff
@@ -0,0 +1,1393 @@
...
+					parents = `parent="` + strings.Join(parentInfo, "") + `" secondary_parent="` + strings.Join(secondaryParentInfo, "") + strings.Join(nullParentInfo, "") + `"`
+				} else {
+					parents = `parent="` + strings.Join(parentInfo, "") + strings.Join(secondaryParentInfo, "") + strings.Join(nullParentInfo, "") + `"`
+				}
+				textLine += parents + ` round_robin=` + ds.MSOAlgorithm + ` qstring=` + parentQStr + ` go_direct=false parent_is_proxy=false`
+
+				parentRetry := ds.MSOParentRetry
+				if atsMajorVer >= 6 && parentRetry != "" {
+					if unavailableServerRetryResponsesValid(ds.MSOUnavailableServerRetryResponses) {
+						log.Errorf("DEBUG unavailableServerRetryResponsesValid '%+v'\n", ds.MSOUnavailableServerRetryResponses)
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: another errorf debug

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 19]
```diff
@@ -0,0 +1,1393 @@
...
+				textLine += "\n"
+				textArr = append(textArr, textLine)
+			} else {
+				// log.Errorf("DEBUG PCGT ds '%+v' neither origin shield nor multisite\n", ds.Name)
+			}
+		}
+		sort.Sort(sort.StringSlice(textArr))
+		text = hdr + strings.Join(textArr, "")
+	} else {
+		log.Errorf("DEBUG PCGen not top level\n")
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 20]
```diff
@@ -0,0 +1,1393 @@
...
+		// not a top level cache
+		data, err := getParentConfigDS(inf.Tx.Tx, serverInfo.ID) // TODO rename
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to rename this?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 21]
```diff
@@ -0,0 +1,1393 @@
...
+		if err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting parent config DS data (non-top-level): "+err.Error()))
+			return
+		}
+
+		log.Errorf("DEBUG PCGen got data len %+v\n", len(data))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 22]
```diff
@@ -0,0 +1,1393 @@
...
+
+		parentInfos, err := getParentInfo(inf.Tx.Tx, serverInfo)
+		if err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting server parent info (non-top-level: "+err.Error()))
+			return
+		}
+
+		log.Errorf("DEBUG PCGen got parent info len %+v\n", len(parentInfos))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 23]
```diff
@@ -0,0 +1,1393 @@
...
+
+		done := map[string]tc.DeliveryServiceName{}                                       // map[originHost]ds
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: the comments seem unnecessary

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 24]
```diff
@@ -0,0 +1,1393 @@
...
+		serverParams, err := getParentConfigServerProfileParams(inf.Tx.Tx, serverInfo.ID) // (map[string]string, error) {
+		if err != nil {
+			api.HandleErr(w, r, inf.Tx.Tx, http.StatusInternalServerError, nil, errors.New("Getting parent config server profile params: "+err.Error()))
+			return
+		}
+
+		log.Errorf("DEBUG PCGen got server params len %+v\n", len(serverParams))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 25]
```diff
@@ -0,0 +1,1393 @@
...
+
+		qsh := serverParams[ParentConfigParamQStringHandling] // TODO rename
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to rename?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 26]
```diff
@@ -0,0 +1,1393 @@
...
+		parentInfo := []string{}
+		secondaryParentInfo := []string{}
+
+		log.Errorf("DEBUG PCGen ranging over len(parentInfos[DeliveryServicesAllParentsKey]) %+v\n", len(parentInfos[DeliveryServicesAllParentsKey]))
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can this be removed?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 27]
```diff
@@ -0,0 +1,1393 @@
...
+				secondaryParentInfo = append(secondaryParentInfo, pTxt)
+			}
+		}
+
+		if len(parentInfo) == 0 {
+			parentInfo = secondaryParentInfo
+			secondaryParentInfo = []string{}
+		}
+
+		// TODO remove duplicate code with top level if block
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to do this?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 28]
```diff
@@ -0,0 +1,1393 @@
...
+		seen := map[string]struct{}{} // TODO change to host+port? host isn't unique
+		parentInfo, seen = removeStrDuplicates(parentInfo, seen)
+		secondaryParentInfo, seen = removeStrDuplicates(secondaryParentInfo, seen)
+
+		parents := ""
+		secParents := "" // TODO rename
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to do this?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 29]
```diff
@@ -0,0 +1,1393 @@
...
+		sort.Sort(sort.StringSlice(secondaryParentInfo))
+		if atsMajorVer >= 6 && len(secondaryParentInfo) > 0 {
+			parents = `parent="` + strings.Join(parentInfo, "") + `"`
+			secParents = ` secondary_parent="` + strings.Join(secondaryParentInfo, "") + `"`
+		} else {
+			parents = `parent="` + strings.Join(parentInfo, "") + strings.Join(secondaryParentInfo, "") + `"`
+		}
+
+		roundRobin := `round_robin=consistent_hash`
+		goDirect := `go_direct=false` // TODO double-check with Perl, that this isn't ever different
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: can you confirm this?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 30]
```diff
@@ -0,0 +1,1393 @@
...
+				log.Errorln("Malformed ds '" + string(ds.Name) + "' origin  URI: '" + originFQDN + "': skipping!" + err.Error())
+				continue
+			}
+
+			if existingDS, ok := done[originFQDN]; ok {
+				log.Errorln("parent.config generation: duplicate origin! services '" + string(ds.Name) + "' and '" + string(existingDS) + "' share origin '" + orgURI.Host + "': skipping '" + string(ds.Name) + "'!")
+				continue
+			}
+
+			// TODO put in function, to remove duplication
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to do this?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 31]
```diff
@@ -0,0 +1,1393 @@
...
+					orgURI.Host += ":80"
+				} else if orgURI.Scheme == "https" {
+					orgURI.Host += ":443"
+				} else {
+					log.Errorln("parent.config generation non-top-level: ds '" + string(ds.Name) + "' origin  URI: '" + originFQDN + "' is unknown scheme '" + orgURI.Scheme + "', but has no port! Using as-is! ")
+				}
+			}
+
+			// debug
+			if orgURI.Hostname() == "odol-cim-linear-hds.cmc.co.ndcwest.comcast.net" {
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: this should be removed

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 32]
```diff
@@ -0,0 +1,1393 @@
...
+			} else {
+
+				// check for profile psel.qstring_handling.  If this parameter is assigned to the server profile,
+				// then edges will use the qstring handling value specified in the parameter for all profiles.
+
+				// If there is no defined parameter in the profile, then check the delivery service profile.
+				// If psel.qstring_handling exists in the DS profile, then we use that value for the specified DS only.
+				// This is used only if not overridden by a server profile qstring handling parameter.
+
+				// TODO refactor this logic, hard to understand (transliterated from Perl)
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: would you like to do this?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3457/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3458/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 33]
```diff
@@ -0,0 +1,1393 @@
...
+	ProfileName                   string
+	Port                          int
+	SecondaryParentCacheGroupID   int
+	SecondaryParentCacheGroupType string
+	Type                          string
+}
+
+func (s *ServerInfo) IsTopLevelCache() bool {
+	return (s.ParentCacheGroupType == TypeCacheGroupOrigin || s.ParentCacheGroupID == 0) &&
+		(s.ParentCacheGroupType == TypeCacheGroupOrigin || s.SecondaryParentCacheGroupID == 0)
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Fixed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 34]
```diff
@@ -0,0 +1,1393 @@
...
+  COALESCE(ds.multi_site_origin, false),
+  COALESCE(ds.origin_shield, ''),
+  dt.name AS ds_type
+`
+const ParentConfigDSQueryFromTopLevel = `
+FROM
+  deliveryservice ds
+  JOIN type as dt ON ds.type = dt.id
+  JOIN cdn ON cdn.id = ds.cdn_id
+` // TODO Perl does 'JOIN deliveryservice_regex dsr ON dsr.deliveryservice = ds.id   JOIN regex r ON dsr.regex = r.id   JOIN type as rt ON r.type = rt.id' and orders by, but doesn't use; ensure it isn't necessary
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: >Did you follow up and ensure they weren't necessary yet?

This code transliterates the Perl as closely as possible. The TODOs are things I think should be investigated, but I'd prefer to keep this PR matching the Perl, and fix them in a later PR, for safety.

>Can the debug comments be cleaned up?

Done

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 35]
```diff
@@ -0,0 +1,1393 @@
...
+	dses, err := getParentConfigDSRaw(tx, ParentConfigDSQueryTopLevel, []interface{}{cdnName})
+	if err != nil {
+		return nil, errors.New("getting top level raw parent config ds: " + err.Error())
+	}
+	topDSes := []ParentConfigDSTopLevel{}
+	for _, ds := range dses {
+		topDSes = append(topDSes, ParentConfigDSTopLevel{ParentConfigDS: ds})
+	}
+
+	// log.Errorf("DEBUG getParentConfigDSTopLevel topDses len %+v\n", len(topDSes))
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 36]
```diff
@@ -0,0 +1,1393 @@
...
+	dsesWithParams, err := getParentConfigDSParams(tx, dses)
+	if err != nil {
+		return nil, errors.New("getting ds params: " + err.Error())
+	}
+	return dsesWithParams, nil
+}
+
+// my $qstring = $self->profile_param_value( $server_obj->profile->id, 'parent.config', 'qstring', undef );
+// 		my $parent_select_alg = $self->profile_param_value( $server_obj->profile->id, 'parent.config', 'algorithm', undef );
+// my $qsh = $self->profile_param_value( $server_obj->profile->id, 'parent.config', 'psel.qstring_handling');
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 37]
```diff
@@ -0,0 +1,1393 @@
...
+}
+
+func getParentConfigDS(tx *sql.Tx, serverID int) ([]ParentConfigDS, error) {
+	log.Errorln("DEBUG dupar query QQ" + ParentConfigDSQuery + "QQ")
+
+	dses, err := getParentConfigDSRaw(tx, ParentConfigDSQuery, []interface{}{serverID})
+
+	// debug
+	seen := map[tc.DeliveryServiceName]struct{}{}
+	log.Errorf("DEBUG dupar checking\n")
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 28 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to do it in a subsequent PR, to minimize changes from the Perl (https://github.com/apache/trafficcontrol/blob/8fcde36019e37965ad5d1dd137032f26e3e4113d/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L2669).

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 31 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 30 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to do it in a subsequent PR, to minimize changes from the Perl

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 29 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 32 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to do it in a subsequent PR, to minimize changes from the Perl

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3459/
Test PASSed.

**Comment by rob05c** [comment]
>I'm more troubled by the fact that lower API versions than 1.4 are still being proxied to Perl.

@ocket8888 It should be 1.1, that was a mistake, I set it to 1.4 to debug. Fixed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3460/
Test PASSed.

**Comment by ocket8888** [comment]
> _"Does not fix #2725"_

Unfortunately, GitHub's not smart enough to pick up on that "not". You should re-word that, otherwise this PR is going to automatically close that issue.

**Comment by ocket8888** [comment]
So I'm still seeing some weird diffs
```diff
1,2c1,2
< # DO NOT EDIT - Generated for REDACTED by Traffic Ops (https://REDACTED/) on Fri Apr 12 17:00:47 UTC 2019
< dest_domain=REDACTED port=80 parent="REDACTED_A:80|1.0;REDACTED_B:80|1.0;" round_robin=consistent_hash qstring=consider go_direct=false parent_is_proxy=false parent_retry=both max_simple_retries=1 max_unavailable_server_retries=1
---
> # DO NOT EDIT - Generated for REDACTED by Traffic Ops (https://REDACTED/) on Fri Apr 12 17:00:43 UTC 2019
> dest_domain=rogers-eas.ipcdn-opl.comcast.net port=80 parent="REDACTED_B:80|1.0;REDACTED_A:80|1.0;" round_robin= qstring=ignore go_direct=false parent_is_proxy=false
```
You'll notice that the parent ordering is different, but since they're generated with explicit quality params, it shouldn't (significantly) alter ATS behavior. The discrepancy between which fields are present is probably a known issue that I like to call The Duplicate Origin Problem<sup>TM</sup> - though that's probably a bad name. However, what **is** a problem is `round_robin=` with no value. Need to figure that out.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3531/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 38]
```diff
@@ -0,0 +1,1393 @@
...
+		if err := rows.Scan(&name, &val); err != nil {
+			return nil, errors.New("scanning: " + err.Error())
+		}
+		params[name] = val
+	}
+	return params, nil
+}
+
+func getParentConfigDSRaw(tx *sql.Tx, qry string, qryParams []interface{}) ([]ParentConfigDS, error) {
+	log.Errorf("DEBUG PCGen getParentConfigDSRaw qry qqq%+vqqq params %+v\n", qry, qryParams)
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 39]
```diff
@@ -0,0 +1,1393 @@
...
+	}
+	defer rows.Close()
+	dses := []ParentConfigDS{}
+	for rows.Next() {
+		d := ParentConfigDS{}
+		if err := rows.Scan(&d.Name, &d.QStringIgnore, &d.OriginFQDN, &d.MultiSiteOrigin, &d.OriginShield, &d.Type); err != nil {
+			return nil, errors.New("scanning: " + err.Error())
+		}
+		if d.OriginFQDN == "" {
+			// TODO skip ANY_MAP DSes? Why? Did Perl, I didn't see it?
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I've confirmed to the best of my ability. I'd prefer to leave this comment in, because I'm unsure this is the correct behavior, but changing it at this time would be dangerous.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 40]
```diff
@@ -0,0 +1,1393 @@
...
+    '` + ParentConfigParamMaxUnavailableServerRetries + `'
+  )
+`
+
+const ParentConfigDSParamsQuery = ParentConfigDSParamsQuerySelect + ParentConfigDSParamsQueryFrom + ParentConfigDSParamsQueryWhere
+
+var ParentConfigDSParamsQueryTopLevel = ParentConfigDSParamsQuerySelect + ParentConfigDSParamsQueryFrom + ParentConfigDSParamsQueryWhereTopLevel
+
+func getParentConfigDSParams(tx *sql.Tx, dses []ParentConfigDS) ([]ParentConfigDS, error) {
+	params, err := getParentConfigDSParamsRaw(tx, ParentConfigDSParamsQuery, parentConfigDSesToNames(dses)) // (map[tc.DeliveryServiceName]map[string]string, error) {
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Removed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3548/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 41]
```diff
@@ -0,0 +1,1393 @@
...
+	if err != nil {
+		return nil, err
+	}
+	for i, ds := range dses {
+		dsParams, ok := params[ds.Name]
+		if !ok {
+			continue // TODO warn?
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I'm not sure, that's why the TODO is there. I often put TODOs to determine things I'm not sure about, if a future reader is able. Removed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 42]
```diff
@@ -0,0 +1,1393 @@
...
+const ParentConfigDSParamDefaultMaxUnavailableServerRetries = "1"
+
+func getParentConfigDSParamsTopLevel(tx *sql.Tx, dses []ParentConfigDSTopLevel) ([]ParentConfigDSTopLevel, error) {
+	params, err := getParentConfigDSParamsRaw(tx, ParentConfigDSParamsQueryTopLevel, parentConfigDSesToNamesTopLevel(dses))
+	if err != nil {
+		return nil, err
+	}
+	for i, ds := range dses {
+		dsParams, ok := params[ds.Name]
+		log.Errorf("DEBUG dsParams %++v\n", dsParams)
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Removed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 43]
```diff
@@ -0,0 +1,1393 @@
...
+
+	params := map[tc.DeliveryServiceName]map[string]string{}
+	for rows.Next() {
+		dsName := tc.DeliveryServiceName("")
+		pName := ""
+		pVal := ""
+		if err := rows.Scan(&dsName, &pName, &pVal); err != nil {
+			return nil, errors.New("scanning: " + err.Error())
+		}
+		log.Errorf("DEBUG getParentConfigDSParamsRaw dsName %+v pName %+v pVal %+v\n", dsName, pName, pVal)
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Removed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 44]
```diff
@@ -0,0 +1,1393 @@
...
+	Domain          string
+	Weight          string
+	UseIP           bool
+	Rank            int
+	IP              string
+	PrimaryParent   bool
+	SecondaryParent bool
+}
+
+// parentData parent_data in Perl
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 45]
```diff
@@ -0,0 +1,1393 @@
...
+	// note deliveryServies also contains an "all" key
+	// originFQDN is "prefix" in Perl; ds is not really a "ds", that's what it's named in Perl
+	for originFQDN, dses := range deliveryServices {
+		for _, row := range dses {
+			profile := profileCaches[row.ProfileID]
+			if profile.NotAParent {
+				log.Errorf("DEBUG PCGen getParentInfo row " + row.ServerHost + " not a parent, skipping\n")
+				continue
+			}
+			// Perl has this check, but we only select "deliveryServices" (servers) with the right CDN in the first place
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I'd prefer to keep it, until this has been tested in Production for a little while, in case there turns out to be an error, to help debug the problem.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 46]
```diff
@@ -0,0 +1,1393 @@
...
+			if parentInf.Port < 1 {
+				parentInf.Port = row.ServerPort
+			}
+			parentInfos[originFQDN] = append(parentInfos[originFQDN], parentInf)
+		}
+	}
+	return parentInfos, nil
+}
+
+// deliveryservices map[orgURI.Host]
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3549/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3550/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 47]
```diff
@@ -0,0 +1,1393 @@
...
+	return ProfileCache{
+		Weight:     "0.999",
+		Port:       0,
+		UseIP:      false,
+		Rank:       1,
+		NotAParent: false,
+	}
+}
+
+// TODO rename
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Renamed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 48]
```diff
@@ -0,0 +1,1393 @@
...
+  JOIN cdn on s.cdn_id = cdn.id
+  JOIN status st ON st.id = s.status
+WHERE
+  cg.id IN (SELECT v FROM parent_cachegroup_ids)
+  AND (stype.name = 'ORG' OR stype.name LIKE 'EDGE%' OR stype.name LIKE 'MID%')
+  AND (st.name = 'REPORTED' OR st.name = 'ONLINE')
+  AND cdn.name = $1
+`
+
+	// TODO move qry, qryParams to separate funcs/consts
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer not to, to minimize risk

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 49]
```diff
@@ -0,0 +1,1393 @@
...
+	qryParams := []interface{}{}
+	if server.IsTopLevelCache() {
+		qryParams = []interface{}{server.CDN}
+	} else {
+		qryParams = []interface{}{server.CDN, server.ID}
+	}
+
+	// log.Errorln("DEBUG gspi qry QQ" + qry + "QQ")
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3551/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 50]
```diff
@@ -0,0 +1,1393 @@
...
+			}
+		}
+	}
+	return profileCaches, deliveryServices, nil
+}
+
+// TODO change, this is terrible practice, using a hard-coded key. What if there were a delivery service named "all_parents" (transliterated Perl)
+const DeliveryServicesAllParentsKey = "all_parents"
+
+const TypeOrigin = "ORG" // TODO move to lib/go-tc
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3552/
Test FAILed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 51]
```diff
@@ -0,0 +1,1393 @@
...
+		profileCache, ok := sParams[param.ProfileID]
+		if !ok {
+			profileCache = DefaultProfileCache()
+		}
+		switch param.Name {
+		case ParentConfigCacheParamWeight:
+			// f, err := strconv.ParseFloat(param.Val, 64)
+			// if err != nil {
+			// 	log.Errorln("parent.config generation: weight param is not a float, skipping! : " + err.Error())
+			// } else {
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I don't agree. We should validate untyped data every place it's used. Complex Systems fail when there's only one failsafe, and it doesn't work when expected. Multiple failsafes prevent cascading system failure.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3553/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 52]
```diff
@@ -0,0 +1,1393 @@
...
+
+const ParentConfigCacheParamWeight = "weight"
+const ParentConfigCacheParamPort = "port"
+const ParentConfigCacheParamUseIP = "use_ip_address"
+const ParentConfigCacheParamRank = "rank"
+const ParentConfigCacheParamNotAParent = "not_a_parent"
+
+type ProfileID int
+
+// TODO rename
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3554/
Test FAILed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 53]
```diff
@@ -0,0 +1,1393 @@
...
+func unavailableServerRetryResponsesValid(s string) bool {
+	// optimization if param is empty
+	if s == "" {
+		return false
+	}
+	re := regexp.MustCompile(`^"(:?\d{3},)+\d{3}"\s*$`) // TODO benchmark, cache if performance matters
+	return re.MatchString(s)
+}
+func removeStrDuplicates(pi []string, seen map[string]struct{}) ([]string, map[string]struct{}) {
+	npi := []string{}
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: This is idiomatic Go. Go encourages names whose length matches the scope. See
https://golang.org/doc/effective_go.html#names
https://talks.golang.org/2014/names.slide#1
https://research.swtch.com/names

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 4 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to wait until the code has been vetted in Production for some time before making significant changes from the Perl transliteration, for safety.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 5 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 6 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 7 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 8 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to wait, for safey.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 9 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 10 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 11 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 12 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 14 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to wait, for safety.
This sounds simple, but it's slightly more than trivial, because both calls only occur in specific nested if-blocks.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 15 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 17 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 18 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Removed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 13 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 20 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 19 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 21 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 22 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 23 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: This comment specifically explains what the `string` is in `map[string]`. I'd prefer to keep it, to make the code easier to understand.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 25 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 26 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 28 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Changed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 27 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: As above, I'd prefer to wait, for safety.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 54]
```diff
@@ -0,0 +1,1393 @@
...
+func getParentConfigDSParamsTopLevel(tx *sql.Tx, dses []ParentConfigDSTopLevel) ([]ParentConfigDSTopLevel, error) {
+	params, err := getParentConfigDSParamsRaw(tx, ParentConfigDSParamsQueryTopLevel, parentConfigDSesToNamesTopLevel(dses))
+	if err != nil {
+		return nil, err
+	}
+	for i, ds := range dses {
+		dsParams, ok := params[ds.Name]
+		log.Errorf("DEBUG dsParams %++v\n", dsParams)
+		if !ok {
+			continue // TODO warn? set defaults anyway??
```
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Nothing. It assumes the object exists, and passes around an `undefined` variable, until it either prints as nothing, or something tries to dereference it and the script dies.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 16 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Possibly. I haven't seen it occur in the logs, so I'm not positive. I'd prefer to leave this `TODO` until someone comes along who positively has an answer, and they can remove it when they do the right thing with certainty.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 24 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by rob05c** [comment]
@ocket8888 When you get a chance, can you send me a private Slack message, with the hostname of the mid you saw that diff on? I can't reproduce. I just ran this on our Production data, and every server diffed clean (after removing duplicate origins, and different parent orderings).

**Comment by rob05c** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3555/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 51 above)
[the remark this answers is not in the document]
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Can you open a ticket to have the validation added in the POST/PUT if you don't want to include it here? I'm not saying you shouldn't have the check here. I'm saying that _only_  having the check here isn't good.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 53 above)
[the remark this answers is not in the document]
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: This is a function named `removeStrDuplicates`, yet the first param is named "pi". What is that even short for?
> A good name is:
> Consistent (easy to guess),
> Short (easy to type),
> Accurate (easy to understand).

"pi" is not easy to guess, nor is it easy to understand IMO. This also seems like a "util" function that belongs in some kind of string utility package so that it isn't just reimplemented all over the place where people need to remove duplicates from a list of strings.

> Function parameters are like local variables, 
but they also serve as documentation.
> Where the types are descriptive, they should be short:
> Where the types are more ambiguous, the names may provide documentation:

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 23 above)
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I guess I should say, the comment doesn't really explain what the map is even used for. Why not `originsToDSNames` instead of `done`. Then the comment is unnecessary and doesn't have to explain what the map holds.

**Comment by rob05c** [comment]
@ocket8888 Ok, I was able to reproduce the diff, and tracked it down. It was a particular edge case with defaults not getting set for top-level caches with parent retries.

It should be fixed now, if you get a chance to test again?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 51 above)
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done: https://github.com/apache/trafficcontrol/issues/3514

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3561/
Test PASSed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 53 above)
[the remark this answers is not in the document]
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3562/
Test FAILed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 23 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Done.

**Comment by rob05c** [comment]
Ok, I created an issue for the TODOs, and more generally to refactor and improve the code, once we're in a safer place: https://github.com/apache/trafficcontrol/issues/3515

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3563/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3564/
Test PASSed.

**Comment by ocket8888** [comment]
Getting a build failure on this branch:

```
# github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/deliveryservice
deliveryservice/deliveryservicesv12.go:77:6: getDSTenantIDByID redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:953:57
deliveryservice/deliveryservicesv12.go:90:6: GetDSTenantIDByIDTx redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:965:59
deliveryservice/deliveryservicesv12.go:103:6: getDSTenantIDByName redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:977:64
deliveryservice/deliveryservicesv12.go:116:6: GetDSTenantIDByNameTx redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:989:80
deliveryservice/deliveryservicesv12.go:137:6: GetXMLID redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:1013:50
deliveryservice/deliveryservicesv12.go:155:6: getTenantID redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:908:69
deliveryservice/deliveryservicesv12.go:167:6: isTenantAuthorized redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:920:82
deliveryservice/deliveryservicesv12.go:315:6: GetDeliveryServiceType redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:1001:63
deliveryservice/deliveryservicesv13.go:131:6: create redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:102:103
deliveryservice/deliveryservicesv13.go:239:6: createDefaultRegex redeclared in this block
	previous declaration at deliveryservice/deliveryservices.go:244:61
deliveryservice/deliveryservicesv13.go:239:6: too many errors
```

**Comment by rob05c** [comment]
@ocket8888 Odd, this PR shouldn't affect those files. I just rebased to the latest master, try now?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3591/
Test PASSed.

**Comment by ocket8888** [comment]
Builds now. Problem was new files introduced to the repo that were untracked in your branch - caused compilation errors because of docker's recursive copy and go's implicit build system.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 55]
```diff
@@ -0,0 +1,1302 @@
...
+
+	"github.com/apache/trafficcontrol/lib/go-log"
+	"github.com/apache/trafficcontrol/lib/go-tc"
+	"github.com/apache/trafficcontrol/lib/go-util"
+	"github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/api"
+
+	"github.com/lib/pq"
+)
+
+const DefaultATSVersion = "5" // emulates Perl
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Maybe a re-write isn't the time to change this, but we don't actually still support ATS 5 do we?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 56]
```diff
@@ -0,0 +1,1302 @@
...
+			orgURI, err := url.Parse(orgURIStr) // TODO verify origin is always a host:port
+			if err != nil {
+				log.Errorln("Malformed ds '" + string(ds.Name) + "' origin  URI: '" + orgURIStr + "', skipping! : " + err.Error())
+				continue
+			}
+			// TODO put in function, to remove duplication
+			if orgURI.Port() == "" {
+				if orgURI.Scheme == "http" {
+					orgURI.Host += ":80"
+				} else if orgURI.Scheme == "https" {
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: according to the quick tests I've done, `net/url.Parse` will casefold the scheme to lower - but is that true in all the Go versions we support? Probably, but I just wanna be sure.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 57]
```diff
@@ -0,0 +1,1302 @@
...
+					orgURI.Host += ":443"
+				} else {
+					log.Errorln("parent.config generation: fds '" + string(ds.Name) + "' origin  URI: '" + orgURIStr + "' is unknown scheme '" + orgURI.Scheme + "', but has no port! Using as-is! ")
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: What's "fds"? Could you be more verbose about that?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 58]
```diff
@@ -0,0 +1,1302 @@
...
+						textLine += ` parent_retry=` + parentRetry + ` unavailable_server_retry_responses=` + ds.MSOUnavailableServerRetryResponses
+					} else {
+						if ds.MSOUnavailableServerRetryResponses != "" {
+							log.Errorln("Malformed unavailable_server_retry_responses parameter '" + ds.MSOUnavailableServerRetryResponses + "', not using!")
+						}
+						textLine += ` parent_retry=` + parentRetry
+					}
+					textLine += ` max_simple_retries=` + ds.MSOMaxSimpleRetries + ` max_unavailable_server_retries=` + ds.MSOMaxUnavailableServerRetries
+				}
+				textLine += "\n"
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Would it make more sense to instead later join the array with `"\n"` instead of doing this every time and joining with an empty string?

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go [hunk 59]
```diff
@@ -0,0 +1,1302 @@
...
+	for ds, _ := range allDSMap {
+		allDSes = append(allDSes, int(ds))
+	}
+
+	dsOrigins, err := getDSOrigins(tx, allDSes)
+	if err != nil {
+		return nil, nil, errors.New("getting deliveryservice origins: " + err.Error())
+	}
+
+	for _, s := range ss {
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I think `ss` is maybe used too far away from its initial declaration to be using such a vague name. I don't know what `for _, s := range ss {` is doing, and figuring it out means looking back quite a bit, and interpreting another code block.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 55 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Not officially. I changed it to a TODO, so it'll be caught with the rest of the TODOs in https://github.com/apache/trafficcontrol/issues/3515

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 56 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Yes, it's not documented, but `url.Parse` calls `ToLower` since Go 1.1, so it can't be changed at this point without breaking people (I can't imagine why they would anyway).

https://github.com/golang/go/blob/release-branch.go1.1/src/pkg/net/url/url.go#L380

I'm not sure we have an "official" minimum supported version, but I believe we have code requiring 1.9. I'd have to research it, but we definitely use things introduced after 1.1, so compiling TO with <1.1 isn't possible.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 57 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: The "f" was a typo, supposed to be "ds" for "delivery service." Fixed.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 56 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: I think we have different Go version requirements documented per component. But regardless I think all of them are > 1.1

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 58 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Maybe. At this point, I'd really prefer not to change it. These variables are reused so much, as an artifact of Perl, I'd be afraid of accidentally changing the logic and breaking something. I added a TODO so it'll be looked at with the rest of #3515 if that's ok?

Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: It's not a bug, so I'm fine with it as long as it's captured somehow.

File: traffic_ops/traffic_ops_golang/ats/parentdotconfig.go (hunk 59 above)
Comment (rob05c) [reply traffic_ops/traffic_ops_golang/ats/parentdotconfig.go]: Changed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3597/
Test PASSed.

**Comment by rawlinp** [comment]
> Also, fwiw I think it's perfectly fine to log warnings even where Perl didn't - it doesn't change the logic 

We need to be mindful of the amount of logging we add and decide whether or not it really needs to be added at all, and if it truly is needed, it should be logged at the right level. If we add unnecessary warnings to code that gets called thousands of times during a Queue Updates operation, then we now have thousands of warnings that could otherwise be drowning out _actual_ problems that need addressed.

Basically, if a warning is just "normal operation" of the system, then it should not be logged as a warning. A warning generally means that that the system is operating sub-optimally, and that something needs addressed before the warnings start leading to errors. If someone is digging into the logs, they should be able to quickly identify issues without having to sift through a bunch of meaningless information. A good rule of thumb is to imagine you're the ops engineer that's been tasked with triaging an issue in Production and has to dig into the logs without any knowledge of the code internals. You'll want to do yourself a favor at that point.

Just my 2 cents :)

**Comment by rob05c** [comment]
>if a warning is just "normal operation" of the system, then it should not be logged as a warning. A warning generally means that that the system is operating sub-optimally, and that something needs addressed before the warnings start leading to errors

I agree. As far as I'm aware, all the warnings I added are things that should be addressed. But I could be mistaken, this code in particular is pretty easy to mistake normal operation for an issue, I'm open to changing anything that was misunderstood and acceptable as normal operation.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3598/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3599/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3600/
Test FAILed.

**Comment by rawlinp** [comment]
I think the current warnings in this PR are fine. I don't really know which warnings @ocket8888 was referring to, but from what I can remember about my initial review a long time ago, most of my comments about removing logging were for logs that seemed like informational debug logs that would only be useful for developing/testing this implementation. ¯\_(ツ)_/¯

**Comment by ocket8888** [comment]
I was referring to logs that aren't there, there are two or three places where data is missing or malformed that just causes the current function to bail or skip the current item and he has e.g. `// TODO log a warning? Perl doesn't`

**Comment by rob05c** [comment]
Yeah, those particular comments, I'm not sure whether it's normal operation, or an issue

**Comment by rob05c** [comment]
retest this please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3604/
Test PASSed.
