### PR TITLE
Use RFC lib and correct Content-Type on TM api

### LINKED ISSUE #2565: Traffic Monitor API gives incorrect Content-Type Header (or response format) for `version` and `traffic-ops-uri`
The TM endpoints at `/api/version` and `/api/traffic-ops-uri` both return plain-text responses, but have a `Content-Type` header that declares it to be `application/json`. The responses should either be wrapped in double quotes to make them valid JSON strings, or the `Content-Type` header should be set to `text/plain`.

### PR DESCRIPTION
**Pull request by shamrickus**
## What does this PR (Pull Request) do?

- [x] This PR fixes #2565. 

It replaces the content-type specification in TM with those found in the go-rfc lib. It also changes the `/api/version` and `/api/traffic-ops-uri` TM endpoints to have a Content-Type of `text/plain`/`text/uri-list` (respectively) in place of `application-json` as it does not return a valid JSON string.

## Which Traffic Control components are affected by this PR?

- Traffic Monitor

## What is the best way to verify this PR?
Ensure TM tests pass
Make a request to `api/version` and `api/traffic-ops-uri` and confirm Content-Type

## If this is a bug fix, what versions of Traffic Control are affected?
master (9e69ce1)

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information|

Before:
```
❯ curl -v http://localhost/api/version
*   Trying ::1:80...
* Connected to localhost (::1) port 80 (#0)
> GET /api/version HTTP/1.1
> Host: localhost
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 13 Aug 2020 17:14:52 GMT
< Content-Length: 28
< 
* Connection #0 to host localhost left intact
traffic_monitor-4.2.0.9e69ce
```

After:   
```
❯ curl -v http://localhost/api/version
*   Trying ::1:80...
* Connected to localhost (::1) port 80 (#0)
> GET /api/version HTTP/1.1
> Host: localhost
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Thu, 13 Aug 2020 17:14:52 GMT
< Content-Length: 28
< 
* Connection #0 to host localhost left intact
traffic_monitor-4.2.0.9e69ce   
```

### CODE REVIEW

File: traffic_monitor/datareq/datareq.go [hunk 1]
```diff
@@ -72,62 +73,62 @@ func MakeDispatchMap(
...
-		}, ContentTypeJSON)),
+		}, rfc.ApplicationJSON)),
 		"/api/version": wrap(WrapBytes(func() []byte {
 			return srvAPIVersion(staticAppData)
-		}, ContentTypeJSON)),
+		}, rfc.ContentTypeTextPlain)),
 		"/api/traffic-ops-uri": wrap(WrapBytes(func() []byte {
 			return srvAPITrafficOpsURI(opsConfig)
-		}, ContentTypeJSON)),
+		}, rfc.ApplicationJSON)),
```
Comment (ocket8888) [inline traffic_monitor/datareq/datareq.go:116]: As per #2565 (which this PR will fix, btw), `/api/traffic-ops-uri` does not return a JSON-encoded response. `text/plain` would not be incorrect, but [`text/uri-list`](https://tools.ietf.org/html/rfc2483#section-5) would be better.
