### PR TITLE
Topology based DS's + reqd capabilities + ORG servers should show ORG servers, alongwith the other servers when queried for the linked servers

### LINKED ISSUE #5380: ds topology + required server capabilities + assigned ORG servers not working correctly
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
GET /api/3.0/servers?dsId={{id}} does not return ORG servers directly assigned to the DS if:
1. a topology is assigned to the DS and
2. one ore more ORG servers are directly assigned to the DS and
3. the ds requires server capabilities that the ORG server(s) does not have

In fact, I don't even think you are allowed to assign server capabilities to an ORG so you'd never be able to accomplish #3.

Note: this issue also seems to affect ORT/atstccfg as the applicable line for the ds in parent.config file is missing altogether when the only parent(s) are ORG servers that don't have the necessary server capability. ORG servers are exempt from server capability filtering and should ALWAYS show up for a ds in which they are directly assigned (server capability or not) but looks like this was addressed with PR #5383 

## Expected behavior:
If I recall correctly, server capabilities are not applicable to ORG servers, therefore, for a ds with a topology AND required server capabilities:
a. show all the servers in the topology in the same cdn as the ds
b. minus the ones w/o the ds's required server caps...except for ORG servers which server caps do not apply to (if assigned, show ORG servers regardless)

## Minimal reproduction of the problem with instructions:
1. assign a topology to a DS
2. assign an ORG to the DS
3. create a server capability (https://tp.domain.tld/#!/server-capabilities) and add it to the DS as a required capability at https://tp.domain.tld/#!/delivery-services/999/required-server-capabilities
4. View the servers associated with the DS: https://tp.cdn.comcast.net/#!/delivery-services/999/servers - despite the assigned ORG server not having the DS's required server capability, it should be displayed.
5. add the server capability to one or more of the topology's servers. Now https://tp.cdn.comcast.net/#!/delivery-services/999/servers  should show the ORG plus the edges/mids that you assigned the server capability to.

### PR DESCRIPTION
**Pull request by srijeet0406**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5380  

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Ops
- CI tests

## What is the best way to verify this PR?

Create a topology based DS with some required capabilities
Assign some ORG servers directly to this DS

Before the fix:
If you query for the servers of this DS using `GET /api/3.0/servers?dsId=<YOUR DS ID>`, you will only get the edges and mids that are:
1.) In the topology AND
2.) In the same CDN as the DS AND
3.) Have the server capabilities as specified in the DS
You will notice that the ORG servers DO NOT show up in the list.

After the fix:
If you perform the same steps, you will notice that the ORG servers also show up in the result now.

## If this is a bug fix, what versions of Traffic Control are affected?

- master
## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR includes documentation
- [x] This PR includes an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 1]
```diff
@@ -846,6 +875,15 @@ func getServers(h http.Header, params map[string]string, tx *sqlx.Tx, user *auth
...
 
 	where, orderBy, pagination, queryValues, errs := dbhelpers.BuildWhereAndOrderByAndPagination(params, queryParamsToSQLCols)
+
+	// get the origin server count
+	if _, ok := params["dsId"]; ok {
+		serverCountOrigin, err = getServerCount(tx, serverCountQuery+originServerQuery, queryValues)
+		if err != nil {
+			return nil, 0, nil, fmt.Errorf("failed to get origin servers count: %v", err), http.StatusInternalServerError, nil
+		}
+	}
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/server/servers.go:885]: Why is it necessary to count origin servers separately? We should avoid adding additional queries when we can.

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 2]
```diff
@@ -855,22 +893,12 @@ func getServers(h http.Header, params map[string]string, tx *sqlx.Tx, user *auth
...
-		if err = countRows.Scan(&serverCount); err != nil {
-			return nil, 0, nil, fmt.Errorf("failed to read servers count: %v", err), http.StatusInternalServerError, nil
-		}
-		rowsAffected++
-	}
-	if rowsAffected != 1 {
-		return nil, 0, nil, fmt.Errorf("incorrect rows returned for server count, want: 1 got: %v", rowsAffected), http.StatusInternalServerError, nil
-	}
 
+	serverCount += serverCountOrigin
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/server/servers.go:901]: Tested this against CDN in a Box. In the case of no required capabilities, the original server count (6) is accurate, so the reported server count ends up being 7 instead of 6.

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 3]
```diff
@@ -767,6 +773,26 @@ JOIN type t ON s.type = t.id ` +
...
+	for countOrigRows.Next() {
+		if err = countOrigRows.Scan(&serverCount); err != nil {
+			return 0, fmt.Errorf("failed to read servers count: %v", err)
+		}
+		rowsAffected++
+	}
+	if rowsAffected != 1 {
+		return 0, fmt.Errorf("incorrect rows returned for server count, want: 1 got: %v", rowsAffected)
+	}
+	return serverCount, nil
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/server/servers.go:793]: A scalar value is returned from getServerCount(). No need to defer or loop, this can compute the server count in SQL itself and return the result.

**Review by zrhoffman — CHANGES_REQUESTED** [review]

File: traffic_ops/traffic_ops_golang/server/servers.go (hunk 1 above)
Comment (srijeet0406) [reply traffic_ops/traffic_ops_golang/server/servers.go:885]: I've made the change so that we are accounting for the origin servers in the same query.

File: traffic_ops/traffic_ops_golang/server/servers.go (hunk 2 above)
Comment (srijeet0406) [reply traffic_ops/traffic_ops_golang/server/servers.go:901]: Fixed the count now. I'm querying for the ORGs separately only when its specific to a DS that has reqd capabilities.

File: traffic_ops/traffic_ops_golang/server/servers.go (hunk 3 above)
Comment (srijeet0406) [reply traffic_ops/traffic_ops_golang/server/servers.go]: Fixed to use a NamedStatement instead.

File: traffic_ops/testing/api/v3/deliveryservices_required_capabilities_test.go [hunk 4]
```diff
@@ -45,9 +46,44 @@ func TestDeliveryServicesRequiredCapabilities(t *testing.T) {
...
+		t.Fatalf("no ID in the resulting delivery service")
+	}
+	dsID := *resp[0].ID
+	params := url.Values{}
+	_, _, err = TOSession.AssignServersToDeliveryService([]string{"denver-mso-org-01"}, "ds-top-req-cap2")
+	if err != nil {
+		t.Errorf("assigning ORG server to ds-top delivery service: %v", err.Error())
+	}
+	params.Add("dsId", strconv.Itoa(dsID))
+	params.Add("type", "ORG")
```
Comment (zrhoffman) [inline traffic_ops/testing/api/v3/deliveryservices_required_capabilities_test.go:71]: `"ORG"` should be `tc.OriginTypeName`

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 5]
```diff
@@ -399,6 +399,12 @@ RETURNING
 	upd_pending
 `
 
+const originServerQuery = `
+JOIN deliveryservice_server dsorg 
+ON dsorg.server = s.id 
+WHERE t.name='ORG'
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/server/servers.go:405]: `ORG` should be `tc.OriginTypeName`

**Review by zrhoffman — CHANGES_REQUESTED** [review]

**Review by zrhoffman — APPROVED** [review]
