### PR TITLE
Servers table switch to ag-grid

### LINKED ISSUE #2326: TP: [RFE] addition of "NOT" (!) operator in search fields
Today, we have the ability to search using `^` and `$` characters. As a user of Traffic Portal, it would also be useful to be able to negate search strings using `!`.

### LINKED ISSUE #2624: Improve TP search query
I'm primarily concerned with the server list, but similar considerations would apply elsewhere.

I'd like the ability to express more complex statements in the TP search box.  Currently you get a substring whitelist across all visible fields.  I'd like to be able to express things like NOT, AND, OR, and groups.  As an additional consideration, being able to supply an optional attribute to each search tuple to specify on what fields it should apply would be nice.  An over the top consideration would be regex support.

### LINKED ISSUE #4354: Improve performance (pagination and search) of TP's tables
## I'm submitting a ...

- [ ] bug report
- [x] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

This would be an improvement for TP and a potential enhancement to the TO API.

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Currently TP fetches ALL records (i.e. servers, delivery services, etc) from the TO API and does the pagination and search on the client-side in the browser. As the number of records grow, the amount of time required by jquery datatables to render the TP tables and the amount of browser memory required to do this grows. Eventually that memory may run out and TP tables may become unusable.

## Expected / new behavior:
2 possible solutions:
1. Implement a better table library
2. push the pagination and search to the server-side (the API) and leveraging some of the existing as well as some new features of the API.

## Minimal reproduction of the problem with instructions:
Create thousands of records (i.e. servers) and navigate to https://tp.domain.net/#!/servers and watch how long it takes for the table to render.

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #4354 and fixes #2624 and fixes #2326

Switches the "/servers" table from jQuery datatables to agGrid, increasing load speed by a factor of about 14.

The new tables have a superset of the functionality of the old tables.

## Which Traffic Control components are affected by this PR?
- Traffic Portal

## What is the best way to verify this PR?
Run Traffic Portal - preferably with a whole ton of servers so you can be impressed by the lightning fast load speed (at least compared to the jQuery data tables).

If #4747 isn't merged yet then you'll need to be using a version of TO that doesn't include the changes from #4700 .

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: traffic_portal/grunt/browserify2.js [hunk 1]
```diff
@@ -89,7 +94,7 @@ module.exports = {
                         cwd: '<%= globalConfig.app %>/bower_components/',
                         src:
                             [
-                                'angular/angular.js',
+                                // 'angular/angular.js',
```
Comment (mitchell852) [inline traffic_portal/grunt/browserify2.js:97]: you want to put this back and we can do this in another PR?

File: traffic_portal/grunt/copy.js [hunk 2]
```diff
@@ -42,6 +42,13 @@ module.exports = {
                     'traffic_portal_release.json',
                     'traffic_portal_properties.json'
                 ]
+            },
+            {
+                expand: true,
```
Comment (mitchell852) [inline traffic_portal/grunt/copy.js:47]: i don't _think_ this is necessary

File: traffic_portal/grunt/copy.js [hunk 3]
```diff
@@ -78,6 +85,13 @@ module.exports = {
...
```
Comment (mitchell852) [inline traffic_portal/grunt/copy.js:90]: nor this

File: traffic_portal/grunt/browserify2.js (hunk 1 above)
Comment (ocket8888) [reply traffic_portal/grunt/browserify2.js:97]: Yeah, that wasn't meant to be in there.

File: traffic_portal/grunt/copy.js (hunk 2 above)
Comment (ocket8888) [reply traffic_portal/grunt/copy.js:47]: It is, unfortunately.

**Comment by mitchell852** [comment]
image

**Comment by mitchell852** [comment]
image

Not sure why "Clear Updates" is disabled.

**Comment by ocket8888** [comment]
"Clear Server Updates" is _meant_ to be disabled when the server isn't a cache server and/or doesn't have pending updates. "Queue Server Updates" is meant to be disabled when the server isn't a cache server and/or _does_ have pending updates. Just to be clear about the intended behavior, because the old context menu would hide those options instead of disabling them.

Clearly, though, that's a cache server, and it _looks_ like it has updates pending. So something's probably wrong.

**Comment by mitchell852** [comment]
> Clearly, though, that's a cache server, and it _looks_ like it has updates pending. So something's probably wrong.

yeah, something is weird there. it's a cache server and updPending=true so "clear updates" should be an option. i looked at the logic and it seemed right so not sure:

```
            <button type="button" ng-click="clearServerUpdates(server, $event)" ng-disabled="!isCache(server) || !server.updPending">Clear Server Updates</button>
```

File: traffic_portal/app/src/common/modules/table/servers/TableServersController.js [hunk 4]
```diff
@@ -17,405 +17,634 @@
...
-        });
-    });
+var TableServersController = function(servers, $scope, $state, $uibModal, $window, dateUtils, locationUtils, serverUtils, cdnService, serverService, statusService, propertiesModel, messageModel, userModel, $document) {
+	/**** Table cell formatters/renderers ****/
 
+	// browserify can't handle classes...
+	function SSHCellRenderer() {}
+	SSHCellRenderer.prototype.init = function(params) {
+		this.eGui = document.createElement("A");
+		this.eGui.href = "ssh://" + userModel.user.username + "@" + params.value;
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/table/servers/TableServersController.js:27]: not sure if you want to / can address this as part of this PR:

https://github.com/apache/trafficcontrol/issues/1801

Comment (ocket8888) [reply traffic_portal/app/src/common/modules/table/servers/TableServersController.js:27]: I could - and considered it - but I don't want to. For this PR I just want to make sure the new table(s) has/have all the same functionality as was expected of the previous version.

**Comment by mitchell852** [comment]
Maybe in order to get this merged sooner rather than later. just focus on these 3 things i found:

1. cdn column is empty
2. clear updates context menu is disabled
3. ensure that this is not a problem:

image

**Comment by ocket8888** [comment]
"cdn column is empty" is already fixed. Might not have pushed it.
"Failed to load stored column state: one or more columns not found" is also not a real problem. I think that's actually related to the cdns thing. It saved column state with a "cdn" column, and the fix was to make it a "cdnName" column. So you need to clear your local storage. Nobody who didn't use it while it was still in a pull request should see that error.

File: traffic_portal/app/src/common/modules/table/servers/TableServersController.js [hunk 5]
```diff
@@ -17,405 +17,633 @@
...
+			headerName: "Network Subnet",
+			field: "ipNetmask",
+			hide: true,
+			searchable: false
+		},
+		{
+			headerName: "Offline Reason",
+			field: "offlineReason",
+			hide: true,
+			searchable: false
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/table/servers/TableServersController.js]: why does it say some are not searchable? looks like they are are all searchable once they are visible.

File: traffic_portal/app/src/common/modules/table/servers/TableServersController.js [hunk 6]
```diff
@@ -17,405 +17,633 @@
...
+			this.eGui.classList.add("fa-check");
+		}
+	}
+	UpdateCellRenderer.prototype.getGui = function() {return this.eGui;};
+
+	/**
+	 * Gets text with which to file a status tooltip.
+	 * @returns {string | undefined} The offline reason if the server is offline, otherwise nothing.
+	 */
+	function offlineReasonTooltip(params) {
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/table/servers/TableServersController.js:51]: does this work? i can't get it to when i hover over status and tbh not even really sure it's needed since there's an offline reason column anyhow.

**Comment by mitchell852** [comment]
nit: the context menu doesn't close when you select 'open in new tab" or "navigate to fqdn" or "show charts". basically anything that opens a new window/tab

File: traffic_portal/app/src/common/modules/table/servers/TableServersController.js (hunk 5 above)
Comment (ocket8888) [reply traffic_portal/app/src/common/modules/table/servers/TableServersController.js]: those don't belong there. I actually already got rid of those properties by the time you made this review :P

File: traffic_portal/app/src/common/modules/table/servers/TableServersController.js (hunk 6 above)
Comment (ocket8888) [reply traffic_portal/app/src/common/modules/table/servers/TableServersController.js:51]: It only shows up when the server is set to an "offline" status, e.g. OFFLINE. Works for me. I don't really think it needs to be there either, but the jQuery datatables did it, so I did too.

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/table/servers/TableServersController.js:51]: yep, that makes sense

**Comment by ocket8888** [comment]
That should be fixed now

File: traffic_portal/package.json [hunk 7]
```diff
@@ -30,5 +30,8 @@
     "requirejs": "2.3.6",
     "ssl-root-cas": "1.3.1",
     "time-grunt": "1.3.0"
+  },
+  "dependencies": {
+    "ag-grid-community": "^23.2.0"
```
Comment (mitchell852) [inline traffic_portal/package.json:35]: i guess i'm less risk tolerant but i'd do `23.2.0` or `~23.2.0` rather than letting it roll ahead to new minor versions, but your call.

Comment (ocket8888) [reply traffic_portal/package.json:35]: That's just the default behavior when you `npm install --save` something.

I don't see a problem with letting it roll ahead to new minor versions; the API won't ever break so it should only come with more benefits. Besides, pinning these things and never coming back is how we wind up on unsupported releases for years.
