### PR TITLE
RGB - Lookup Zip Code based on Lat/Long if Zip Code is null

### LINKED ISSUE #4372: RGB - Lookup Zip Code based on Lat/Long if Zip Code is null
## I'm submitting a ...
- [ ] bug report
- [x] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Currently when RGB is enabled, a client will be Geo Blocked if their IP does not have a zip code.  Sometime, especially with IP addresses, clients who should be allowed are not.
## Expected / new behavior:
If a client IP does not have a Zip code but does have a lat/long then we should use the lat/long to look up the zip code and then apply RGB logic. 
## Minimal reproduction of the problem with instructions:

### PR DESCRIPTION
**Pull request by srijeet0406**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4372 

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Documentation
- Traffic Router

## What is the best way to verify this PR?

Make sure all the unit tests and API tests pass.

Add a line in your regional_geoblock config file under the `geoLocation` key, which has the allowed coordinate ranges like this:

`"geoLocation": {
                "excludePostalCode": [
                    "V5G",
                    "M7A"
                ],
                "coordinateRange": [{"minLat" : -12, "maxLat": 13, "minLon" : 55, "maxLon": 56}, {"minLat" : -13, "maxLat": 14, "minLon" : 55, "maxLon": 56}]
            }`

For a TR request, try spoofing the IP address of the client, such that the client doesn't have a postal code associated with it.
Make sure the min/max lat/long values are valid, and that the user's lat/long (which you get by spoofing the IP) falls within one of these ranges.
This IP should NOT be blocked by RGB.
Now, try to change the coordinate ranges in the config file, such that the request's lat/long do NOT fall in these ranges.
Make the request again.
This time, the IP should be blocked by RGB.

## If this is a bug fix, what versions of Traffic Control are affected?

master

## The following criteria are ALL met by this PR

- [x] This PR includes tests 
- [x] This PR includes documentation 
- [x] This PR includes an update to CHANGELOG.md 
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/RegionalGeo.java [hunk 1]
```diff
@@ -219,6 +251,11 @@ private static RegionalGeo parseConfigJson(final JsonNode json) {
                     LOGGER.error("RegionalGeo ERR: geoLocation empty");
                     return null;
                 }
+                // coordinate range
+                final List<RegionalGeoCoordinateRange> coordinateRanges = parseLocationJsonCoordinateRange(locationJson);
+                if (coordinateRanges != null) {
+                    regionalGeo.setCoordinateRanges(coordinateRanges);
```
Comment (mattjackson220) [inline traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/RegionalGeo.java:257]: why do we set this here? doesnt look like we ever use the class level variable so maybe we can get rid of it and the getter/setter and this if statement?

Comment (srijeet0406) [reply traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/loc/RegionalGeo.java]: You're correct, I removed it, along with the if statement, and the getters and setters.
