### PR TITLE
Fixed https status code when updating CDN for a DS for existing SSL keys

### LINKED ISSUE #5341: PUT /api/3.0/deliveryservices/{id} with changed cdn returns 403 forbidden
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
Changing the CDN for a delivery service returns a 403 with 

```
{"alerts":[{"text":"Forbidden","level":"error"}]}
```

403s are for operations that fail role or tenancy check.

## New behavior:
This needs to be a 400 Bad Request instead with a message like:

```
{"alerts":[{"text":"Delivery service CDN is immutable","level":"error"}]}
```

## Minimal reproduction of the problem with instructions:
Navigate to a DS in TP and change the CDN value. Save.

## Anything else:
If the intent is to make CDN immutable on a DS, the cdn field of an existing DS should be disabled as well to prevent the user from changing it.

### PR DESCRIPTION
**Pull request by rimashah25**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5341 

## Which Traffic Control components are affected by this PR?

- Traffic Ops
- Traffic Portal

## What is the best way to verify this PR?

Run TP end-to-end tests and TO API tests

## If this is a bug fix, what versions of Traffic Control are affected?

- master(7a3506a)

## The following criteria are ALL met by this PR

- [x] I have explained why tests are unnecessary
- [x] I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

## Additional Information

The PR doesn't have tests or documentation update as the logic hasn't changed.

### CODE REVIEW

**Review by mitchell852 — COMMENTED** [review]
do u want to create an api test that attempts to change the cdn of a ds and ensure that a 400 is returned?

**Review by mitchell852 — COMMENTED** [review]
also, in the delivery-services-spec.js file, can you add a check to each of the update tests to ensure the cdn dropdown is enabled?

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go [hunk 1]
```diff
@@ -1018,7 +1018,7 @@ func updateV31(w http.ResponseWriter, r *http.Request, inf *api.APIInfo, dsV31 *
 	}
 
 	if newDSType.HasSSLKeys() && (oldHostName != newHostName || oldCDNName != newCDNName || oldRoutingName != *ds.RoutingName) {
-		return nil, http.StatusForbidden, nil, errors.New("delivery service has ssl keys that cannot be automatically changed")
+		return nil, http.StatusBadRequest, errors.New("delivery service CDN is immutable"), errors.New("delivery service has ssl keys that cannot be automatically changed")
```
Comment (mitchell852) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:1021]: is this supposed to return 2 errors? because i'm only seeing one.

Comment (mitchell852) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:1021]: maybe the error message needs to be something like - "delivery service has ssl keys that cannot be automatically changed therefore, cdn and routing name are immutable"

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html [hunk 2]
```diff
@@ -171,7 +171,7 @@ <h3>Current Value</h3>
                         </div>
                         </label>
                         <div class="col-md-10 col-sm-10 col-xs-12">
-                            <select id="cdn" name="cdn" class="form-control" ng-model="deliveryService.cdnId" ng-options="cdn.id as cdn.name for cdn in cdns" required>
+                            <select id="cdn" name="cdn" class="form-control" ng-model="deliveryService.cdnId" ng-options="cdn.id as cdn.name for cdn in cdns" required ng-disabled="!settings.isNew">
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: i guess you should leave this enabled as you can change the cdn on a DS IF the ds has no ssl keys...

Comment (rimashah25) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: The reason I added it because of this statement, "_If the intent is to make CDN immutable on a DS, the cdn field of an existing DS should be disabled as well to prevent the user from changing it._"

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go (hunk 1 above)
Comment (rimashah25) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:1021]: The error I added is user error. The system error in my opinion is not needed but I maybe wrong.

**Comment by rimashah25** [comment]
> do u want to create an api test that attempts to change the cdn of a ds and ensure that a 400 is returned?

I'll add one. That is a good idea.

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html (hunk 2 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: where did u see that statement?

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: i _think_ cdn and routing name are only immutable if the ds has ssl keys, otherwise, make the change...

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: as a user, i would be annoyed if i created a delivery service and put it in the wrong cdn and was blocked from changing it..

Comment (rimashah25) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: Under **_Anything Else_** section in issue: https://github.com/apache/trafficcontrol/issues/5341

Comment (rimashah25) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: I'll change it. and make it immutable only if DS has ssl key.

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:174]: yeah, i guess that was a bad assumption on my part. I _think_ if a ds has no ssl keys, then changing the cdn and/or routing name is perfectly fine.

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go (hunk 1 above)
Comment (rimashah25) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:1021]: Done.

**Comment by mitchell852** [comment]
> > do u want to create an api test that attempts to change the cdn of a ds and ensure that a 400 is returned?
> 
> I'll add one. That is a good idea.

actually, only a ds WITH ssl keys should return a 400 when cdn and/or routing name is changed right? not sure how you'll know if it has ssl keys as the api framework is not hooked into riak...

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.anyMap.tpl.html [hunk 3]
```diff
@@ -156,7 +156,7 @@ <h3>Current Value</h3>
                         </div>
                         </label>
                         <div class="col-md-10 col-sm-10 col-xs-12">
-                            <select id="cdn" name="cdn" class="form-control" ng-model="deliveryService.cdnId" ng-options="cdn.id as cdn.name for cdn in cdns" required ng-disabled="!settings.isNew">
+                            <select id="cdn" name="cdn" class="form-control" ng-model="deliveryService.cdnId" ng-options="cdn.id as cdn.name for cdn in cdns" required>
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.anyMap.tpl.html]: do u want to disable this one?

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html [hunk 4]
```diff
@@ -746,7 +746,7 @@ <h3>Current Value</h3>
                         </label>
                         <div class="col-md-10 col-sm-10 col-xs-12">
                             <small class="input-warning" ng-show="!settings.isNew && routingConfig.routingName.$dirty">Warning: Changing the routing name may require SSL certificates to be updated.</small>
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:748]: you can get rid of these warnings on all the routing name fields that should no longer be relevant

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go [hunk 5]
```diff
@@ -1017,8 +1025,8 @@ func updateV31(w http.ResponseWriter, r *http.Request, inf *api.APIInfo, dsV31 *
 		}
 	}
 
-	if newDSType.HasSSLKeys() && (oldHostName != newHostName || oldCDNName != newCDNName || oldRoutingName != *ds.RoutingName) {
-		return nil, http.StatusBadRequest, errors.New("delivery service CDN is immutable"), errors.New("delivery service has ssl keys that cannot be automatically changed")
+	if newDSType.HasSSLKeys() && exists && (oldHostName != newHostName || oldCDNName != newCDNName || oldRoutingName != *ds.RoutingName) {
```
Comment (mitchell852) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:1028]: kind of confused why `newDSType.HasSSLKeys()` is not enough to determine if ssl keys exist or not for this ds...

Comment (mitchell852) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:1028]: to me this looks like "if has key and keys exist and....". seems redundant.

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go [hunk 6]
```diff
@@ -851,11 +851,19 @@ func updateV31(w http.ResponseWriter, r *http.Request, inf *api.APIInfo, dsV31 *
...
 		oldHostName, oldCDNName, oldRoutingName, userErr, sysErr, errCode = getOldDetails(*ds.ID, tx)
 		if userErr != nil || sysErr != nil {
 			return nil, errCode, userErr, sysErr
 		}
+		exists, err = GetSSLVersion(*ds.XMLID, tx)
+		if err != nil {
+			return nil, http.StatusInternalServerError, nil, fmt.Errorf("querying delivery service failed: %s", err)
+		}
+		if exists {
+			return nil, http.StatusBadRequest, errors.New("delivery service has ssl keys that cannot be automatically changed, therefore CDN and routing name are immutable"), nil
```
Comment (mitchell852) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go:865]: i'm confused why this error is being called twice. here and on line 1029

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.anyMap.tpl.html (hunk 3 above)
Comment (rimashah25) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.anyMap.tpl.html]: Nope, since SSLkeys are part of only 3 services: HTTP, DNS and Steering

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html (hunk 4 above)
Comment (rimashah25) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html:748]: Aha.. that makes sense.., i'll do that.

**Review by shamrickus — APPROVED** [review]
LGTM 
* GHA issues are transient and unrelated
