### PR TITLE
Fixed create regions accepts mismatch values for divisionName

### LINKED ISSUE #5562: POST request to /api/3.0/regions accepts mismatch values for divisionName
## I'm submitting a ...

-  bug report
 

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

When you make a POST request to /regions endpoint in API 3.0, if you pass in the body with id from one division ("division": 1 for Eastern division) and name from another division ("divisionName": "Western"), you get a successful response. 

## Expected behavior:

Request with mismatch ID and name would fail or divisionName could be dynamically named based on ID (I believe we do this already).

## Minimal reproduction of the problem with instructions:

all existing divisions
```
{
    "response": [
        {
            "id": 5,
            "lastUpdated": "2021-02-22 21:02:57+00",
            "name": "Ash-test"
        },
        {
            "id": 1,
            "lastUpdated": "2021-02-20 01:51:09+00",
            "name": "Eastern"
        },
        {
            "id": 2,
            "lastUpdated": "2021-02-20 01:51:10+00",
            "name": "Western"
        }
    ]
}
```
POST body --- request made to /regions, with Western ID and divisionName : Eastern
```
{
    "name": "test-abc",
    "division": 2,
    "divisionName": "Eastern"
}
```
response
```
{
    "alerts": [
        {
            "text": "region was created.",
            "level": "success"
        }
    ],
    "response": {
        "divisionName": "Eastern",
        "division": 2,
        "id": 8,
        "lastUpdated": "2021-02-22 21:37:31+00",
        "name": "test-abc"
    }
}
```

## Anything else:

When checked the region that we created with mismatch, the divisionName was correct in the DB. So, I also tried the request without the divisionName in body and that was successful. Notice the divisionName is empty in response will validate that the DB shows the right divisionName

```
req body
{
    "name": "test-123",
    "division": 7
}
response 
{
    "alerts": [
        {
            "text": "region was created.",
            "level": "success"
        }
    ],
    "response": {
        "divisionName": "",
        "division": 7,
        "id": 10,
        "lastUpdated": "2021-02-22 21:47:24+00",
        "name": "test-123"
    }
}
```

### PR DESCRIPTION
**Pull request by dmohan001c**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5562   

This fixes the create regions accepts and returns mismatch values.
POST  /regions
## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Traffic Control Client 
- Traffic Ops
- CI tests

## What is the best way to verify this PR?
Execute all the Integration tests and make sure the tests are passed.

## If this is a bug fix, what versions of Traffic Control are affected?
* Master

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/region/regions.go [hunk 1]
```diff
@@ -116,8 +117,38 @@ JOIN division d ON r.division = d.id ` + where + orderBy + pagination +
...
+
+	var divisionName string
+	var id int
+	var lastUpdated tc.TimeNoMod
+
+	rowsAffected := 0
+	for resultRows.Next() {
+		rowsAffected++
+		if err = resultRows.Scan(&id, &lastUpdated, &divisionName); err != nil {
+			return nil, fmt.Errorf("could not scan after insert: %s\n)", err), http.StatusInternalServerError
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/region/regions.go:136]: Error strings should not contain newlines, also this should wrap `err` using `%w` instead of coercing it to a string with `%s`

File: traffic_ops/traffic_ops_golang/user/user.go [hunk 2]
```diff
@@ -36,7 +36,7 @@ import (
 	"github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/tenant"
 	"github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/util/ims"
 
-	"github.com/go-ozzo/ozzo-validation"
+	validation "github.com/go-ozzo/ozzo-validation"
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/user/user.go:39]: I don't think this PR needs to touch this file

Comment (dmohan001c) [reply traffic_ops/traffic_ops_golang/user/user.go]: removed.

File: traffic_ops/traffic_ops_golang/region/regions.go (hunk 1 above)
Comment (dmohan001c) [reply traffic_ops/traffic_ops_golang/region/regions.go]: removed the new line and updated %w.

**Comment by ocket8888** [comment]
I'm still seeing a mismatch between the `divisionName` and `division` properties in the POST response. Given the divisions:
```json
[
	{
		"id": 2,
		"lastUpdated": "2021-09-15 13:23:50+00",
		"name": "Quebec"
	},
	{
		"id": 1,
		"lastUpdated": "2021-09-15 13:23:50+00",
		"name": "USA"
	}
]

```
I made a POST request to `/regions` like so:
```http
POST /api/3.0/regions HTTP/1.1
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Cookie: mojolicious=...
Content-Length: 62

{"divisionName": "Quebec", "division": 1, "name": "testquest"}
```
Note that `divisionName` is the name of a Division with the ID `2`, and the name of the Division with ID `1` is `USA`. Now the response:
```http
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Permissions-Policy: interest-cohort=()
Set-Cookie: mojolicious=...; Path=/; Expires=Wed, 15 Sep 2021 14:28:06 GMT; Max-Age=3600; HttpOnly
Vary: Accept-Encoding
X-Server-Name: traffic_ops_golang/
Date: Wed, 15 Sep 2021 13:28:06 GMT
Content-Length: 166

{
        "alerts": [
                {
                        "text": "region was created.",
                        "level": "success"
                }
        ],
        "response": {
                "divisionName": "Quebec",
                "division": 1,
                "id": 3,
                "lastUpdated": "2021-09-15 13:28:06+00",
                "name": "testquest"
        }
}
```
It still repeats what I put in, even though it's incorrect. A later request reveals the Region's *actual* `divisionName`:
```http
GET /api/3.0/regions?id=3 HTTP/1.1
User-Agent: python-requests/2.26.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Cookie: mojolicious=...
```
```http
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Permissions-Policy: interest-cohort=()
Set-Cookie: mojolicious=...; Path=/; Expires=Wed, 15 Sep 2021 14:35:47 GMT; Max-Age=3600; HttpOnly
Vary: Accept-Encoding
X-Server-Name: traffic_ops_golang/
Date: Wed, 15 Sep 2021 13:35:47 GMT
Content-Length: 128

{
        "response": [
                {
                        "divisionName": "USA",
                        "division": 1,
                        "id": 3,
                        "lastUpdated": "2021-09-15 13:28:06+00",
                        "name": "testquest"
                }
        ]
}
```

**Review by ocket8888 — APPROVED** [review]
