### PR TITLE
Removing v5 client methods for Delivery Service Required Capabilities

### LINKED ISSUE #7801: API v5 client.CreateDeliveryServicesRequiredCapability 404s
## This Bug Report affects these Traffic Control components:

- Traffic Control Client - Go library
- Traffic Ops - v5 API tests
- CDN in a Box - enroller, Traffic Ops data

## What did you do?

The enroller tried to create a DS required capability using `client.CreateDeliveryServicesRequiredCapability` (in API v5)

## What did you expect to happen?

Capability is created

## What actually happened?

```
error creating Delivery Services Required Capability: error requesting Traffic Ops: path 'https://trafficops.infra.ciab.test:443/api/5.0/deliveryservices_required_capabilities' gave HTTP error 404 Not Found - error-level alerts: The requested path '/api/5.0/deliveryservices_required_capabilities' does not exist.
```

It was removed from API v5 in #7224, so these client methods should be removed:
`CreateDeliveryServicesRequiredCapability`
`DeleteDeliveryServicesRequiredCapability`
`GetDeliveryServicesRequiredCapabilities`

And the places using them should be updated use Delivery Services directly.

```
infrastructure/cdn-in-a-box/enroller/enroller.go
traffic_ops/testing/api/v5/deliveryservices_required_capabilities_test.go
```

### PR DESCRIPTION
**Pull request by srijeet0406**
This PR closes #7801 
This PR removes unneeded client methods for Delivery Service Required Capabilities.
<hr/>

## Which Traffic Control components are affected by this PR?

- Documentation
- Traffic Control Client Golang
- Traffic Ops
- CDN in a Box

## What is the best way to verify this PR?

Make sure CDN in a box builds and functions as expected.
Make sure all the tests pass.

## If this is a bugfix, which Traffic Control versions contained the bug?

- master

## PR submission checklist
- [x] This PR has tests 
- [ ] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

File: traffic_ops/testing/api/v5/withobjs_test.go [hunk 1]
```diff
@@ -89,44 +89,44 @@ type TCObjFuncs struct {
...
+	CDNs:                           {CreateTestCDNs, DeleteTestCDNs},
+	CDNLocks:                       {CreateTestCDNLocks, DeleteTestCDNLocks},
+	CDNNotifications:               {CreateTestCDNNotifications, DeleteTestCDNNotifications},
+	CDNFederations:                 {CreateTestCDNFederations, DeleteTestCDNFederations},
+	Coordinates:                    {CreateTestCoordinates, DeleteTestCoordinates},
+	DeliveryServices:               {CreateTestDeliveryServices, DeleteTestDeliveryServices},
+	DeliveryServicesRegexes:        {CreateTestDeliveryServicesRegexes, DeleteTestDeliveryServicesRegexes},
+	DeliveryServiceRequests:        {CreateTestDeliveryServiceRequests, DeleteTestDeliveryServiceRequests},
+	DeliveryServiceRequestComments: {CreateTestDeliveryServiceRequestComments, DeleteTestDeliveryServiceRequestComments},
+	//DeliveryServicesRequiredCapabilities: {CreateTestDeliveryServicesRequiredCapabilities, DeleteTestDeliveryServicesRequiredCapabilities},
```
Comment (rimashah25) [inline traffic_ops/testing/api/v5/withobjs_test.go:104]: Why is this commented?

**Review by rimashah25 — CHANGES_REQUESTED** [review]

File: traffic_ops/testing/api/v5/withobjs_test.go (hunk 1 above)
Comment (srijeet0406) [reply traffic_ops/testing/api/v5/withobjs_test.go:104]: ah should have been removed
