### PR TITLE
Fix Traffic Monitor Log Spam

### LINKED ISSUE #5306: TM repeatedly logging events for ADMIN_DOWN caches
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Monitor

## Current behavior:
If a cache is `ADMIN_DOWN`, it appears that TM will log an event for the cache every single time it is polled:
```
1605800485.067 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv4) ADMIN_DOWN - available (health) "
1605800487.140 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv6) ADMIN_DOWN - available (health) "
1605800489.045 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv4) ADMIN_DOWN - available (health) "
1605800489.977 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv6) ADMIN_DOWN - available (stat) "
1605800490.857 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv6) ADMIN_DOWN - available (health) "
```

## Expected behavior:
Before 5.0.x, TM would not repeatedly log events for `ADMIN_DOWN` caches every time they were polled. I believe TM should only be logging events for changes in availability, which is how it has always logged events. Since `ADMIN_DOWN` caches are always unavailable for routing, these events should not be logged.

## Minimal reproduction of the problem with instructions:
Set a cache to `ADMIN_DOWN`, snapshot, observe TM event logs.

## Anything else:
This appears to affect version 5.0.x/master, compared to 4.1.x.

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #5306 

## Which Traffic Control components are affected by this PR?
- Traffic Monitor

## What is the best way to verify this PR?
Start CDN-in-a-Box, set one (or more, if you like) cache server to ADMIN_DOWN, notice that only the availability change is logged, not every time it's polled.

## If this is a bug fix, what versions of Traffic Control are affected?
- master
- 5.0.x (RC1)

## The following criteria are ALL met by this PR
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -65,6 +65,10 @@ local.tar.gz
 .projectile
 *.bak
 *.iml
+.anjuta/
+.anjuta_sym_db.db
+*.anjuta
+*.kateproject
```
Comment (shamrickus) [inline .gitignore:71]: What are these for?

File: traffic_monitor/health/cache.go [hunk 2]
```diff
@@ -322,7 +327,7 @@ func CalcAvailability(
 			Ipv6Available: availStatus.Available.IPv6,
 		})
 
-		if available, ok := localStates.GetCache(tc.CacheName(result.ID)); !ok || !available.IsAvailable || !availStatus.ProcessedAvailable {
```
Comment (shamrickus) [inline traffic_monitor/health/cache.go:325]: Originally this was `available.IsAvailable != availStatus.ProcessedAvailable` (4.1). I think it should use that instead of `lastStatus`.
I'm not seeing a log entry when going from ADMIN_DOWN -> ONLINE and I assume this is the reason.

**Review by shamrickus — CHANGES_REQUESTED** [review]

File: traffic_monitor/health/cache.go (hunk 2 above)
Comment (ocket8888) [reply traffic_monitor/health/cache.go:325]: `available` no longer exists

Comment (shamrickus) [reply traffic_monitor/health/cache.go:325]: I am now seeing it from that path - which is to say you are correct

**Review by shamrickus — APPROVED** [review]
LGTM
* Fixes log pollution
