### PR TITLE
fixed nil exception in cert autorenewal

### LINKED ISSUE #4480: POST request to /letsencrypt/autorenew results in traffic ops failure
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `POST` request to `letsencrypt/autorenew` (empty request body) results in traffic ops failing with the following status:
```
Mar 10 20:24:11 ...: panic: runtime error: invalid memory address or nil pointer dereference
Mar 10 20:24:11 ...: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa8926c]
Mar 10 20:24:11 ...: goroutine 239953 [running]:
Mar 10 20:24:11 ...: github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/deliveryservice.RunAutorenewal(0xc0010f4080, 0x3, 0x4, 0xc000196480, 0xee6700, 0xc000c99a40, 0xc00109f950)
Mar 10 20:24:11 ...: /tmp/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/deliveryservice/autorenewcerts.go:194 +0x29c
Mar 10 20:24:11 ...: created by github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/deliveryservice.RenewCertificates
Mar 10 20:24:11 ...: /tmp/go/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/deliveryservice/autorenewcerts.go:92 +0x4a7
```
## Expected / new behavior:

Should not bring down traffic ops

### PR DESCRIPTION
**Pull request by mattjackson220**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4480 

This PR fixes a bug that results in a nil exception in the certificate autorenewal script.

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

ensure that SMTP is enabled and lets_encrypt send_expiration_email is enabled
update the html template to be invalid or non-existent (/opt/traffic_ops/app/templates/send_mail/autorenewcerts_mail.html)
POST to the /letsencrypt/autorenew endpoint
verify that an error starting with "cert autorenewal: sending email: errCode:" is logged successfully and a nil exception is not thrown

## The following criteria are ALL met by this PR

No tests, docs, CHANGELONG, or database migration are necessary since this is a small bug fix.

- [x] This PR does not require tests
- [x] This PR does not require documentation
- [x] This PR does not require an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/deliveryservice/autorenewcerts.go [hunk 1]
```diff
@@ -190,8 +190,12 @@ func RunAutorenewal(existingCerts []ExistingCerts, cfg *config.Config, ctx conte
 
 	if cfg.SMTP.Enabled && cfg.ConfigLetsEncrypt.SendExpEmail {
 		errCode, userErr, sysErr := AlertExpiringCerts(keysFound, *cfg)
-		if userErr != nil || sysErr != nil {
-			log.Errorf("cert autorenewal: sending email: errCode: %d userErr: %s sysErr: %s", errCode, userErr.Error(), sysErr.Error())
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/deliveryservice/autorenewcerts.go]: you could instead just change the format options for errors to `%v` and get rid of the method call to `error.Error`:
```go
log.Errorf("cert autorenewal: sending email: errCode: %d userErr: %v sysErr: %v", errCode, userErr, sysErr)

Comment (mattjackson220) [reply traffic_ops/traffic_ops_golang/deliveryservice/autorenewcerts.go]: well thats a lot easier. done
