### PR TITLE
Generate a self signed cert on ds creation/update

### LINKED ISSUE #5893: Snapshotting a CDN that has an HTTPS delivery service w/ no cert causes TR crconfig reload failure
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Router

## Current behavior:
TR will not load a snapshot that has an HTTPs delivery service with a missing cert, therefore, TR will be stuck with an old snapshot until the problem is resolved and a cert is created for the HTTPS ds or the HTTPS ds is switched to HTTP.

## Expected behavior:
Prevent the creation of an invalid snapshot or TR should handle invalid snapshots more gracefully. 

## Minimal reproduction of the problem with instructions:
- Create a delivery service with protocol=HTTPS. Do NOT add a cert to the delivery service.
- snapshot the cdn for the delivery service
- TR will not reload the new snapshot due to the missing cert

## Anything else:
Possible solutions:
1. when snapshotting a cdn via the api, return 400 if any of the cdn's https delivery services are missing a cert.
2. [auto-generate a self-signed cert](https://github.com/apache/trafficcontrol/issues/2429) when creating an https ds or updating an http ds to an https ds.
3. TR could somehow filter out the bad ds's and consume the rest of the snapshot?

### PR DESCRIPTION
**Pull request by mattjackson220**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5893  

This PR updates TO so that when a new HTTPS delivery service is created or an HTTP delivery service is updated to HTTPS, a self signed certificate is created as a placeholder.

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Create a new HTTPS DS and verify that a self signed certificate is generated and stored
Create an HTTP DS and verify that no cert is generated
Update that HTTP DS to use HTTPS and verify that a self signed cert is generated and stored
Update an existing HTTPS DS that already has a cert and verify that the previous cert remains unchanged
Verify that all other DS creation / update functionality is unchanged

## The following criteria are ALL met by this PR

This test does not include docs or tests since it is a minor change that will not impact these
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go [hunk 1]
```diff
@@ -115,3 +118,70 @@ func generatePutRiakKeys(req tc.DeliveryServiceGenSSLKeysReq, tx *sql.Tx, tv tra
...
+		DeliveryServiceSSLKeysReq: tc.DeliveryServiceSSLKeysReq{
+			CDN:             &cdnNameStr,
+			DeliveryService: ds.XMLID,
+			HostName:        &hostname,
+			Key:             ds.XMLID,
+			Version:         &version,
+			BusinessUnit:    util.StrPtr("Placeholder"),
+			City:            util.StrPtr("Placeholder"),
+			Organization:    util.StrPtr("Placeholder"),
+			Country:         util.StrPtr("United States (US)"),
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go:165]: Does "Placeholder" not work for country and state? If not, disregard :)

File: traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go [hunk 2]
```diff
@@ -115,3 +118,70 @@ func generatePutRiakKeys(req tc.DeliveryServiceGenSSLKeysReq, tx *sql.Tx, tv tra
...
+	}
+
+	cdnNameStr := string(cdnName)
+
+	if ds.ExampleURLs == nil {
+		ds.ExampleURLs = MakeExampleURLs(ds.Protocol, *ds.Type, *ds.RoutingName, *ds.MatchList, cdnDomain)
+	}
+
+	hostname := strings.Split(ds.ExampleURLs[0], "://")[1]
+	if strings.Contains(ds.Type.String(), "HTTP") {
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go:149]: I think we may be able to change this to `if ds.Type.IsHTTP()`

**Review by rawlinp — CHANGES_REQUESTED** [review]

File: traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go [hunk 3]
```diff
@@ -87,9 +90,9 @@ func GenerateSSLKeys(w http.ResponseWriter, r *http.Request) {
 	api.WriteResp(w, r, "Successfully created ssl keys for "+*req.DeliveryService)
 }
 
-// generatePutRiakKeys generates a certificate, csr, and key from the given request, and insert it into the Riak key database.
+// GeneratePutRiakKeys generates a certificate, csr, and key from the given request, and insert it into the Riak key database.
 // The req MUST be validated, ensuring required fields exist.
-func generatePutRiakKeys(req tc.DeliveryServiceGenSSLKeysReq, tx *sql.Tx, tv trafficvault.TrafficVault, ctx context.Context) error {
+func GeneratePutRiakKeys(req tc.DeliveryServiceGenSSLKeysReq, tx *sql.Tx, tv trafficvault.TrafficVault, ctx context.Context) error {
```
[the remark this answers is not in the document]
Comment (mattjackson220) [reply traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go:95]: my bad. leftover from when i had the `GeneratePlaceHolderSelfSignedCert` in a different file. fixed

File: traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go [hunk 4]
```diff
@@ -115,3 +118,70 @@ func generatePutRiakKeys(req tc.DeliveryServiceGenSSLKeysReq, tx *sql.Tx, tv tra
...
+// GeneratePlaceholderSelfSignedCert generates a self-signed SSL certificate as a placeholder when a new HTTPS
+// delivery service is created or an HTTP delivery service is updated to use HTTPS.
+func GeneratePlaceholderSelfSignedCert(ds tc.DeliveryServiceV40, inf *api.APIInfo, context context.Context) (error, int) {
+	version := util.JSONIntStr(1)
+
+	db, err := api.GetDB(context)
+	if err != nil {
+		return err, http.StatusInternalServerError
+	}
+	tx, err := db.Begin()
```
[the remark this answers is not in the document]
Comment (mattjackson220) [reply traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go:131]: i think it will after the switch to using `createV40` and `updateV40` so ill get rid of this

File: traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go (hunk 1 above)
Comment (mattjackson220) [reply traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go:165]: haha i think it will work but it felt weird. updated now

**Review by rawlinp — COMMENTED** [review]
Code looks good, and manual testing confirms the certs are created as expected. Should we add TO API tests to check for the cert creation? It would probably need to be wrapped in `if includeSystemTests`.

Also, I can't tell if the TO API tests and TP tests are failing due to this PR. I've rerun them a few times, but they seem to be consistent.

**Comment by smalenfant** [comment]
Would there be a way to configure these so the CSR is valid to use after being auto-generated? That would mean new configuration.

```
			BusinessUnit:    util.StrPtr("Placeholder"),
			City:            util.StrPtr("Placeholder"),
			Organization:    util.StrPtr("Placeholder"),
			Country:         util.StrPtr("Placeholder"),
			State:           util.StrPtr("Placeholder"),
```

**Comment by rawlinp** [comment]
I like that idea. Just make the new config optional and use `placeholder` by default 👍

**Comment by jhg03a** [comment]
Closes #2429

File: traffic_ops/traffic_ops_golang/config/config.go [hunk 5]
```diff
@@ -173,6 +174,14 @@ type ConfigAcmeAccount struct {
 	HmacEncoded  string `json:"hmac_encoded"`
 }
 
+type DefaultCertificateInfo struct {
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/config/config.go:177]: Can we add some config validation to ensure that if the config contains the `default_certificate_info` section, that all the fields within it are non-empty? I'm not sure if that would cause the certificate generation to fail or not, but I'd think if there were any empty fields that it would be unintentional.

File: traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/deliveryservice/sslkeys.go:124]: So I think this went back and forth, but are we not able to use `inf.Tx.Tx` here? It seems like maybe there was a missing nil pointer check that ended up fixing the tests?

**Review by rawlinp — CHANGES_REQUESTED** [review]

**Review by rawlinp — APPROVED** [review]
Code looks good, and TO generated a cert on DS create (with https enabled) and update (from http to https) as expected.
