### PR TITLE
CIAB: add sanity checks around x509 file existence

### LINKED ISSUE #3769: CIAB certificate addition issues causes infinite loop on startup
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [x] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When starting up CIAB, sometimes it gets stuck in a loop where it continually calls the TO API with empty cert input:
```
trafficops_1       | ++ to-post api/1.4/deliveryservices/sslkeys/add '{
trafficops_1       |   "cdn": "CDN-in-a-Box",
trafficops_1       |   "certificate": {
trafficops_1       |     "crt": "",
trafficops_1       |     "csr": "",
trafficops_1       |     "key": ""
trafficops_1       |   },
trafficops_1       |   "deliveryservice": "demo1",
trafficops_1       |   "hostname": "*.demo1.mycdn.ciab.test",
trafficops_1       |   "key": "demo1",
trafficops_1       |   "version": 1
trafficops_1       | }'
trafficops_1       | ++ local t
trafficops_1       | ++ local data
trafficops_1       | ++ [[ -z {
trafficops_1       |   "cdn": "CDN-in-a-Box",
trafficops_1       |   "certificate": {
trafficops_1       |     "crt": "",
trafficops_1       |     "csr": "",
trafficops_1       |     "key": ""
trafficops_1       |   },
trafficops_1       |   "deliveryservice": "demo1",
trafficops_1       |   "hostname": "*.demo1.mycdn.ciab.test",
trafficops_1       |   "key": "demo1",
trafficops_1       |   "version": 1
trafficops_1       | } ]]
trafficops_1       | ++ [[ -f {
trafficops_1       |   "cdn": "CDN-in-a-Box",
trafficops_1       |   "certificate": {
trafficops_1       |     "crt": "",
trafficops_1       |     "csr": "",
trafficops_1       |     "key": ""
trafficops_1       |   },
trafficops_1       |   "deliveryservice": "demo1",
trafficops_1       |   "hostname": "*.demo1.mycdn.ciab.test",
trafficops_1       |   "key": "demo1",
trafficops_1       |   "version": 1
trafficops_1       | } ]]
trafficops_1       | +++ mktemp
trafficops_1       | ++ t=/tmp/tmp.g9weCBLU2B
trafficops_1       | ++ echo '{' '"cdn":' '"CDN-in-a-Box",' '"certificate":' '{' '"crt":' '"",' '"csr":' '"",' '"key":' '""' '},' '"deliveryservice":' '"demo1",' '"hostname":' '"*.demo1.mycdn.ciab.test",' '"key":' '"demo1",' '"version":' 1 '}'
trafficops_1       | ++ data='--data @/tmp/tmp.g9weCBLU2B'
trafficops_1       | ++ to-auth
trafficops_1       | ++ [[ -z https://trafficops.infra.ciab.test:443 ]]
trafficops_1       | ++ [[ -z admin ]]
trafficops_1       | ++ [[ -z twelve ]]
trafficops_1       | ++ cookie_current /tmp/tmp.aO15EzejCT
trafficops_1       | ++ local cookiefile=/tmp/tmp.aO15EzejCT
trafficops_1       | ++ [[ -s /tmp/tmp.aO15EzejCT ]]
trafficops_1       | +++ awk '/mojolicious/ {print $5}' /tmp/tmp.aO15EzejCT
trafficops_1       | +++ tail -n 1
trafficops_1       | ++ exp=1564721547
trafficops_1       | +++ date +%s
trafficops_1       | ++ cur=1564700655
trafficops_1       | ++ ((  1564721547 > 1564700655  ))
trafficops_1       | ++ return
trafficops_1       | ++ curl -k -LfsS -H 'Content-Type: application/json;charset=UTF-8' --cookie /tmp/tmp.aO15EzejCT -X POST --data @/tmp/tmp.g9weCBLU2B https://trafficops.infra.ciab.test:443/api/1.4/deliveryservices/sslkeys/add
edge_1             | + to-get api/1.3/cdns/name/CDN-in-a-Box/sslkeys
edge_1             | + to-auth
edge_1             | + [[ -z https://trafficops.infra.ciab.test:443 ]]
edge_1             | + [[ -z admin ]]
edge_1             | + [[ -z twelve ]]
edge_1             | + cookie_current /tmp/tmp.3SLWasQmrd
edge_1             | + local cookiefile=/tmp/tmp.3SLWasQmrd
edge_1             | + [[ -s /tmp/tmp.3SLWasQmrd ]]
trafficops_1       | INFO: routing.go:196: 2019-08-01T23:04:16.05390824Z: POST /api/1.4/deliveryservices/sslkeys/add handling (reqid 2440)
edge_1             | ++ awk '/mojolicious/ {print $5}' /tmp/tmp.3SLWasQmrd
trafficops_1       | DEBUG: plugin.go:178: 2019-08-01T23:04:16.05414433Z: DEBUG plugins.OnRequest calling 0 plugins
edge_1             | ++ tail -n 1
trafficops_1       | DEBUG: api.go:134: 2019-08-01T23:04:16.056513174Z: parsing request: validating: missing fields: certificate.key required; certificate.crt required; certificate.csr required
```
In the past, it's been thought that simply running `docker-compose down -v` to remove the created volumes and `rm -r traffic_ops/ca` to remove that directory should be enough to prevent this loop from occurring, but that doesn't seem to work for me every time. 

## Expected / new behavior:

When starting up CIAB, it should not get stuck in an endless loop of attempting to add empty certs via the TO API. 

## Minimal reproduction of the problem with instructions:

`docker-compose -f docker-compose.yml up --build` then if it does *not* get stuck in that loop above, ctrl-c the terminal, then run `docker-compose -f docker-compose.yml down` followed by `docker-compose -f docker-compose.yml up --build` again. It's likely to get stuck in the same loop.

## Anything else:

Though it might not be the cause, https://github.com/apache/trafficcontrol/pull/3489 fixed some other related things, so it might be a good place to dive into for fixing this issue.

### PR DESCRIPTION
**Pull request by rawlinp**
## What does this PR (Pull Request) do?

There is a race condition around the readability/existence of generated
certs and attempting to add them into TO. This adds some sanity checks
aorund the existence of delivery service x509 env vars and file
existence and sets the X509_GENERATION_COMPLETE env var only after all
the delivery service sslkeys have been genereated.

- [x] This PR fixes #3769 

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

Build and start CIAB, stop it, delete the `traffic_ops/ca` dir and `docker-compose down -v`, and start it again. Verify that it starts up properly.

## If this is a bug fix, what versions of Traffic Control are affected?

- master

## The following criteria are ALL met by this PR

- [x] This is CIAB, no tests necessary
- [x] Minor bugfix, no docs necessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/4093/
Test PASSed.

File: infrastructure/cdn-in-a-box/traffic_ops/run-go.sh [hunk 1]
```diff
@@ -87,6 +87,12 @@ while true; do
 done
 
 ### Add SSL keys for demo1 delivery service
+until [[ -s "$X509_DEMO1_CERT_FILE" && -s "$X509_DEMO1_REQUEST_FILE" && -s "$X509_DEMO1_KEY_FILE" ]]
+do
+  echo "Waiting on X509_DEMO1 files to exist"
+  sleep 3
```
Comment (lbathina) [inline infrastructure/cdn-in-a-box/traffic_ops/run-go.sh]: would result in possible infinite loop if the file did not exist for some reason. its better to loop for certain duration or until the file exists.

Comment (ocket8888) [reply infrastructure/cdn-in-a-box/traffic_ops/run-go.sh]: That's true, but because the processes are totally asynchronous there's know way to know for an arbitrary host what a reasonable timeout would be.

Comment (rob05c) [reply infrastructure/cdn-in-a-box/traffic_ops/run-go.sh]: Moreover, I think we really do want to loop forever, for things required for initialization. If the Docker container can't proceed without this, looping forever and continuously logging what's being waited on makes it easier to debug what went wrong.

Comment (rawlinp) [reply infrastructure/cdn-in-a-box/traffic_ops/run-go.sh]: Yeah, the general async architecture of CIAB tends to require waiting on things indefinitely. That can be frustrating sometimes though, because it's not always clear how long CIAB is "supposed to take" in order to fully startup, and it's not immediately obvious when CIAB has actually started up properly from the logs.

That said, this PR jives w/ the existing architecture, and if we to change the architecture, we should discuss/design that in a more open forum.
