### PR TITLE
Prevents line breaks in delivery service remapText field (UI and API)

### LINKED ISSUE #4298: Line breaks in DS raw remap text will result in a malformed remap.config file
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
When creating or editing a delivery service of type HTTP*, DNS* or ANY_MAP, a line break in the `remapText` field will result in a malformed remap.config file being deployed to all of the edge caches assigned to the delivery service which can have a negative impact across multiple delivery services (if multiple delivery services are assigned to the cache).

When remapText = foo[line break]bar, the applicable line in remap.config will look like this:

```
map	http://edge.demo1.mycdn.ciab.test/     http://origin.infra.ciab.test/  foo
bar
map	http://edge.demo2.mycdn.ciab.test/     http://origin2.infra.ciab.test/
```

## Expected / new behavior:
On API DS create/update, any line breaks in the `remapText` field need to be removed.

## Minimal reproduction of the problem with instructions:
1. In TP, create or edit an HTTP*, DNS* or ANY_MAP delivery service and enter a line break in the `Raw Remap Text` field. Note: a textarea has been provided for readability of the `Raw Remap Text` field, however, it has the downside of allowing line breaks.
2. Navigate to the assigned servers for DS. Pick one.
3. View config files for the server.
4. View the contents of remap.config file and notice the line that doesn't start with `map`

### PR DESCRIPTION
**Pull request by mitchell852**
## What does this PR (Pull Request) do?

Rejects delivery service remapText with line breaks as it will result in a malformed remap.config file.

- [x] This PR fixes #4298 

## Which Traffic Control components are affected by this PR?

- Traffic Ops
- Traffic Portal

## What is the best way to verify this PR?
1. Run the [UI tests](https://github.com/apache/trafficcontrol/tree/master/traffic_portal/test/end_to_end)
2. Run the API tests
3. Manually verify in TP by trying to enter a line break in the `Raw Remap Text` delivery service form field for a DNS, HTTP or ANY_MAP delivery service.
4. Attempt to create or update a delivery service using the API where remapText contains \n or \r. It should fail.

## If this is a bug fix, what versions of Traffic Control are affected?
- master (6b11bd9)
- 3.1.0
- 4.0.0 (RC1)

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/testing/api/v14/deliveryservices_test.go [hunk 1]
```diff
@@ -189,6 +190,39 @@ func UpdateNullableTestDeliveryServices(t *testing.T) {
 	}
 }
 
+// UpdateDeliveryServiceWithInvalidRemapText ensures that a delivery service can't be updated with a remap text value with a line break in it
```
Comment (ocket8888) [inline traffic_ops/testing/api/v14/deliveryservices_test.go]: nit: GoDoc missing period

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html [hunk 2]
```diff
@@ -534,7 +534,8 @@ <h3>Current Value</h3>
                         </div>
                         </label>
                         <div class="col-md-10 col-sm-10 col-xs-12">
-                            <textarea id="remapText" name="remapText" class="form-control" ng-model="deliveryService.remapText" rows="3"></textarea>
+                            <textarea id="remapText" name="remapText" class="form-control" ng-model="deliveryService.remapText" ng-pattern="/^[^\n\r]*$/" rows="3"></textarea>
```
Comment (ocket8888) [inline traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html]: if this can't have multiple lines, why not just make it an `input[type="text"]`?

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.HTTP.tpl.html [hunk 3]
```diff
@@ -534,7 +534,8 @@ <h3>Current Value</h3>
                         </div>
                         </label>
                         <div class="col-md-10 col-sm-10 col-xs-12">
-                            <textarea id="remapText" name="remapText" class="form-control" ng-model="deliveryService.remapText" rows="3"></textarea>
+                            <textarea id="remapText" name="remapText" class="form-control" ng-model="deliveryService.remapText" ng-pattern="/^[^\n\r]*$/" rows="3"></textarea>
```
Comment (ocket8888) [inline traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.HTTP.tpl.html]: same as above RE `textarea` vs `input[type="text"]`

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.anyMap.tpl.html [hunk 4]
```diff
@@ -262,7 +262,8 @@ <h3>Current Value</h3>
                         </div>
                         </label>
                         <div class="col-md-10 col-sm-10 col-xs-12">
-                            <textarea id="remapText" name="remapText" class="form-control" ng-model="deliveryService.remapText" rows="3" required></textarea>
+                            <textarea id="remapText" name="remapText" class="form-control" ng-model="deliveryService.remapText" ng-pattern="/^[^\n\r]*$/" rows="3" required></textarea>
```
Comment (ocket8888) [inline traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.anyMap.tpl.html]: and one more time

File: traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html (hunk 2 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html]: remap text gets long and i want the word wrapability of a TA.

Comment (ocket8888) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html]: Yeah, I suppose that makes sense. You _could_ make the number of rows dynamic so that it's always exactly big enough to contain its contents. But I won't make you do that to fix a bug.

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html]: textareas are stretchable so i suppose if the content goes over the 3 rows, they can stretch the TA

Comment (rawlinp) [reply traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html]: I think because it's easier to read long inputs with text-wrapping.

**Comment by mitchell852** [comment]
> The regular expression you're using isn't multi-line; `^` and `$` match the beginning and end of a line, respectively. So I can still do this:
> 
> ```js
> >> temp0.name
> <- "remapText"
> >> temp0.tagName
> <- "TEXTAREA"
> >> temp0.attributes[4]
> <- ng-pattern="/^[^\\n\\r]*$/"
> >> temp0.value
> <- "
> this is a test
> "
> >> temp0.validity.patternMismatch
> <- false
> >> temp0.classList.contains("ng-invalid")
> <- false
> >> temp0.classList.contains("ng-valid")
> <- true
> ```

well in the UI i am unable to enter anything on 2 lines so that's what i was going for

**Comment by ocket8888** [comment]
No, you still can.

Depiction of the problem

That'll get rejected by the API but the form shows no problems. According to the issue, the content of this field is:

> _"appended to the one line [in remap.config for most Delivery Services]"_

so this value would still exhibit the problem. So it ought to not be considered correct - especially since submission will result in an error.

**Comment by mitchell852** [comment]
> so this value would still exhibit the problem. So it ought to not be considered correct - especially since submission will result in an error.

hmm. i can't replicate. this submits fine in both chrome and firefox.

image

it makes it past the api so it appears to be getting trimmed.

**Comment by mitchell852** [comment]
retest this please
