### PR TITLE
GET /api/3.0/servers?dsId=1 500s when requested with If-Modified-Since header

### LINKED ISSUE #4949: GET /api/3.0/servers?dsId=1 500s when requested with If-Modified-Since header
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

`GET /api/3.0/servers?dsId=1` returns a response with an *Internal Server Error* alert and status code 500  when requested with `If-Modified-Since` header.

## Expected / new behavior:

`GET /api/3.0/servers?dsId=1` should return status code 200 with a set of servers matching the query parameter

## Minimal reproduction of the problem with instructions:

1. Start CDN-in-a-Box
2. Log into Traffic Portal
3. Visit https://trafficportal.infra.ciab.test/api/3.0/servers?dsId=1
4. Visit https://trafficportal.infra.ciab.test/api/3.0/servers?dsId=1 again, receive error

## Anything else:

Traffic Ops error log:
```go
ERROR: api.go:209: 2020-08-13T15:39:45.268410415Z: 172.16.239.8:49780 querying: pq: current transaction is aborted, commands ignored until end of transaction block
DEBUG: api.go:214: 2020-08-13T15:39:45.268428091Z: Internal Server Error
```

### PR DESCRIPTION
**Pull request by srijeet0406**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4949 

## Which Traffic Control components are affected by this PR?

- CDN in a Box
- Traffic Ops

## What is the best way to verify this PR?

Start TO locally
Make a call to get the servers associated with a ds like:
`curl -X GET -k -H "Accept: application/json" -H "If-Modified-Since: Mon, 13 Jul 2020 21:26:00 GMT" "https://localhost:8443/api/3.0/servers?dsId=3"`
This should not give you a 500 error, instead, you should see the servers associated with this DS.

## If this is a bug fix, what versions of Traffic Control are affected?

- master
## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR includes documentation
- [x] This PR does not include an update to CHANGELOG.md
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go [hunk 1]
```diff
@@ -814,7 +814,7 @@ func (dss *TODSSDeliveryService) Read(h http.Header, useIMS bool) ([]interface{}
 
 func selectMaxLastUpdatedQuery(where string) string {
 	return `SELECT max(t) from (
-		SELECT max(dss.last_updated) as t from deliveryservice_server dss ` + where +
+		SELECT max(dss.last_updated) as t from deliveryservice_server dss JOIN deliveryservice ds ON ds.id = dss.deliveryservice ` + where +
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go:817]: We don't always need this join, only when dsId is a query parameter. How is the join conditionally added to `serverCountQuery` and `selectQuery`?

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 2]
```diff
@@ -611,7 +611,8 @@ JOIN cdn cdn ON s.cdn_id = cdn.id
 JOIN phys_location pl ON s.phys_location = pl.id
 JOIN profile p ON s.profile = p.id
 JOIN status st ON s.status = st.id
-JOIN type t ON s.type = t.id ` + where +
+JOIN type t ON s.type = t.id 
+FULL OUTER JOIN deliveryservice_server dss ON dss.server = s.id ` + where +
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/server/servers.go:615]: As with the comment above, we don't always need this join, only when dsId is a query parameter.

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go (hunk 1 above)
Comment (srijeet0406) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go:817]: We will actually need this one always, because we look for the DS ID in the params and if its not present, we return there. So if it makes it to this line, we are guaranteed that we do have a delivery service id, denoted by `id` in the params.

File: traffic_ops/traffic_ops_golang/server/servers.go (hunk 2 above)
Comment (srijeet0406) [reply traffic_ops/traffic_ops_golang/server/servers.go:615]: Fixed

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go (hunk 1 above)
Comment (zrhoffman) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go:817]: I missed that this one was in a completely different file. Sounds good

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 3]
```diff
@@ -640,14 +640,15 @@ func ReadID(w http.ResponseWriter, r *http.Request) {
...
+func selectMaxLastUpdatedQuery(queryAddition string, where string) string {
 	return `SELECT max(t) from (
 		SELECT max(s.last_updated) as t from server s JOIN cachegroup cg ON s.cachegroup = cg.id
 JOIN cdn cdn ON s.cdn_id = cdn.id
 JOIN phys_location pl ON s.phys_location = pl.id
 JOIN profile p ON s.profile = p.id
 JOIN status st ON s.status = st.id
-JOIN type t ON s.type = t.id ` + where +
+JOIN type t ON s.type = t.id ` +
+queryAddition + where +
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/server/servers.go:651]: `go fmt` indents this line
