### PR TITLE
TP: adds a CSV link to all tables to enable export of table data to CSV

### LINKED ISSUE #3895: Add ability to export server data from Traffic Portal
## I'm submitting a ...
- [ ] bug report
- [x] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Currently the only way to export server data is to copy/paste it out of the portal or to use the API.  Copy/pasting does not give you the ability to control which fields you are exporting, and using the API requires some basic knowledge on scripting/writing code.  Neither of these options are great, we should provide the ability to let a user export server data.  
## Expected / new behavior:

User can export server data to csv.  Traffic Portal would allow them to choose servers from a specific CDN, Cache group, etc as well as letting the user choose which fields they want to export.  This would be useful for external groups that use the Traffic Ops data for other purposes (e.g. network monitoring)

### PR DESCRIPTION
**Pull request by mitchell852**
## What does this PR (Pull Request) do?

A 'CSV' link has been added to all tables in TP that provides the user with the ability to download the table data (with the search filter applied) in csv format. 

- [x] This PR fixes #3895 

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Navigate to any table in TP and click the 'CSV' link at the top of the table. Verify that the contents of the table are downloaded in csv format.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_portal/app/src/common/service/application/ApplicationService.js [hunk 1]
```diff
@@ -38,6 +38,10 @@ var ApplicationService = function($rootScope, $anchorScroll, $http, messageModel
 
         // jquery DataTables default overrides
         $.extend(true, $.fn.dataTable.defaults, {
+            "dom": "lfBrtip",
+            "buttons": [
+                { "extend": "csv", "className": "btn-link", "titleAttr": "Export to CSV" }
+            ],
```
Comment (ocket8888) [inline traffic_portal/app/src/common/service/application/ApplicationService.js]: Is there any way this can be changed to a download icon like <kbd>⭳</kbd> or something? Failing that, "Export as CSV" or simply "Export" would be more clear than just "CSV", IMO.

File: traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html [hunk 2]
```diff
@@ -48,8 +48,8 @@
                 <td data-search="^{{::pp.name}}$">{{::pp.name}}</td>
                 <td data-search="^{{::pp.configFile}}$">{{::pp.configFile}}</td>
                 <td data-search="^{{::pp.value}}$">{{::pp.value}}</td>
-                <td class="center" data-order="{{pp.selected1}}"><input type="checkbox" ng-change="onChange(1)" ng-class="{'dirty': isCheckboxDirty(pp, 1)}" ng-model="pp.selected1"></td>
-                <td class="center" data-order="{{pp.selected2}}"><input type="checkbox" ng-change="onChange(2)" ng-class="{'dirty': isCheckboxDirty(pp, 2)}" ng-model="pp.selected2"></td>
+                <td class="center" data-order="{{pp.selected1}}"><input type="checkbox" ng-change="onChange(1)" ng-class="{'dirty': isCheckboxDirty(pp, 1)}" ng-model="pp.selected1"><span hidden>{{pp.selected1}}</span></td>
+                <td class="center" data-order="{{pp.selected2}}"><input type="checkbox" ng-change="onChange(2)" ng-class="{'dirty': isCheckboxDirty(pp, 2)}" ng-model="pp.selected2"><span hidden>{{pp.selected2}}</span></td>
```
Comment (ocket8888) [inline traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html]: what's with the hidden span here?

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html]: it's to hide the span :P

Comment (mitchell852) [reply traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html]: it's because when the table is exported to csv, there is no value in this table cell. the export is not smart enough to figure out the value of the checkbox. instead, if i include this hidden field it is hidden from the UI but gets captured in the export.

Comment (ocket8888) [reply traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html]: > _"the export is not smart enough to figure out the value of the checkbox"_

That sounds like a dirty hack to me, but I think you'd be disinclined to write it better yourself?

File: traffic_portal/app/src/common/service/application/ApplicationService.js (hunk 1 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/service/application/ApplicationService.js]: i did try an icon and it looked kinda weird just hanging out on the top of the table. But yes, "Export as CSV" would be better. clarity is good.

File: traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html (hunk 2 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html]: it does feel hacky....but it is such a simple hack (so little code) i couldn't resist. plus, monkey patching the library felt more problematic than it's worth.

File: traffic_portal/app/src/common/service/application/ApplicationService.js (hunk 1 above)
Comment (mitchell852) [reply traffic_portal/app/src/common/service/application/ApplicationService.js]: done

File: traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html (hunk 2 above)
Comment (ocket8888) [reply traffic_portal/app/src/common/modules/table/profilesParamsCompare/table.profilesParamsCompare.tpl.html]: Oh I didn't mean patching the library, I meant using the download stuff from the utils service to make your own button.
