### PR TITLE
Better messages for Traffic Router exceptions

### LINKED ISSUE #7081: Traffic Router logs `SocketTimeoutException` for port 53 TCP health checks
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Router

## Current behavior

To ensure that a Traffic Router can handle DNSSEC requests, a common practice is for an operator to create a health check that attempts to connect to Traffic Router over TCP on port 53, and, once successfully connected, close the request. When this happens, the following stack trace shows up in `traffic_router.log`:

```java
ERROR 2022-09-21T18:44:42.289 [pool-13-thread-1] org.apache.traffic_control.traffic_router.core.dns.protocol.TCP - Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:388) ~[?:?]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) ~[?:?]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107) ~[?:?]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101) ~[?:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:200) ~[?:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:170) ~[?:?]
	at org.apache.traffic_control.traffic_router.core.dns.protocol.TCP$TCPSocketHandler.run(TCP.java:108) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

## New behavior

`org.apache.traffic_control.traffic_router.core.dns.protocol.TCP$TCPSocketHandler.run()` should catch `SocketTimeoutException` and give a more descriptive error (including IP address).

Also, this case is also not currently recorded in `access.log`. Do we want to log this case there?

## Steps to reproduce

1. Start CDN in a Box
2. Make an HTTP request against traffic router on port 53:
  ```
  [zrhoffman@computer cdn-in-a-box]$ docker-compose exec trafficops curl -v trafficrouter:53
  * Rebuilt URL to: trafficrouter:53/
  *   Trying fc01:9400:1000:8::f...
  * TCP_NODELAY set
  * Connected to trafficrouter (fc01:9400:1000:8::f) port 53 (#0)
  > GET / HTTP/1.1
> Host: trafficrouter:53
  > User-Agent: curl/7.61.1
  > Accept: */*
  >
  * Empty reply from server
  * Connection #0 to host trafficrouter left intact
  curl: (52) Empty reply from server
  ```
3. Watch the Traffic Router logs

### PR DESCRIPTION
**Pull request by srijeet0406**
This PR closes #7081 
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Router

## What is the best way to verify this PR?

Follow the steps in #7081 
Make sure the new information shows up in the logs.

## If this is a bugfix, which Traffic Control versions contained the bug?

- master

## PR submission checklist
- [ ] This PR has tests 
- [ ] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

File: traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/dns/protocol/TCP.java [hunk 1]
```diff
@@ -112,6 +114,20 @@ public void run() {
...
             } catch (final WireParseException e) {
                 // This is already recorded in the access log
+            } catch (final SocketTimeoutException e) {
+                String hostAddress = "unknown";
+                if (client != null) {
+                    hostAddress = client.getHostAddress();
+                }
+                LOGGER.error("The socket with the Client at: " +
+                        hostAddress + " has timed out. Error: " + e.getMessage(), e);
+            } catch (final EOFException e) {
```
Comment (zrhoffman) [inline traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/dns/protocol/TCP.java:124]: Syntax error

```
core/dns/protocol/TCP.java:[124,27] error: cannot find symbol
```

File: traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/dns/protocol/TCP.java [hunk 2]
```diff
@@ -112,6 +115,20 @@ public void run() {
                 os.write(response);
             } catch (final WireParseException e) {
                 // This is already recorded in the access log
+            } catch (final SocketTimeoutException e) {
+                String hostAddress = "unknown";
+                if (client != null) {
+                    hostAddress = client.getHostAddress();
+                }
+                LOGGER.error("The socket with the Client at: " +
+                        hostAddress + " has timed out. Error: " + e.getMessage(), e);
```
Comment (zrhoffman) [inline traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/dns/protocol/TCP.java:124]: This still prints the stack trace, which we don't need in this specific case.

```java
ERROR 2022-10-19T16:17:45.535 [pool-13-thread-1] org.apache.traffic_control.traffic_router.core.dns.protocol.TCP - The socket with the Client at: 2001:3984:3989:0:0:0:0:3 has timed out. Error: Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:388) ~[?:?]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) ~[?:?]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107) ~[?:?]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101) ~[?:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:200) ~[?:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:170) ~[?:?]
	at org.apache.traffic_control.traffic_router.core.dns.protocol.TCP$TCPSocketHandler.run(TCP.java:111) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
````

In the dev CDN in a Box, ran
```shell
docker-compose exec trafficops wget -O- trafficrouter:53
```

**Review by zrhoffman — CHANGES_REQUESTED** [review]

**Review by zrhoffman — APPROVED** [review]
Looks good!
