### PR TITLE
Fixed filtering query parameters in the /servers API

### LINKED ISSUE #4795: Fix query parameter for servers API
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

1. When user perform a /GET `https://{{TO_BASE_URL}}/api/3.0/servers?type=MID` with any type like MID,EDGE ...
The API will return 500 Internal Server Error.
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
2. When user perform a /GET `https://{{TO_BASE_URL}}/api/3.0/servers?status=ONLINE` with any valid or invalid status
The API will return 500 Internal Server Error
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
3. When user perform a /GET `https://{{TO_BASE_URL}}/api/3.0/servers?parentCachegroup=1` with valid or invalid parentCachegroup number.
The API will return 500 Internal Server Error
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should return the servers with correct match

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #4795

Fixes the filtering query parameters of `/servers`.

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?
Run the API/client integration tests

Make requests that filter servers by type, cdn, cachegroup, profile, physical location, and/or status.

## If this is a bug fix, what versions of Traffic Control are affected?
- master

## The following criteria are ALL met by this PR
- [x] This PR includes tests
- [x] Documentation is unnecessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

**Comment by ocket8888** [comment]
Because finding a cache server in the test data with a parentCacheGroup is non-trivial, since it's not a server property, and dsId is currently broken for other reasons. A separate PR that fixes issues with dsId is adding a test for it (#4798).

File: traffic_ops/traffic_ops_golang/server/servers.go [hunk 1]
```diff
@@ -51,6 +51,12 @@ import (
 const serverCountQuery = `
 SELECT COUNT(s.id)
 FROM server AS s
+JOIN cachegroup cg ON s.cachegroup = cg.id
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/server/servers.go:54]: Since this is the exact same `FROM ... JOIN`s as the main `selectQuery` below, should we move this into a constant and share them between both queries?

Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/server/servers.go:54]: I don't really have an opinion, but I suppose it could help avoid something like this in the future. That's a good enough reason to do it.

File: traffic_ops/testing/api/v3/servers_test.go [hunk 2]
```diff
@@ -101,6 +97,70 @@ func GetTestServersQueryParameters(t *testing.T) {
...
+	}
+
+	if len(resp.Response) < 1 {
+		t.Fatalf("Failed to get at least one server")
+	}
+
+	s := resp.Response[0]
+
+	params.Add("type", s.Type)
+	if _, _, err := TOSession.GetServers(&params); err != nil {
```
Comment (rawlinp) [inline traffic_ops/testing/api/v3/servers_test.go:113]: nit: I'm going to merge this anyways, but if you really want to level up this testing you could iterate over the servers and verify that the response only contains the properly filtered servers

Comment (ocket8888) [reply traffic_ops/testing/api/v3/servers_test.go:113]: ... I know...
