### PR TITLE
Fixes missing deliveryservice data fields from the servers/deliveryservices endpoint.

### LINKED ISSUE #2989: TO Go api/1.1/servers/{:id}/deliveryservices missing entries
The  `api/1.1/servers/{:id}/deliveryservices` endpoint in Go is missing several entries available in the Perl version.  Some others have different values.   This is what I have observed, but may not represent all the differences depending on the content of db..

Note that some of these may be missing because they have an empty value (e.g. false for boolean)

Missing fields:
 - anonymousBlockingEnabled
 - cdnName
 - profileName
 - signed
 - tenant
 - type

These ones have different value between Perl and Go:
 - deepCachingType
 - fqPacingRate

This is also tangentially related to #2972 -- hitting the endpoint with the `.json` endpoint actually redirects to Perl,  but should not..

### PR DESCRIPTION
**Pull request by jrushford**
This PR fixes /api/servers/{id}/deliveryservices endpoint.
The fix removes a duplicate deliveryservice struct and query.
The endpoint now uses the same DeliverServiceNullable struct in
tc-go and the query from deliverservice/deliveryservcesv13.go

Also added a tenancy check.

#### What does this PR do?
Fixes #2989

#### Which TC components are affected by this PR?

- [ ] Documentation
- [ ] Grove
- [ ] Traffic Analytics
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] Other _________

#### Check all that apply

- [ ] This PR includes tests
- [ ] This PR includes documentation updates
- [ ] This PR includes an update to CHANGELOG.md
- [ ] This PR includes all required license headers
- [ ] This PR includes a database migration (ensure that migration sequence is correct)
- [ ] This PR fixes a serious security flaw. Read more: [www.apache.org/security](http://www.apache.org/security/)

Fixes #2989

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2870/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2871/
Test FAILed.

**Comment by mitchell852** [comment]
@jrushford - was there an issue for this? This sounds familiar so maybe there was.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2872/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2873/
Test FAILed.

**Comment by jrushford** [comment]
@mitchell852 I updated the PR with the issue numbe, #2989

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2876/
Test FAILed.

**Comment by jrushford** [comment]
retest please

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2890/
Test PASSed.

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go [hunk 1]
```diff
@@ -472,106 +473,85 @@ func dssSelectQuery() string {
...
+	query := deliveryservice.GetDSSelectQuery() + where + orderBy
+	queryValues["server"] = dss.APIInfo().Params["id"]
+	log.Debugln("generated deliveryServices query: " + query)
+	log.Debugf("executing with values: %++v\n", queryValues)
 
-func SDSSelectQuery() string {
+	dses, errs, _ := deliveryservice.GetDeliveryServices(query, queryValues, dss.APIInfo().Tx)
+	if len(errs) > 0 {
+		for _, err := range errs {
+			if err.Error() == `id cannot parse to integer` { // TODO create const for string
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: Does this check really need to be made again here? Is it coming from the `BuildWhereAndOrderBy` function?

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go [hunk 2]
```diff
@@ -472,106 +473,85 @@ func dssSelectQuery() string {
...
 func (dss *TODSSDeliveryService) Read() ([]interface{}, error, error, int) {
-	orderby := dss.APIInfo().Params["orderby"]
-	if orderby == "" {
-		orderby = "deliveryService"
+	returnable := []interface{}{}
+	params := make(map[string]string)
+	tx := dss.APIInfo().Tx.Tx
+	user := dss.APIInfo().User
+
+	if _, ok := params["orderby"]; !ok {
```
[the remark this answers is not in the document]
Comment (jrushford) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: oops, you're right.  I'll fix that.

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go (hunk 1 above)
Comment (jrushford) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: I'll fix it.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2899/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2900/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2901/
Test PASSed.

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go [hunk 3]
```diff
@@ -472,106 +473,85 @@ func dssSelectQuery() string {
...
+			}
+		}
+		return nil, nil, errors.New("reading dses: " + util.JoinErrsStr(errs)), http.StatusInternalServerError
 	}
 
-	query := SDSSelectQuery()
-	log.Debugln("Query is ", query)
-
-	rows, err := dss.APIInfo().Tx.Queryx(query, dss.APIInfo().Params["id"])
+	tenancyEnabled, err := tenant.IsTenancyEnabledTx(tx)
```
[the remark this answers is not in the document]
Comment (jrushford) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: made the changes to unconditionally perform tenancy checks

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go [hunk 4]
```diff
@@ -472,106 +473,85 @@ func dssSelectQuery() string {
...
+		where = "WHERE "
+	}
+	where += "ds.id in (SELECT deliveryService FROM deliveryservice_server where server = :server)"
 
-	services := []interface{}{}
-	for rows.Next() {
-		var s tc.DSSDeliveryService
-		if err = rows.StructScan(&s); err != nil {
-			return nil, nil, errors.New("dss scanning: " + err.Error()), http.StatusInternalServerError
+	if tenancyEnabled {
```
[the remark this answers is not in the document]
Comment (jrushford) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: made the change

File: traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go [hunk 5]
```diff
@@ -472,106 +473,72 @@ func dssSelectQuery() string {
...
+
+	// Query Parameters to Database Query column mappings
+	// see the fields mapped in the SQL query
+	queryParamsToSQLCols := map[string]dbhelpers.WhereColumnInfo{
+		"xml_id": dbhelpers.WhereColumnInfo{"ds.xml_id", nil},
+		"xmlId":  dbhelpers.WhereColumnInfo{"ds.xml_id", nil},
+	}
+	where, orderBy, queryValues, errs := dbhelpers.BuildWhereAndOrderBy(params, queryParamsToSQLCols)
+	if len(errs) > 0 {
+		for _, err := range errs {
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: So I don't think this for loop actually catches the error since "id" isn't in the `queryParamsToSQLCols`. But, I don't think we can really check it there since we don't have a real `WhereColumnInfo` since you're adding your own `WHERE` clause below.

I think we should just remove this for loop and add the following explicit check up to line 493 above:
```
	if err := api.IsInt(params["id"]); err != nil {
		return nil, errors.New("Resource not found."), nil, http.StatusNotFound //matches perl response
	}
```
That should make this emit the proper error when passing something like "foo" as the id in the path.

Comment (jrushford) [reply traffic_ops/traffic_ops_golang/deliveryservice/servers/servers.go]: good catch, i'll make the change

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2906/
Test FAILed.
