### PR TITLE
Use RFC 3339 for lastUpdated timestamp in /server_server_capabilities

### LINKED ISSUE #7743: /server_server_capabilities in TO API uses non-RFC3339 date/time strings
## Parent Issue: #5911

Breaking down the parent issue https://github.com/apache/trafficcontrol/issues/5911 in smaller issues to raise separate, reviewable PRs for each of the services.

## Traffic Control components affected:
- Traffic Ops
- Documentation

## Current behavior:
Statuses Using Deprecated TimeNoMod & TimeLayout

## Expected behavior:
Status  to Use RFC3339 Format

## Steps to reproduce:
`GET /api/5.0/server_server_capabilities`

### PR DESCRIPTION
**Pull request by zrhoffman**
This PR resolves #7743 by using the timestamp format specified in RFC 3339 for the `lastUpdated` field of the `/api/5.0/server_server_capabilities` endpoint.
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Run the server_server_capabilities API tests

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

File: traffic_ops/v5-client/server_server_capabilities.go [hunk 1]
```diff
@@ -31,14 +31,14 @@ const apiServerServerCapabilities = "/server_server_capabilities"
...
+// CreateServerServerCapabilityV5 assigns a Server Capability to a Server.
+func (to *Session) CreateServerServerCapability(ssc tc.ServerServerCapabilityV5, opts RequestOptions) (tc.Alerts, toclientlib.ReqInf, error) {
 	var alerts tc.Alerts
 	reqInf, err := to.post(apiServerServerCapabilities, opts, ssc, &alerts)
 	return alerts, reqInf, err
 }
 
-// DeleteServerServerCapability unassigns a Server Capability from a Server.
+// DeleteServerServerCapabilityV5 unassigns a Server Capability from a Server.
 func (to *Session) DeleteServerServerCapability(serverID int, serverCapability string, opts RequestOptions) (tc.Alerts, toclientlib.ReqInf, error) {
```
Comment (kdamichie) [inline traffic_ops/v5-client/server_server_capabilities.go:42]: `DeleteServerServerCapabilityV5` description doesn't match `DeleteServerServerCapability` func name

File: traffic_ops/v5-client/server_server_capabilities.go [hunk 2]
```diff
@@ -31,14 +31,14 @@ const apiServerServerCapabilities = "/server_server_capabilities"
 // apiMultipleServersCapabilities is the API version-relative path to the /multiple_servers_capabilities API endpoint.
 const apiMultipleServersCapabilities = "/multiple_servers_capabilities"
 
-// CreateServerServerCapability assigns a Server Capability to a Server.
-func (to *Session) CreateServerServerCapability(ssc tc.ServerServerCapability, opts RequestOptions) (tc.Alerts, toclientlib.ReqInf, error) {
+// CreateServerServerCapabilityV5 assigns a Server Capability to a Server.
+func (to *Session) CreateServerServerCapability(ssc tc.ServerServerCapabilityV5, opts RequestOptions) (tc.Alerts, toclientlib.ReqInf, error) {
```
Comment (kdamichie) [inline traffic_ops/v5-client/server_server_capabilities.go:35]: `CreateServerServerCapabilityV5` description doesn't match `CreateServerServerCapability` func name

File: traffic_ops/v5-client/server_server_capabilities.go [hunk 3]
```diff
@@ -52,8 +52,8 @@ func (to *Session) DeleteServerServerCapability(serverID int, serverCapability s
 
 // GetServerServerCapabilities retrieves a list of Server Capabilities that are
 // assigned to Servers.
-func (to *Session) GetServerServerCapabilities(opts RequestOptions) (tc.ServerServerCapabilitiesResponse, toclientlib.ReqInf, error) {
-	var resp tc.ServerServerCapabilitiesResponse
+func (to *Session) GetServerServerCapabilities(opts RequestOptions) (tc.ServerServerCapabilitiesResponseV5, toclientlib.ReqInf, error) {
+	var resp tc.ServerServerCapabilitiesResponseV5
```
Comment (kdamichie) [inline traffic_ops/v5-client/server_server_capabilities.go:56]: Suggestion: `GetServerServerCapabilities` should probably be `GetServerServerCapabilitiesV5`

File: traffic_ops/traffic_ops_golang/server/servers_server_capability.go
Comment (kdamichie) [inline traffic_ops/traffic_ops_golang/server/servers_server_capability.go:1]: Verified `v5` `servers_server_capability_test.go` DOES test the new code.

**Review by kdamichie — CHANGES_REQUESTED** [review]
Check #1 - simple changes requested

File: CHANGELOG.md [hunk 4]
```diff
@@ -102,6 +102,7 @@ The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/).
 - [#7441](https://github.com/apache/trafficcontrol/pull/7441) *Traffic Ops* Fixed the invalidation jobs endpoint to respect CDN locks.
 - [#7413](https://github.com/apache/trafficcontrol/issues/7413) *Traffic Ops* Fixes service_category apis to respond with RFC3339 date/time Format
 - [#7413](https://github.com/apache/trafficcontrol/issues/7706) *Traffic Ops* Fixes /statuses apis to respond with RFC3339 date/time format
+- [#7743](https://github.com/apache/trafficcontrol/issues/7706) *Traffic Ops* Fixes /server_server_capabilities apis to respond with RFC3339 date/time format
```
[the remark this answers is not in the document]
Comment (zrhoffman) [reply CHANGELOG.md]: Good catch, fixed!

File: traffic_ops/v5-client/server_server_capabilities.go (hunk 1 above)
Comment (zrhoffman) [reply traffic_ops/v5-client/server_server_capabilities.go]: Changed godoc to `DeleteServerServerCapability` in c2e7652089

File: traffic_ops/v5-client/server_server_capabilities.go (hunk 2 above)
Comment (zrhoffman) [reply traffic_ops/v5-client/server_server_capabilities.go:35]: Changed godoc to `CreateServerServerCapability` in c2e7652089

File: traffic_ops/v5-client/server_server_capabilities.go (hunk 3 above)
Comment (zrhoffman) [reply traffic_ops/v5-client/server_server_capabilities.go:56]: We don't want V5 in the struct method name, since this is already the v5 version of the `Session` struct

Comment (kdamichie) [reply traffic_ops/v5-client/server_server_capabilities.go:56]: Sounds good

**Review by kdamichie — APPROVED** [review]
Approved!
