### PR TITLE
Fix DSRC error response

### LINKED ISSUE #4112: TO: Error response conflict in deliveryservices_required_capabilities
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
When making a `POST` to `/deliveryservices_required_capabilities` with a `requiredCapability` that does not exist and with no servers linked to the same delivery service the error response is:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "alerts": [
        {
            "text": "server_capability not found",
            "level": "error"
        }
    ]
}
```
When making a `POST` to `/deliveryservices_required_capabilities` with a `requiredCapability` that does not exist and servers are linked to the same delivery service the error response is:
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
    "alerts": [
        {
            "text": "capability TEST_DISK1 cannot be made required on the delivery service 2 as it has the associated servers 14 that do not have the capability assigned",
            "level": "error"
        }
    ]
}
```
Even though the server capability does not exist.
## Expected / new behavior:
Should return a `404` and same response message.

### PR DESCRIPTION
**Pull request by ZugNZwang**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4112 

 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Create a Delivery Service 
Assign a Server to Delivery Service
Make a `POST` request to `/deliveryservice_required_capabilities` using the Id of the delivery service you created and using a `requiredCapability` value that does not exist.

Should return:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "alerts": [
        {
            "text": "server_capability not found",
            "level": "error"
        }
    ]
}
```

## The following criteria are ALL met by this PR

- [X] This PR includes tests OR I have explained why tests are unnecessary
- [X] This PR includes documentation OR I have explained why documentation is unnecessary
- [X] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [X] This PR includes any and all required license headers
- [X] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [X] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Comment by ocket8888** [comment]
can you rebase to fix these conflicts?

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go [hunk 1]
```diff
@@ -281,6 +286,25 @@ func (rc *RequiredCapability) Create() (error, error, int) {
 	return nil, nil, http.StatusOK
 }
 
+func (rc *RequiredCapability) checkServerCap() (error, error, int) {
+	tx := rc.APIInfo().Tx
+
+	// Get server capability name
+	name := ""
+	if err := tx.QueryRow(`
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: Adding this query broke the flow expected by the sqlmock statements in the unit tests

Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: To be clear, you should change the tests, not your code.
