### PR TITLE
TO `deliveryservice/sslkeys/add` verify certificate chain

### LINKED ISSUE #7046: POST /deliveryservices/sslkeys/add accepts unrelated certificates
## This Bug Report affects these Traffic Control components:

- Traffic Ops

## Current behavior:

`POST /api/4.1/deliveryservices/sslkeys/add` accepts unrelated certificates included in the `certificate.crt` field

## Expected behavior:

Including a certificate that is not part of the Leaf-Intermediate-Root chain should result in a response with a 400-level HTTP status code.

## Steps to reproduce:

1. Create Delivery Service 1
2. Generate a self-signed certificate for DS 1
3. Create Delivery Service 2
4. Generate a self-signed certificate for DS 2
5. Append the DS 2 certificate to the bottom of the DS 1 certificate and POST

`POST /api/4.1/deliveryservices/sslkeys/add` response (HTTP response status code 200):

```json
{
  "alerts": [
    {
      "text": "WARNING: SSL keys were successfully added for 'my-delivery-service-1', but the input certificate may be invalid (certificate is signed by an unknown authority)",
      "level": "warning"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by shamrickus**
This PR fixes #7046 
<hr/>

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?
Add SSL Keys to a Delivery Service where the chain certificates are not related, this should now return a 400 error instead of an unknown authority _warning_.

## If this is a bugfix, which Traffic Control versions contained the bug?

- master

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by ericholguin — APPROVED** [review]
LGTM. Fails when given an inconsistent chain.

File: traffic_ops/testing/api/v5/deliveryservices_keys_test.go [hunk 1]
```diff
@@ -333,6 +334,38 @@ func DeliveryServiceSSLKeys(t *testing.T) {
...
+			if err == nil && dsSSLKey != nil {
+				break
+			}
+		}
+		if dsSSLKey != nil {
+			otherKey = dsSSLKey
+			break
+		}
+	}
+	assert.RequireNotNil(t, otherKey, "Expected to find another DS  with a valid SSL certificate")
```
Comment (ocket8888) [inline traffic_ops/testing/api/v5/deliveryservices_keys_test.go:359]: `dsSSLKey` is never `nil` at any point, so the check after the inner `for` loop will always be true, and this assertion can never fail. To make it work, I think you'd need to only use `new` when setting the value of `dsSSLKey` in that inner loop, and just declare it as a nil pointer above that. I'm sure the test would fail anyway because parsing a blank cert should probably return an error, but as-is this is an unused check.

File: traffic_ops/testing/api/v5/deliveryservices_keys_test.go [hunk 2]
```diff
@@ -333,6 +334,38 @@ func DeliveryServiceSSLKeys(t *testing.T) {
...
+			continue
+		}
+		var err error
+		dsSSLKey := new(tc.DeliveryServiceSSLKeys)
+		for tries := 0; tries < 5; tries++ {
+			time.Sleep(time.Second)
+			var sslKeysResp tc.DeliveryServiceSSLKeysResponse
+			sslKeysResp, _, err = TOSession.GetDeliveryServiceSSLKeys(*ds.XMLID, client.RequestOptions{})
+			*dsSSLKey = sslKeysResp.Response
+			if err == nil && dsSSLKey != nil {
```
Comment (ocket8888) [inline traffic_ops/testing/api/v5/deliveryservices_keys_test.go:350]: Similar to above, `dsSSLKey` can never be nil, so checking it here is pointless unless that changes. If that check were to be `true`, the preceding line would segfault before it got that far.

File: traffic_ops/testing/api/v5/deliveryservices_keys_test.go [hunk 3]
```diff
@@ -333,6 +334,38 @@ func DeliveryServiceSSLKeys(t *testing.T) {
...
+	}
+	assert.RequireNotNil(t, otherKey, "Expected to find another DS  with a valid SSL certificate")
+	err = deliveryservice.Base64DecodeCertificate(&otherKey.Certificate)
+	assert.RequireNoError(t, err, "Couldn't decode certificate: %v", err)
+
+	dsSSLKeyReq.Certificate.Crt += otherKey.Certificate.Crt
+	_, _, err = TOSession.AddSSLKeysForDS(tc.DeliveryServiceAddSSLKeysReq{DeliveryServiceSSLKeysReq: dsSSLKeyReq}, client.RequestOptions{})
+	assert.RequireNotNil(t, err, "Expected inconsistent certificate chain to be rejected")
+	if !strings.Contains(err.Error(), "intermediate chain contains certificates that do not match") {
+		t.Fatalf("Expected failure with chain issue, instead got: %s", err.Error())
```
Comment (ocket8888) [inline traffic_ops/testing/api/v5/deliveryservices_keys_test.go:367]: nit but Fatal is unnecessary when the statement is the last one in the test

File: traffic_ops/traffic_ops_golang/deliveryservice/keys_test.go [hunk 4]
```diff
@@ -2521,11 +2654,29 @@ func TestVerifyAndEncodeCertificateECDSASelfSignedCertificateKeyPairWithoutParam
...
+		t.Fatalf("expected chain to be considered inconsistent")
+	}
+
+	_, _, _, _, isInconsistent, err = verifyCertKeyPair(SelfSignedCertChain+ValidIntermediateCert, SelfSignedRSAPrivateKeyInvalidChain, "", true)
+	if err != nil {
+		t.Fatalf("expected mismatched to return no error")
+	}
+	if !isInconsistent {
+		t.Fatalf("expected chain to be considered inconsistent")
+	}
```
Comment (ocket8888) [inline traffic_ops/traffic_ops_golang/deliveryservice/keys_test.go:2681]: nit but I don't think any of these actually need to be fatal failures

**Review by ocket8888 — APPROVED** [review]
