### PR TITLE
Fixes regression of the ability to add/remove a capability or a delivery service from a server

### LINKED ISSUE #4853: Cannot add a server capability to a server in TP
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Cannot add a capability to a server in TP.

image

## Expected / new behavior:
You should be able to add a capability to a server. This is a regression caused by #4747 . More specifically it's due to the removal of this method - https://github.com/apache/trafficcontrol/pull/4747/files#diff-58e3f2204371520d8da9abcd1e5339c2L33

## Minimal reproduction of the problem with instructions:
- Navigate to a server and select `Manage Capabilities`
- Attempt to add a capability to a server
- Observe the `'serverId' cannot be blank` error.

### LINKED ISSUE #4858: Cannot assign delivery services to a server in TP
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Navigate to an Edge server and attempt to assign delivery services. It will fail.

## Expected / new behavior:
You should be able to assign delivery services to a server. This is a regression caused by #4747 . More specifically it's due to the removal of this method - https://github.com/apache/trafficcontrol/pull/4747/files#diff-58e3f2204371520d8da9abcd1e5339c2L33

## Minimal reproduction of the problem with instructions:
Navigate to an Edge server and attempt to assign delivery services. It will fail.

### PR DESCRIPTION
**Pull request by mitchell852**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4853 and fixes #4858 

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
- Run the [UI tests](https://github.com/apache/trafficcontrol/tree/master/traffic_portal/test/end_to_end)
- Navigate to an Edge server and attempt to add/remove a capability. It should succeed.
- Navigate to an Edge server and attempt to add/remove delivery service assignments. It should succeed.

## If this is a bug fix, what versions of Traffic Control are affected?
- master

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes no documentation updates as it is just a bug fix
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_portal/app/src/common/modules/table/serverDeliveryServices/TableServerDeliveryServicesController.js [hunk 1]
```diff
@@ -120,18 +120,18 @@ var TableServerDeliveryServicesController = function(server, deliveryServices, $
 			size: 'lg',
 			resolve: {
 				server: function() {
-					return server;
+					return $scope.server;
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/table/serverDeliveryServices/TableServerDeliveryServicesController.js:123]: this one actually fixes the ds/server assignment bug
