### PR TITLE
Fixed runtime panic when creating roles, added docs

### LINKED ISSUE #3891: Internal Server Error message when create a new role
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When I created a new role, with the 30 Privilege Level, it displayed the danger message "Internal Server Error". The role still created.
## Expected / new behavior:

It should displays "Role created" message instead.

### PR DESCRIPTION
**Pull request by ocket8888**
## What does this PR (Pull Request) do?
- [x] This PR fixes #3891 and partially addresses #3443 

Fixes runtime panics caused by requests with invalid payloads - the endpoint handler required a `capabilities` array but didn't check for it until after a role had already been created/replaced, thus returning an error message while still seemingly completing the operation successfully. To solve this, the `capabilities` array was made optional in both `POST` (where its absence will result in simply no capabilities added to the Role) and `PUT` requests (where its absence will result in capabilities not being updated on the Role - **NOT** deleting all existing capabilities, which is what would happen if an empty array was submitted).

As the `POST`, `PUT` and `DELETE` methods of the endpoint were undocumented, I also took the opportunity to fill those in - thereby documenting the new behavior. I also added some missing query parameters to the documentation for the `GET` method.

## Which Traffic Control components are affected by this PR?
- Documentation
- Traffic Ops

## What is the best way to verify this PR?
Verify existing tests pass. Build and run Traffic Ops/DB/Portal (CDN-in-a-Box recommended) and verify that admin users can create roles of privilege levels less than or equal to 30 (admin's privilege level) successfully, and no erroneous error message is reported. Build and read the documentation to ensure that it is accurate, comprehensible, and free of guideline violations and/or spelling/grammar mistakes.

## If this is a bug fix, what versions of Traffic Control are affected?

- master (c18d535)
- 3.0.1
- 3.0.2 (RC2)
- 3.1.0 (pre-release candidate)

## The following criteria are ALL met by this PR

- [x] This PR adds no additional tests, but tests for the endpoint already exist
- [x] This PR includes documentation
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/role/roles.go [hunk 1]
```diff
@@ -122,9 +122,11 @@ func (role *TORole) Create() (error, error, int) {
 	}
 
 	//after we have role ID we can associate the capabilities:
-	userErr, sysErr, errCode = role.createRoleCapabilityAssociations(role.ReqInfo.Tx)
-	if userErr != nil || sysErr != nil {
-		return userErr, sysErr, errCode
+	if role.Capabilities != nil && *role.Capabilities != nil && len(*role.Capabilities) > 0 {
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/role/roles.go]: Nit but this can be simplified to `role.Capabilities != nil && len(*role.Capabilities) > 0`

File: traffic_ops/traffic_ops_golang/role/roles.go [hunk 2]
```diff
@@ -177,12 +179,16 @@ func (role *TORole) Update() (error, error, int) {
 	if userErr != nil || sysErr != nil {
 		return userErr, sysErr, errCode
 	}
+
 	// TODO cascade delete, to automatically do this in SQL?
-	userErr, sysErr, errCode = role.deleteRoleCapabilityAssociations(role.ReqInfo.Tx)
-	if userErr != nil || sysErr != nil {
-		return userErr, sysErr, errCode
+	if role.Capabilities != nil && *role.Capabilities != nil {
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/role/roles.go]: do you need to check for len of *role.Capabilities?

File: docs/source/api/roles.rst [hunk 3]
```diff
@@ -65,19 +84,236 @@ Response Structure
...
+				"text": "role was updated.",
+				"level": "success"
+			}
+		],
+		"response": {
+			"id": 5,
+			"name": "test",
+			"description": "quest",
+			"privLevel": 29,
+			"capabilities": null
```
Comment (mhoppa) [inline docs/source/api/roles.rst]: do we return null responses to our users instead of empty throughout our API? I usually dont like doing that as then client have to code against it but if we use it many other places then this is fine

File: traffic_ops/traffic_ops_golang/role/roles.go (hunk 1 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/role/roles.go]: Yeah, so I've heard. Never knew that about Go, makes life much easier

File: traffic_ops/traffic_ops_golang/role/roles.go (hunk 2 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/role/roles.go]: Not to fix the bug.

Sounds like it might be a good idea, though, as it's probably doing extra work otherwise

File: docs/source/api/roles.rst (hunk 3 above)
Comment (ocket8888) [reply docs/source/api/roles.rst]: No idea. Generally I think an empty list would be better, but this documentation is accurate to how the endpoint behaves (which I don't *believe* I changed in this PR) and that's all I was attempting to accomplish.

Comment (mhoppa) [reply docs/source/api/roles.rst]: fine to leave - might be good to do a sweep through all our endpoint for 2.0 and cleanup any null responses

Comment (ocket8888) [reply docs/source/api/roles.rst]: The 2.0 todo list is long

File: traffic_ops/traffic_ops_golang/role/roles.go (hunk 2 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/role/roles.go]: Oh, no actually, you still need to do that. If the Role had associated capabilities and the user updated it to have none, you still need to delete those associations.

Comment (mhoppa) [reply traffic_ops/traffic_ops_golang/role/roles.go]: ahh - makes sense 👍

**Comment by ocket8888** [comment]
retest this please
