### PR TITLE
Fix TP Docker tests

### LINKED ISSUE #5750: TP integration tests in CiaB - Failed: Wait timed out after 2061ms
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Portal

## Current behavior:

When running in CDN in a Box, the Traffic Portal integration tests print a deprecation warning:

```javascript
portal-integration-test_1  | 2021-04-16T18:26:25.673269659Z (node:178) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

and then time out 7 minutes later.

## Expected behavior:

The Traffic Portal integration tests should succeed and exit when running in CDN in a Box.

## Minimal reproduction of the problem with instructions:

```shell
docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml up -d db edge trafficportal trafficops trafficvault portal-integration-test &&
docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml logs --no-color --timestamps -f portal-integration-test
```

## Anything else:

```
[user@computer cdn-in-a-box]$ docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml up -d db edge trafficportal trafficops trafficvault portal-integration-test &&
docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml logs --no-color --timestamps -f portal-integration-test
[CDN-in-a-Box startup...]
portal-integration-test_1  | 2021-04-16T18:25:51.962158310Z waiting for Traffic Ops at 'https://trafficops.infra.ciab.test:443' fqdn 'trafficops.infra.ciab.test' host 'trafficops'
portal-integration-test_1  | 2021-04-16T18:25:54.967527310Z waiting for Traffic Ops at 'https://trafficops.infra.ciab.test:443' fqdn 'trafficops.infra.ciab.test' host 'trafficops'
portal-integration-test_1  | 2021-04-16T18:25:57.999561215Z {"ping":"pong"}
portal-integration-test_1  | 2021-04-16T18:25:58.000902020Z Waiting for Traffic Ops to finish seeding the Traffic Ops data so Traffic Portal will start...
portal-integration-test_1  | 2021-04-16T18:26:01.002326624Z Waiting for Traffic Ops to finish seeding the Traffic Ops data so Traffic Portal will start...
portal-integration-test_1  | 2021-04-16T18:26:04.003902506Z Waiting for Traffic Ops to finish seeding the Traffic Ops data so Traffic Portal will start...
portal-integration-test_1  | 2021-04-16T18:26:07.011961986Z waiting for Traffic Portal at 'https://trafficportal.infra.ciab.test:443' fqdn 'trafficportal.infra.ciab.test' host 'trafficportal'
portal-integration-test_1  | 2021-04-16T18:26:10.018580571Z waiting for Traffic Portal at 'https://trafficportal.infra.ciab.test:443' fqdn 'trafficportal.infra.ciab.test' host 'trafficportal'
portal-integration-test_1  | 2021-04-16T18:26:13.068850938Z {"ping":"pong"}
portal-integration-test_1  | 2021-04-16T18:26:13.896271118Z waiting for selenium server to start on 'http://localhost:4444'
portal-integration-test_1  | 2021-04-16T18:26:14.013744820Z webdriver-manager: using local installed version 12.1.8
portal-integration-test_1  | 2021-04-16T18:26:14.591160302Z [18:26:14] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/lang/traffic_portal/test/integration/node_modules/webdriver-manager/selenium/chromedriver_90.0.4430.72 -Dwebdriver.gecko.driver=/lang/traffic_portal/test/integration/node_modules/webdriver-manager/selenium/geckodriver-v0.29.1 -jar /lang/traffic_portal/test/integration/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar -port 4444
portal-integration-test_1  | 2021-04-16T18:26:14.596816938Z [18:26:14] I/start - seleniumProcess.pid: 122
portal-integration-test_1  | 2021-04-16T18:26:14.900976519Z waiting for selenium server to start on 'http://localhost:4444'
portal-integration-test_1  | 2021-04-16T18:26:14.954405847Z 18:26:14.951 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
portal-integration-test_1  | 2021-04-16T18:26:15.046874266Z 18:26:15.046 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
portal-integration-test_1  | 2021-04-16T18:26:15.102067665Z 2021-04-16 18:26:15.099:INFO::main: Logging initialized @490ms to org.seleniumhq.jetty9.util.log.StdErrLog
portal-integration-test_1  | 2021-04-16T18:26:15.361178836Z 18:26:15.359 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
portal-integration-test_1  | 2021-04-16T18:26:15.468039890Z 18:26:15.467 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
portal-integration-test_1  | 2021-04-16T18:26:15.953138534Z {
portal-integration-test_1  | 2021-04-16T18:26:15.953162064Z   "seleniumAddress": "http://localhost:4444/wd/hub",
portal-integration-test_1  | 2021-04-16T18:26:15.953167600Z   "allScriptsTimeout": 200000,
portal-integration-test_1  | 2021-04-16T18:26:15.953171573Z   "capabilities": {
portal-integration-test_1  | 2021-04-16T18:26:15.953175256Z     "browserName": "chrome",
portal-integration-test_1  | 2021-04-16T18:26:15.953178624Z     "shardTestFiles": false,
portal-integration-test_1  | 2021-04-16T18:26:15.953182383Z     "maxInstances": 1,
portal-integration-test_1  | 2021-04-16T18:26:15.953185705Z     "marionette": true,
portal-integration-test_1  | 2021-04-16T18:26:15.953188850Z     "acceptInsecureCerts": true,
portal-integration-test_1  | 2021-04-16T18:26:15.953192482Z     "acceptSslCerts": true,
portal-integration-test_1  | 2021-04-16T18:26:15.953204873Z     "chromeOptions": {
portal-integration-test_1  | 2021-04-16T18:26:15.953208828Z       "args": [
portal-integration-test_1  | 2021-04-16T18:26:15.953211997Z         "--headless",
portal-integration-test_1  | 2021-04-16T18:26:15.953214913Z         "--no-sandbox",
portal-integration-test_1  | 2021-04-16T18:26:15.953217920Z         "--ignore-certificate-errors"
portal-integration-test_1  | 2021-04-16T18:26:15.953221040Z       ],
portal-integration-test_1  | 2021-04-16T18:26:15.953224415Z       "prefs": {
portal-integration-test_1  | 2021-04-16T18:26:15.953227488Z         "download": {
portal-integration-test_1  | 2021-04-16T18:26:15.953230902Z           "prompt_for_download": false
portal-integration-test_1  | 2021-04-16T18:26:15.953233937Z         }
portal-integration-test_1  | 2021-04-16T18:26:15.953237320Z       }
portal-integration-test_1  | 2021-04-16T18:26:15.953240810Z     }
portal-integration-test_1  | 2021-04-16T18:26:15.953244259Z   },
portal-integration-test_1  | 2021-04-16T18:26:15.953247781Z   "specs": [
portal-integration-test_1  | 2021-04-16T18:26:15.953250575Z     "specs/*.spec.js"
portal-integration-test_1  | 2021-04-16T18:26:15.953253819Z   ],
portal-integration-test_1  | 2021-04-16T18:26:15.953261461Z   "framework": "jasmine",
portal-integration-test_1  | 2021-04-16T18:26:15.953264629Z   "getPageTimeout": 60000,
portal-integration-test_1  | 2021-04-16T18:26:15.953267845Z   "jasmineNodeOpts": {
portal-integration-test_1  | 2021-04-16T18:26:15.953270876Z     "showColors": true,
portal-integration-test_1  | 2021-04-16T18:26:15.953274097Z     "defaultTimeoutInterval": 1000000,
portal-integration-test_1  | 2021-04-16T18:26:15.953277097Z     "random": false,
portal-integration-test_1  | 2021-04-16T18:26:15.953280417Z     "stopSpecOnExpectationFailure": true
portal-integration-test_1  | 2021-04-16T18:26:15.953283560Z   },
portal-integration-test_1  | 2021-04-16T18:26:15.953286613Z   "params": {
portal-integration-test_1  | 2021-04-16T18:26:15.953289658Z     "apiUrl": "https://trafficportal.infra.ciab.test/api/4.0",
portal-integration-test_1  | 2021-04-16T18:26:15.953293014Z     "baseUrl": "https://trafficportal.infra.ciab.test",
portal-integration-test_1  | 2021-04-16T18:26:15.953296346Z     "login": {
portal-integration-test_1  | 2021-04-16T18:26:15.953299358Z       "username": "admin",
portal-integration-test_1  | 2021-04-16T18:26:15.953302625Z       "password": "twelve12"
portal-integration-test_1  | 2021-04-16T18:26:15.953305815Z     },
portal-integration-test_1  | 2021-04-16T18:26:15.953308707Z     "junitReporter": true
portal-integration-test_1  | 2021-04-16T18:26:15.953311927Z   }
portal-integration-test_1  | 2021-04-16T18:26:15.953314866Z }
portal-integration-test_1  | 2021-04-16T18:26:21.622484203Z [18:26:21] I/launcher - Running 1 instances of WebDriver
portal-integration-test_1  | 2021-04-16T18:26:21.622861104Z [18:26:21] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
portal-integration-test_1  | 2021-04-16T18:26:21.707663192Z 18:26:21.707 INFO [ActiveSessionFactory.apply] - Capabilities are: {
portal-integration-test_1  | 2021-04-16T18:26:21.707686364Z   "acceptInsecureCerts": true,
portal-integration-test_1  | 2021-04-16T18:26:21.707690455Z   "acceptSslCerts": true,
portal-integration-test_1  | 2021-04-16T18:26:21.707693236Z   "browserName": "chrome",
portal-integration-test_1  | 2021-04-16T18:26:21.707695851Z   "chromeOptions": {
portal-integration-test_1  | 2021-04-16T18:26:21.707701890Z     "args": [
portal-integration-test_1  | 2021-04-16T18:26:21.707710458Z       "--headless",
portal-integration-test_1  | 2021-04-16T18:26:21.707713194Z       "--no-sandbox",
portal-integration-test_1  | 2021-04-16T18:26:21.707716300Z       "--ignore-certificate-errors"
portal-integration-test_1  | 2021-04-16T18:26:21.707719226Z     ],
portal-integration-test_1  | 2021-04-16T18:26:21.707721538Z     "prefs": {
portal-integration-test_1  | 2021-04-16T18:26:21.707723903Z       "download": {
portal-integration-test_1  | 2021-04-16T18:26:21.707726229Z         "prompt_for_download": false,
portal-integration-test_1  | 2021-04-16T18:26:21.707729089Z         "default_directory": "\u002flang\u002ftraffic_portal\u002ftest\u002fintegration\u002fDownloads"
portal-integration-test_1  | 2021-04-16T18:26:21.707731881Z       }
portal-integration-test_1  | 2021-04-16T18:26:21.707734279Z     }
portal-integration-test_1  | 2021-04-16T18:26:21.707736770Z   },
portal-integration-test_1  | 2021-04-16T18:26:21.707739144Z   "count": 1,
portal-integration-test_1  | 2021-04-16T18:26:21.707741551Z   "marionette": true,
portal-integration-test_1  | 2021-04-16T18:26:21.707743922Z   "maxInstances": 1,
portal-integration-test_1  | 2021-04-16T18:26:21.707746338Z   "shardTestFiles": false
portal-integration-test_1  | 2021-04-16T18:26:21.707749165Z }
portal-integration-test_1  | 2021-04-16T18:26:21.708595442Z 18:26:21.708 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
portal-integration-test_1  | 2021-04-16T18:26:21.740644294Z Starting ChromeDriver 90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429}) on port 27970
portal-integration-test_1  | 2021-04-16T18:26:21.740664253Z Only local connections are allowed.
portal-integration-test_1  | 2021-04-16T18:26:21.740704761Z Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
portal-integration-test_1  | 2021-04-16T18:26:21.754028082Z [1618597581.754][SEVERE]: bind() failed: Cannot assign requested adChdrroemsesD r(i9v9e)r
portal-integration-test_1  | 2021-04-16T18:26:21.754051139Z  was started successfully.
portal-integration-test_1  | 2021-04-16T18:26:22.361118012Z 18:26:22.360 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
portal-integration-test_1  | 2021-04-16T18:26:22.386356649Z 18:26:22.386 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session c25790e892ad3a7887fae82215c409f0 (org.openqa.selenium.chrome.ChromeDriverService)
portal-integration-test_1  | 2021-04-16T18:26:22.445794102Z null
portal-integration-test_1  | 2021-04-16T18:26:25.671004229Z Started
portal-integration-test_1  | 2021-04-16T18:26:25.673269659Z (node:178) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
portal-integration-test_1  | 2021-04-16T18:32:13.531474919Z [32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[32m.[0m[31mF[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0mdelete /server_capabilities?name=servertestcap1
portal-integration-test_1  | 2021-04-16T18:32:13.533199062Z DATA: { route: '/server_capabilities?name=servertestcap1puf5' }
portal-integration-test_1  | 2021-04-16T18:32:13.693251920Z [31mF[0mpost /divisions
portal-integration-test_1  | 2021-04-16T18:32:13.693281555Z DATA: { name: 'PhysTestpuf5' }
portal-integration-test_1  | 2021-04-16T18:32:30.007104339Z [31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0mdelete /servers/
portal-integration-test_1  | 2021-04-16T18:32:30.007309598Z DATA: {
portal-integration-test_1  | 2021-04-16T18:32:30.007316874Z   route: '/servers/',
portal-integration-test_1  | 2021-04-16T18:32:30.007320168Z   getRequest: [
portal-integration-test_1  | 2021-04-16T18:32:30.007322774Z     {
portal-integration-test_1  | 2021-04-16T18:32:30.007325235Z       route: '/servers',
portal-integration-test_1  | 2021-04-16T18:32:30.007327722Z       queryKey: 'hostName',
portal-integration-test_1  | 2021-04-16T18:32:30.007330137Z       queryValue: 'testserver1',
portal-integration-test_1  | 2021-04-16T18:32:30.007332617Z       replace: 'route'
portal-integration-test_1  | 2021-04-16T18:32:30.007335059Z     }
portal-integration-test_1  | 2021-04-16T18:32:30.007337506Z   ]
portal-integration-test_1  | 2021-04-16T18:32:30.007339940Z }
portal-integration-test_1  | 2021-04-16T18:33:25.348777035Z [31mF[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m[32m.[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m[32m.[0m
portal-integration-test_1  | 2021-04-16T18:33:25.348820307Z 
portal-integration-test_1  | 2021-04-16T18:33:25.348826266Z Failures:
portal-integration-test_1  | 2021-04-16T18:33:25.348831524Z 1) Traffic Portal - ASNs - Admin Role can open asns page
portal-integration-test_1  | 2021-04-16T18:33:25.348901999Z   Message:
portal-integration-test_1  | 2021-04-16T18:33:25.348915598Z [31m    Failed: Wait timed out after 2061ms[0m
portal-integration-test_1  | 2021-04-16T18:33:25.348920827Z   Stack:
portal-integration-test_1  | 2021-04-16T18:33:25.349025826Z     TimeoutError: Wait timed out after 2061ms
portal-integration-test_1  | 2021-04-16T18:33:25.349036494Z         at /lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2201:17
portal-integration-test_1  | 2021-04-16T18:33:25.349039681Z         at ManagedPromise.invokeCallback_ (/lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1376:14)
portal-integration-test_1  | 2021-04-16T18:33:25.349042237Z         at TaskQueue.execute_ (/lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
portal-integration-test_1  | 2021-04-16T18:33:25.349044481Z         at TaskQueue.executeNext_ (/lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
portal-integration-test_1  | 2021-04-16T18:33:25.349046889Z         at /lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2927:27
portal-integration-test_1  | 2021-04-16T18:33:25.349049202Z         at /lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7
portal-integration-test_1  | 2021-04-16T18:33:25.349052880Z         at runMicrotasks (<anonymous>)
portal-integration-test_1  | 2021-04-16T18:33:25.349056793Z         at processTicksAndRejections (internal/process/task_queues.js:97:5)
portal-integration-test_1  | 2021-04-16T18:33:25.349060309Z     From: Task: <anonymous wait>
portal-integration-test_1  | 2021-04-16T18:33:25.349063663Z         at scheduleWait (/lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2188:20)
portal-integration-test_1  | 2021-04-16T18:33:25.349067163Z         at ControlFlow.wait (/lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2517:12)
portal-integration-test_1  | 2021-04-16T18:33:25.349070949Z         at thenableWebDriverProxy.wait (/lang/traffic_portal/test/integration/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
portal-integration-test_1  | 2021-04-16T18:33:25.349074616Z         at run (/lang/traffic_portal/test/integration/node_modules/protractor/built/browser.js:59:33)
portal-integration-test_1  | 2021-04-16T18:33:25.349078015Z         at ProtractorBrowser.to.<computed> [as wait] (/lang/traffic_portal/test/integration/node_modules/protractor/built/browser.js:67:16)
portal-integration-test_1  | 2021-04-16T18:33:25.349087584Z         at SideNavigationPage.<anonymous> (/lang/traffic_portal/test/integration/PageObjects/SideNavigationPage.po.ts:70:23)
portal-integration-test_1  | 2021-04-16T18:33:25.349091734Z         at Generator.next (<anonymous>)
portal-integration-test_1  | 2021-04-16T18:33:25.349095167Z         at /lang/traffic_portal/test/integration/GeneratedCode/PageObjects/SideNavigationPage.po.js:8:71
portal-integration-test_1  | 2021-04-16T18:33:25.349098716Z         at new Promise (<anonymous>)
portal-integration-test_1  | 2021-04-16T18:33:25.349103015Z         at __awaiter (/lang/traffic_portal/test/integration/GeneratedCode/PageObjects/SideNavigationPage.po.js:4:12)
portal-integration-test_1  | 2021-04-16T18:33:25.349106793Z     From: Task: Run it("can open asns page") in control flow
portal-integration-test_1  | 2021-04-16T18:33:25.349110357Z         at UserContext.<anonymous> (/lang/traffic_portal/test/integration/node_modules/jasminewd2/index.js:94:19)
portal-integration-test_1  | 2021-04-16T18:33:25.349113878Z     From asynchronous test: 
portal-integration-test_1  | 2021-04-16T18:33:25.349117280Z     Error
portal-integration-test_1  | 2021-04-16T18:33:25.349120650Z         at Suite.<anonymous> (/lang/traffic_portal/test/integration/specs/ASNs.spec.ts:46:13)
portal-integration-test_1  | 2021-04-16T18:33:25.349124314Z         at /lang/traffic_portal/test/integration/specs/ASNs.spec.ts:40:9
portal-integration-test_1  | 2021-04-16T18:33:25.349127735Z         at Array.forEach (<anonymous>)
portal-integration-test_1  | 2021-04-16T18:33:25.349131160Z         at /lang/traffic_portal/test/integration/specs/ASNs.spec.ts:39:21
portal-integration-test_1  | 2021-04-16T18:33:25.349134505Z         at Generator.next (<anonymous>)
portal-integration-test_1  | 2021-04-16T18:33:25.349137938Z         at /lang/traffic_portal/test/integration/GeneratedCode/specs/ASNs.spec.js:8:71
portal-integration-test_1  | 2021-04-16T18:33:25.349141322Z 
portal-integration-test_1  | 2021-04-16T18:33:25.349144539Z 2) Traffic Portal - ASNs - Admin Role create an ASN
portal-integration-test_1  | 2021-04-16T18:33:25.349148202Z   Message:
ortal-integration-test_1  | 2021-04-16T18:33:25.349151483Z [31m    Failed: Wait timed out after 2046ms[0m
[Continues like this for 14,000+ lines]
```

### PR DESCRIPTION
**Pull request by shamrickus**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5750 

Adds a resolution to the chrome launch options to ensure we get desktop resolutions (which is what the tests were built for).
## Which Traffic Control components are affected by this PR?

- CI tests

## What is the best way to verify this PR?
Run the TP docker tests
```
docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml build
docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml up -d db edge trafficportal trafficops trafficvault portal-integration-test
docker-compose -f docker-compose.yml -f docker-compose.traffic-portal-test.yml logs -f portal-integration-test
```

## If this is a bug fix, what versions of Traffic Control are affected?

- master

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

**Review by zrhoffman — CHANGES_REQUESTED** [review]
The TP integration tests still fail for me in Docker after building the images using instructions from the *What is the best way to verify this PR?* section:
```dockerfile
portal-integration-test_1  | 2021-04-20T18:12:09.669106753Z Started
portal-integration-test_1  | 2021-04-20T18:12:09.670966442Z (node:172) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
portal-integration-test_1  | 2021-04-20T18:18:02.149833716Z ..FFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFF..F.F.FFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFdelete /server_capabilities?name=servertestcap1
portal-integration-test_1  | 2021-04-20T18:18:02.152047970Z DATA: { route: '/server_capabilities?name=servertestcap19bop' }
portal-integration-test_1  | 2021-04-20T18:18:02.336235648Z Fpost /divisions
portal-integration-test_1  | 2021-04-20T18:18:02.336302061Z DATA: { name: 'PhysTest9bop' }
portal-integration-test_1  | 2021-04-20T18:18:18.701412683Z FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFdelete /servers/
portal-integration-test_1  | 2021-04-20T18:18:18.701817302Z DATA: {
portal-integration-test_1  | 2021-04-20T18:18:18.701850868Z   route: '/servers/',
portal-integration-test_1  | 2021-04-20T18:18:18.701854366Z   getRequest: [
portal-integration-test_1  | 2021-04-20T18:18:18.701856804Z     {
portal-integration-test_1  | 2021-04-20T18:18:18.701859295Z       route: '/servers',
portal-integration-test_1  | 2021-04-20T18:18:18.701875025Z       queryKey: 'hostName',
portal-integration-test_1  | 2021-04-20T18:18:18.701877822Z       queryValue: 'testserver1',
portal-integration-test_1  | 2021-04-20T18:18:18.701881307Z       replace: 'route'
portal-integration-test_1  | 2021-04-20T18:18:18.701901458Z     }
portal-integration-test_1  | 2021-04-20T18:18:18.701904880Z   ]
portal-integration-test_1  | 2021-04-20T18:18:18.701907166Z }
portal-integration-test_1  | 2021-04-20T18:19:14.604046520Z F.FFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFF.
portal-integration-test_1  | 2021-04-20T18:19:14.604081097Z 
portal-integration-test_1  | 2021-04-20T18:19:14.604090324Z Failures:
portal-integration-test_1  | 2021-04-20T18:19:14.604094542Z 1) Traffic Portal - ASNs - Admin Role can open asns page
portal-integration-test_1  | 2021-04-20T18:19:14.604186520Z   Message:
portal-integration-test_1  | 2021-04-20T18:19:14.604197447Z     Failed: Wait timed out after 2011ms
portal-integration-test_1  | 2021-04-20T18:19:14.604200781Z   Stack:
portal-integration-test_1  | 2021-04-20T18:19:14.604335374Z     TimeoutError: Wait timed out after 2011ms
[same stack trace as in #5750]
[...]
portal-integration-test_1  | 2021-04-20T18:19:14.660557273Z 409 specs, 383 failures
portal-integration-test_1  | 2021-04-20T18:19:14.660559418Z Finished in 424.985 seconds
```

File: infrastructure/cdn-in-a-box/traffic_portal_integration_test/run.sh [hunk 1]
```diff
@@ -65,11 +65,6 @@ done
 jq "$(<<JQ_FILTERS cat
 	.params.baseUrl = "https://$TP_FQDN" |
 	.params.apiUrl = "https://$TP_FQDN/api/4.0" |
-	.capabilities.chromeOptions.args = [
```
Comment (zrhoffman) [inline infrastructure/cdn-in-a-box/traffic_portal_integration_test/run.sh:68]: Changing the `=` to `+=` would preserve the previous arguments, too

**Review by zrhoffman — CHANGES_REQUESTED** [review]
The Dockerfile needs to not replace `.capabilities.chromeOptions.args`, as well:

https://github.com/apache/trafficcontrol/blob/61e423f33b8f4b61a6228c9e3d0fbac646d231f2/infrastructure/cdn-in-a-box/traffic_portal_integration_test/Dockerfile#L63-L72

**Review by zrhoffman — APPROVED** [review]
Passing for me now!
