### PR TITLE
`cdns/{{name}}/federations` and `cdns/{{name}}/federations/{{ID}}` use RFC3339 timestamps

### LINKED ISSUE #5911: TO API uses non-RFC3339 date/time strings
## I'm submitting a ...
-  other

## Traffic Control components affected ...
-  Traffic Ops
-  unknown

## Current behavior:
Traffic Ops API responses frequently return our custom format for date/times: `YYYY-MM-DD hh:mm:ss-ZZ` (`"2006-01-02 15:04:05-07"` is the actual Go format string).

## Expected behavior:
The Traffic Ops API (in the latest API version, where the behavior is breakable) should respond with RFC3339-format date strings.

## Minimal reproduction of the problem with instructions:
Make most any TO API request.

### LINKED ISSUE #7799: /cdns/{{name}}/federations and /cdns/{{name}}/federations/{{ID}} should use RFC3339 timestamps
## Parent Issue: #5911

Breaking down the parent issue #5911 in smaller issues to raise separate, reviewable PRs for each of the services.

## Traffic Control components affected:
- Traffic Ops
- Documentation

## Current behavior:
CDN Federations Using Deprecated TimeNoMod & TimeLayout

## Expected behavior:
CDN Federations to Use RFC3339 Format

## Steps to reproduce:
Make requests to:

- `/cdns/{{Name}}/federations`
- `/cdns/{{Name}}/federations/{{ID}}`

### PR DESCRIPTION
**Pull request by ocket8888**
Fixes #7799 and thereby closes #5911

This PR updates the "CDN Federations" endpoint(s) to use RFC3339 timestamps. Also, with the recent sphinx upgrade, our RFC text roles aren't working due to missing grave accents, so I fixed those.

<hr/>

## Which Traffic Control components are affected by this PR?
- Documentation
- Traffic Ops Client (Go)
- Traffic Ops

## What is the best way to verify this PR?
Make sure all of the tests provided pass. I added a bunch of unit tests, too - not nearly 100% coverage, but better than nothing.

## PR submission checklist
- [x] This PR has tests
- [x] This PR has documentation
- [x] This PR has a CHANGELOG.md entry
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: traffic_ops/testing/api/v5/cdn_federations_test.go [hunk 1]
```diff
@@ -220,10 +219,9 @@ func validateCDNFederationCNameSort() utils.CkReqFunc {
 	return func(t *testing.T, _ toclientlib.ReqInf, resp interface{}, alerts tc.Alerts, _ error) {
 		assert.RequireNotNil(t, resp, "Expected CDN Federation response to not be nil.")
 		var federationCNames []string
-		CDNFederationResp := resp.([]tc.CDNFederation)
-		for _, CDNFederation := range CDNFederationResp {
-			assert.RequireNotNil(t, CDNFederation.CName, "Expected CDN Federation CName to not be nil.")
```
Comment (rimashah25) [inline traffic_ops/testing/api/v5/cdn_federations_test.go:225]: Why are the assert of CName and ID checks removed?

File: traffic_ops/traffic_ops_golang/routing/routes.go [hunk 2]
```diff
@@ -395,10 +395,11 @@ func Routes(d ServerData) ([]Route, http.Handler, error) {
...
-		{Version: api.Version{Major: 5, Minor: 0}, Method: http.MethodPut, Path: `cdns/{name}/federations/{id}$`, Handler: api.UpdateHandler(&cdnfederation.TOCDNFederation{}), RequiredPrivLevel: auth.PrivLevelAdmin, RequiredPermissions: []string{"FEDERATION:UPDATE", "FEDERATION:READ", "CDN:READ"}, Authenticated: Authenticated, Middlewares: nil, ID: 42606546631},
-		{Version: api.Version{Major: 5, Minor: 0}, Method: http.MethodDelete, Path: `cdns/{name}/federations/{id}$`, Handler: api.DeleteHandler(&cdnfederation.TOCDNFederation{}), RequiredPrivLevel: auth.PrivLevelAdmin, RequiredPermissions: []string{"FEDERATION:DELETE", "FEDERATION:READ", "CDN:READ"}, Authenticated: Authenticated, Middlewares: nil, ID: 444285290231},
+		{Version: api.Version{Major: 5, Minor: 0}, Method: http.MethodGet, Path: `cdns/{name}/federations/?$`, Handler: api.Wrap(cdnfederation.Read, []string{"name"}, nil), RequiredPrivLevel: auth.PrivLevelReadOnly, RequiredPermissions: []string{"CDN:READ", "FEDERATION:READ", "DELIVERY-SERVICE:READ"}, Authenticated: Authenticated, Middlewares: nil, ID: 48922503231},
```
Comment (rimashah25) [inline traffic_ops/traffic_ops_golang/routing/routes.go:398]: interesting.. I haven't seen api.wrap usage before. What are we achieving here?

File: traffic_ops/traffic_ops_golang/cdnfederation/cdnfederations.go [hunk 3]
```diff
@@ -21,21 +23,27 @@ package cdnfederation
 
 import (
 	"database/sql"
+	_ "embed" // needed to embed SQL queries within Go variables
```
Comment (zrhoffman) [inline traffic_ops/traffic_ops_golang/cdnfederation/cdnfederations.go:26]: None of the file-embedded queries use named parameters. Just use sql, not sqlx, unless I'm missing something?

**Review by zrhoffman — CHANGES_REQUESTED** [review]

File: traffic_ops/traffic_ops_golang/cdnfederation/insert.sql [hunk 4]
```diff
@@ -0,0 +1,12 @@
+INSERT INTO federation (
```
Comment (rimashah25) [inline traffic_ops/traffic_ops_golang/cdnfederation/insert.sql:1]: Why different sql files? We normally have these sql statements as part of the go file.

File: infrastructure/cdn-in-a-box/enroller/enroller.go [hunk 5]
```diff
@@ -842,13 +847,8 @@ func enrollFederation(toSession *session, r io.Reader) error {
 				return err
 			}
 			cdnFederation = resp.Response
-			if cdnFederation.ID == nil {
-				err = fmt.Errorf("federation returned from creation through Traffic Ops with null or undefined ID")
-				log.Infoln(err)
-				return err
-			}
```
[the remark this answers is not in the document]
Comment (ocket8888) [reply infrastructure/cdn-in-a-box/enroller/enroller.go:849]: Federation IDs cannot be nil, so not removing that check would result in a compilation error

File: traffic_ops/traffic_ops_golang/cdnfederation/cdnfederations.go (hunk 3 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/cdnfederation/cdnfederations.go:26]: I'm not sure what you mean? `embed` doesn't interact with database drivers or libraries in any way

File: traffic_ops/testing/api/v5/cdn_federations_test.go (hunk 1 above)
Comment (ocket8888) [reply traffic_ops/testing/api/v5/cdn_federations_test.go:225]: Because those cannot be nil, so the check is useless.

File: traffic_ops/traffic_ops_golang/routing/routes.go (hunk 2 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/routing/routes.go:398]: Eliminates boilerplate. The servers API uses it, I think that's the only other one so far.

File: traffic_ops/traffic_ops_golang/cdnfederation/insert.sql (hunk 4 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/cdnfederation/insert.sql:1]: Yeah, and I find that harder to read than if they're in their own file.

Comment (rimashah25) [reply traffic_ops/traffic_ops_golang/cdnfederation/insert.sql:1]: Interesting but is it worth the change now just because it is harder to read? Why is this file an exception and not others. Also, makes it harder to review too since it looks like cdnfederations.go underwent a lot of change.

File: traffic_ops/traffic_ops_golang/routing/routes.go (hunk 2 above)
Comment (rimashah25) [reply traffic_ops/traffic_ops_golang/routing/routes.go:398]: So, why not do it for all the routes in a different PR, then have it just done for one. I didn't review server's PR, else I would have commented the same on that one too.

Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/routing/routes.go:398]: Because you can't just make that change for all of the routes. That requires changing the call signatures of the route handlers; such a PR would probably never even be reviewed. I had to make a new handler, and I didn't want to use the crudder, so I chose to make use of the wrapper.

File: traffic_ops/traffic_ops_golang/cdnfederation/insert.sql (hunk 4 above)
Comment (ocket8888) [reply traffic_ops/traffic_ops_golang/cdnfederation/insert.sql:1]: I mean, I also thought it would be easier for a reviewer to read them in their own files. I don't think putting more lines into the cdnfederations.go file is going to make the changes to it look any smaller, but if you want these to be inline string constants I can do that.

**Review by rimashah25 — APPROVED** [review]
Code changes LGTM. Need to test on local.

File: traffic_ops/traffic_ops_golang/cdnfederation/cdnfederations.go (hunk 3 above)
Comment (zrhoffman) [reply traffic_ops/traffic_ops_golang/cdnfederation/cdnfederations.go]: Resolved in 0f6d05dec5

**Review by zrhoffman — APPROVED** [review]

File: traffic_ops/traffic_ops_golang/routing/routes.go (hunk 2 above)
Comment (rimashah25) [reply traffic_ops/traffic_ops_golang/routing/routes.go:398]: ok.. we have now 3 different ways to do it.. not bad.. but maintenance gets a little tough. For now, I am ok with the changes.

**Comment by rimashah25** [comment]
Test look good. Approved.
