### PR TITLE
return 403 when unauthorized user assigns/deletes ds required capability

### LINKED ISSUE #4043: TO: Internal Server error is returned when user not tenant of the ds assigns/deletes required capability
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

500 Internal server error
## Expected / new behavior:

403 Forbidden access
## Minimal reproduction of the problem with instructions:

create tenants 1 and 2 at same level not associated with each other
try to post on DS of tenant1 while logged in as tenant2
*Issue1:*
POST https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryservices_required_capabilities
{
        "deliveryServiceID": 17,
        "requiredCapability": "DISK_CAP"
}
*Issue2:*
DELETE https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryservices_required_capabilities?deliveryServiceID=17&requiredCapability=DISK_CAP

Issue3: 

this error also happens when an user of inactive tenant same as that of DS makes a POST or DELETE

### PR DESCRIPTION
**Pull request by jheitz200**
- [X] This PR fixes #4043

## Which Traffic Control components are affected by this PR?

- Traffic Ops
- Documentation - the documentation for this api is still correct

## What is the best way to verify this PR?

Build new traffic ops API and then associate/get/disassociates server_capability to deliveryservice via the api path /deliveryservice_required_capabilities as an unauthorized user

## If this is a bug fix, what versions of Traffic Control are affected?

Master (102372c0b92e4ef65b9011a949464bb6750c920b)

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go [hunk 1]
```diff
@@ -219,22 +219,51 @@ func (rc *RequiredCapability) getCapabilities(tenantIDs []int) ([]tc.DeliverySer
...
 	return api.GenericDelete(rc)
 }
 
+// exists checks to see if a required capability is assigned to a delivery service
+func (rc *RequiredCapability) exists() (int, error) {
+	where, orderBy, pagination, queryValues, errs := dbhelpers.BuildWhereAndOrderByAndPagination(rc.APIInfo().Params, rc.ParamColumns())
+	if len(errs) > 0 {
+		return http.StatusBadRequest, util.JoinErrs(errs)
+	}
+	fmt.Printf("\n\nwhere: %+v\norderby: %+v\npag: %+v\nqueryvalues: %+v\n\n", where, orderBy, pagination, queryValues)
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: I am guessing you did not mean to add this?

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go [hunk 2]
```diff
@@ -219,22 +219,51 @@ func (rc *RequiredCapability) getCapabilities(tenantIDs []int) ([]tc.DeliverySer
...
+
+	var count int
+	query := `SELECT count(deliveryservice_id) FROM deliveryservices_required_capability where deliveryservice_id = $1 and required_capability = $2`
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: nothing to address but instead of COUNT you could simplify this to SELECT EXISTS and read that into a bool

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go [hunk 3]
```diff
@@ -219,22 +219,51 @@ func (rc *RequiredCapability) getCapabilities(tenantIDs []int) ([]tc.DeliverySer
...
+	statusCode, err := rc.exists()
+	if err != nil {
+		return err, nil, statusCode
 	}
 
 	return api.GenericDelete(rc)
 }
 
+// exists checks to see if a required capability is assigned to a delivery service
+func (rc *RequiredCapability) exists() (int, error) {
```
Comment (mhoppa) [inline traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: Is this not caught by https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/api/generic_crud.go#L169? is this just to clean up the error message?

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go (hunk 1 above)
Comment (jheitz200) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: thanks, i complete forgot i wanted to see what that helper function did and use it if possible. looking into this now

File: traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go (hunk 3 above)
Comment (jheitz200) [reply traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices_required_capabilities.go]: I dont have my head wrapped around all of these interfaces yet....

this was added before i realized the auth if check needed switched. thanks for pointing out the functionality of this interface. removing this code. updates coming
