### PR TITLE
Resolves issue #6439 by changing the TM endpoint used to get cache status using publish/CrStates

### LINKED ISSUE #6439: TC Health Client uses TM's /api/cache-statuses API which does not participate in the health protocol
## This Bug Report affects these Traffic Control components:

- Traffic Control Health Client (t3c-health-client)

## Current behavior:

The TC Health Client uses TM's `/api/cache-statuses` API for getting cache availability states in order to mark caches up/down. This is very dangerous because this API returns the TM's _local_ cache states rather than the combined cache states of itself and its peers using the optimistic health protocol. Using this API, the TC health client will set caches down when only the single requested TM thinks they're down. However, if that singular TM is on a network partition and can't reach those caches because of it, it will mark those caches down even though they might be perfectly reachable by its peers (and the broader client base).

## Expected behavior:

The TC Health Client should use TM's `/publish/CrStates` API for getting cache availability states. This API returns the _combined_ cache states of itself and its peers participating in the optimistic health protocol, and this API is what Traffic Router actually uses for routing clients to available caches.

In addition to the dangers of using TM's local cache states, `/api/cache-statuses` includes a lot of unnecessary data that the tc-health-client doesn't really need, whereas `/publish/CrStates` is simply just cache availability. We also shouldn't have Traffic Router and the tc-health-client using different APIs for getting cache states from TM.

## Steps to reproduce:

Disconnect a TM from the cache network or otherwise make it unable to reach one or more caches. Request `/api/cache-statuses` and `/publish/CrStates` and compare the results. As long as a cache is reachable and otherwise healthy, the other peers will consider it available, so the caches will be available in `/publish/CrStates` but not in `/api/cache-statuses`.

### PR DESCRIPTION
**Pull request by jrushford**
Closes #6439  by changing the TM endpoint used to get cache status using publish/CrStates

## Which Traffic Control components are affected by this PR?

- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

**Review by jpappa200 — APPROVED** [review]
👍 LGTM

File: tc-health-client/tmagent/tmagent.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ import (
 	"github.com/apache/trafficcontrol/lib/go-tc"
 	"github.com/apache/trafficcontrol/tc-health-client/config"
 	"github.com/apache/trafficcontrol/tc-health-client/util"
-	"github.com/apache/trafficcontrol/traffic_monitor/datareq"
+	//"github.com/apache/trafficcontrol/traffic_monitor/datareq"
```
Comment (zrhoffman) [inline tc-health-client/tmagent/tmagent.go:41]: This comment should be removed:

**Review by zrhoffman — CHANGES_REQUESTED** [review]

File: tc-health-client/tmagent/tmagent.go (hunk 1 above)
Comment (jrushford) [reply tc-health-client/tmagent/tmagent.go:41]: @zrhoffman yeah, agreed.  I overlooked that.

**Review by zrhoffman — APPROVED** [review]
