### PR TITLE
Fix reserved consistentHashQueryParams entries causing internal server error instead of client error

### LINKED ISSUE #6385: Reserved consistentHashQueryParameters cause internal server error
## This Bug Report affects these Traffic Control components:
- Traffic Ops

## Current behavior:
Trying to update or create a Delivery Service to use a reserved query string parameter name like "trred" or "format" causes a 500 Internal Server Error response.

## Expected behavior:
I'm almost certain the old behavior was more proper; the API should return a client-level error and accompanying Alert that tells the user they can't do what they're trying to do.

## Steps to reproduce:
```console
$ topost -kp deliveryservices '{
	"active": false,
	"cdnId": 2,
	"displayName": "test",
	"dnsBypassCname": "test",
	"dscp": 1,
	"geoLimit": 1,
	"geoLimitCountries": "[US, CA]",
	"geoProvider": -7,
	"initialDispersion": 1,
	"ipv6RoutingEnabled": true,
	"logsEnabled": true,
	"missLat": 0,
	"missLong": 0,
	"multiSiteOrigin": false,
	"orgServerFqdn": "http://origin.infra.ciab.test",
	"protocol": 7,
	"qstringIgnore": 5,
	"rangeRequestHandling": 0,
	"regionalGeoBlocking": false,
	"tenantId": 1,
	"typeId": 1,
	"xmlId": "test",
	"consistentHashQueryParams": ["format", "something fine", "trred"]
}'
```

### PR DESCRIPTION
**Pull request by ocket8888**
This PR fixes #6385 by causing Traffic Ops to return the correct error code (400 Bad Request) and an alert describing what went wrong when a client attempts to create or modify a Delivery Service such that it would an entry in its Consistent Hashing Query string Parameters that is reserved for use by Traffic Router.

<hr/>

## Which Traffic Control components are affected by this PR?
- Traffic Ops

## What is the best way to verify this PR?
```bash
topost -kp deliveryservices '{       
        "active": false,
        "cdnId": 2,
        "consistentHashQueryParams": ["format"],
        "displayName": "test",
        "dnsBypassCname": "test",
        "dscp": 1,
        "geoLimit": 1,
        "geoLimitCountries": "US,CA",
        "geoProvider": -7,
        "initialDispersion": 1,
        "ipv6RoutingEnabled": true,
        "logsEnabled": true,
        "missLat": 0,
        "missLong": 0,
        "multiSiteOrigin": false,
        "orgServerFqdn": "test.quest",
        "protocol": 7,
        "qstringIgnore": 5,
        "rangeRequestHandling": 0,
        "regionalGeoBlocking": false,
        "tenantId": 1,
        "typeId": 1,
        "xmlId": "test"
}'
```

## If this is a bugfix, which Traffic Control versions contained the bug
- not sure

## PR submission checklist
- [x] This PR has tests 
- [x] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY**

### CODE REVIEW

File: lib/go-tc/deliveryservices.go [hunk 1]
```diff
@@ -49,6 +49,14 @@ const MaxRangeSliceBlockSize = 33554432
 // values of a Delivery Service's 'Active' property (v3.0+).
 type DeliveryServiceActiveState string
 
+// These names of URL query string parameters are not allowed to be in a
+// Delivery Service's "ConsistentHashQueryParams" set, because they collide with
+// query string parameters reserved for use by Traffic Router.
+const (
+	ReservedConsistentHashingQueryParameterFormat = "format"
+	ReservedConsistentHashingQueryParameterTRRED  = "trred"
```
Comment (zrhoffman) [inline lib/go-tc/deliveryservices.go:57]: Should probably include `"fakeClientIpAddress"`, too

https://github.com/apache/trafficcontrol/blob/7741530c494d797758d226885abee3ed7feda7be/traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/request/HTTPRequest.java#L30

Comment (zrhoffman) [inline lib/go-tc/deliveryservices.go:57]: It's true that reserved consistent hashing query parameters includes these, but that doesn't describe what they actually are. For reuse, should these be grouped with other Traffic Router-related constants?

For example, this is a header, not a GET variable, but maybe GET variables could go somewhere nearby:

https://github.com/apache/trafficcontrol/blob/7741530c494d797758d226885abee3ed7feda7be/lib/go-tc/traffic_router.go#L55-L57

**Review by zrhoffman — CHANGES_REQUESTED** [review]

File: lib/go-tc/deliveryservices.go (hunk 1 above)
Comment (ocket8888) [reply lib/go-tc/deliveryservices.go:57]: I don't really care where they go, but I also don't think it matters that this doesn't describe what they are to Traffic Router. It describes what they are in the context of Delivery Service properties: disallowed values. Traffic Router doesn't use any part of this Go package, so nobody and nothing reading that code should ever need to understand how Traffic Router uses them.
