### PR TITLE
More Topologies validation

### LINKED ISSUE #4691: Internal Server Error when create/update a Topologies with invalid parent node
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Create new topologies with wrong parent node. For example:
Do a POST `api/3.0/topologies` with this payload :
```
{
        "name": "my-topology",
        "description": "This is my topology",
        "nodes": [
                {
                        "cachegroup": "albany-ny-usa",
                        "parents": [
                                7
                        ]
                }
        ]
}
```

API will return Internal Server Error

Same thing for PUT `api/3.0/topologies`.  It also return Internal Server Error.
## Expected / new behavior:

It should return 400 Bad Request.

### PR DESCRIPTION
**Pull request by zrhoffman**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4691 by checking whether a parent node's index exists
- This PR fixes a bug by only performing further validation on a topology if all of its nodes' cachegroups exist
- Adds a status code check to the negative API tests to enure that POSTing invalid topologies returns only 400-level response status codes, not 500-level

## Which Traffic Control components are affected by this PR?

- Traffic Control Client (Go)
- Traffic Ops

## What is the best way to verify this PR?

Run Traffic Ops API tests, verify they still pass:
```shell script
docker-compose -f docker-compose.yml -f docker-compose.traffic-ops-test.yml up
```

## If this is a bug fix, what versions of Traffic Control are affected?

- master (88f4f2aad0)

## The following criteria are ALL met by this PR

- [x] This PR includes tests
- [x] This PR is a bugfix, no documentation necessary
- [x] An update to CHANGELOG.md is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/client/topology.go [hunk 1]
```diff
@@ -30,94 +30,118 @@ const (
...
+func (to *Session) CreateTopology(top tc.Topology) (*tc.TopologyResponse, ReqInf, error, int) {
+	var (
+		statusCode = http.StatusNotAcceptable
+		remoteAddr net.Addr
+	)
 	reqBody, err := json.Marshal(top)
 	reqInf := ReqInf{CacheHitStatus: CacheHitStatusMiss, RemoteAddr: remoteAddr}
 	if err != nil {
-		return nil, reqInf, err
+		return nil, reqInf, err, statusCode
```
Comment (rawlinp) [inline traffic_ops/client/topology.go:41]: Based on the mailing list discussion it sounds like consensus has been built around adding the status code to the `ReqInf` struct and returning it that way, so we should start following that pattern for these methods. Then in a separate PR someone could retroactively add the status code to `ReqInf` for the rest of the TO Go client methods.

Comment (zrhoffman) [reply traffic_ops/client/topology.go]: Following that pattern in c1140e42f4

Comment (rawlinp) [reply traffic_ops/client/topology.go]: Did you not want to start setting the status code in `ReqInf` in these Topologies methods? Or that likely means having to update all of its usage throughout the entire TO client?

Comment (zrhoffman) [reply traffic_ops/client/topology.go]: Let's do it. Setting the status code in 481038d58a.

File: traffic_ops/client/session.go [hunk 2]
```diff
@@ -307,7 +307,7 @@ func NewNoAuthSession(toURL string, insecure bool, userAgent string, useCache bo
 	}, useCache)
 }
 
-// ErrUnlessOk returns nil and an error if the given Response's status code is anything but 200 OK. This includes reading the Response.Body and Closing it. Otherwise, the given response and error are returned unchanged.
+// ErrUnlessOk returns the response an error if the given Response's status code is anything but 200 OK. This includes reading the Response.Body and Closing it. Otherwise, the given response and a nil error are returned.
```
Comment (srijeet0406) [inline traffic_ops/client/session.go:310]: Should be `the response and an error`
Also, shouldn't the comment say that this function returns three things?

File: traffic_ops/traffic_ops_golang/topology/validation.go [hunk 3]
```diff
@@ -57,9 +57,14 @@ func checkForEdgeParents(nodes []tc.TopologyNode, cachegroups []tc.CacheGroupNul
 	node := nodes[nodeIndex]
 	errs := make([]error, len(node.Parents))
 	for parentIndex := range node.Parents {
-		cacheGroupType := cachegroups[node.Parents[parentIndex]].Type
+		cachegroupIndex := node.Parents[parentIndex]
```
Comment (srijeet0406) [inline traffic_ops/traffic_ops_golang/topology/validation.go:60]: This could be a part of the `range` statement above, wherein you'd get the index and the value in the step.

File: traffic_ops/client/session.go (hunk 2 above)
Comment (zrhoffman) [reply traffic_ops/client/session.go]: Thanks, fixed the typo and mentioned the remote address in 971302817.

File: traffic_ops/traffic_ops_golang/topology/validation.go (hunk 3 above)
Comment (zrhoffman) [reply traffic_ops/traffic_ops_golang/topology/validation.go]: Changed in 38838fa76
