### PR TITLE
increase state character limit to 4

### LINKED ISSUE #6983: Increase State Character Limit
## This Bug Report affects these Traffic Control components:
- Traffic Portal

## Current behavior:

Topologies -> Physical Location

As of now, the state cannot have more than 2 letters. 

## Expected behavior:

There are many states which have abbreviations of more than 2 letters and up to 4 letters.

### PR DESCRIPTION
**Pull request by ntheanh201**
Closes: #6983 

Increase state character limit to 4

<hr/>

## Which Traffic Control components are affected by this PR?
- Traffic Portal

## What is the best way to verify this PR?

- Step 1: Go to Topology/Phys Locations
- Step 2: Create/Update Phys Location (State can have max 4 characters)

## PR submission checklist
- [ ] This PR has tests 
- [ ] This PR has documentation 
- [x] This PR has a CHANGELOG.md entry 
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://apache.org/security) for details)

### CODE REVIEW

File: traffic_portal/app/src/common/modules/form/physLocation/FormPhysLocationController.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ var FormPhysLocationController = function(physLocation, $scope, $location, formU
         { name: 'shortName', type: 'text', required: true, maxLength: 100 },
         { name: 'address', type: 'text', required: true, maxLength: 128 },
         { name: 'city', type: 'text', required: true, maxLength: 128 },
-        { name: 'state', type: 'text', required: true, maxLength: 2 },
+        { name: 'state', type: 'text', required: true, maxLength: 4 },
```
Comment (ocket8888) [inline traffic_portal/app/src/common/modules/form/physLocation/FormPhysLocationController.js:45]: This should match the limitations set by the API - and currently there is no max length in the API. You might arbitrarily choose something huge like 255 but 5+ characters is actually totally valid and our front-end ought to model that more accurately.

**Review by ocket8888 — CHANGES_REQUESTED** [review]

File: traffic_portal/app/src/common/modules/form/physLocation/FormPhysLocationController.js (hunk 1 above)
Comment (ntheanh201) [reply traffic_portal/app/src/common/modules/form/physLocation/FormPhysLocationController.js:45]: Should we also set the limit in Traffic Ops API?

Comment (ocket8888) [reply traffic_portal/app/src/common/modules/form/physLocation/FormPhysLocationController.js:45]: You could do that, but that would be a breaking API change which would necessitate an APIv6, deprecation strategy, and a plan on how to eventually migrate old data to the new, more restrictive format.

It'd be a lot less work to just eliminate the requirement altogether in the UI.
