### PR TITLE
Fix federation user validation

### LINKED ISSUE #4068: Admin can assign User to a Federation with wrong PARAMETER
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Login as ADMIN
POST Request: `https://{{TO_BASE_URL}}/api/{{api_version}}/federations/{{federationsID}}/users. `
With wrong json payload parameter like "userIdssss"
```json
{
        "userIdssss": [2],
        "replaces": true
}
```
It will return 
```http
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

{
    "alerts": [
        {
            "text": "0 user(s) were Assign to the test.quest. federation",
            "level": "success"
        }
    ],
    "response": {
        "userIds": null,
        "replace": null
    }
}
```
## Expected / new behavior:
Should return 400 Bad Request

### PR DESCRIPTION
**Pull request by mhoppa**
## What does this PR (Pull Request) do?

This PR makes sure the on federation user post the userIDs is defined.

- [x] This PR fixes #4068 

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Make a POST request without a userIDs key to federation users endpoint and you should get back a validation error.

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: lib/go-tc/federation.go [hunk 1]
```diff
@@ -184,7 +186,9 @@ type FederationUserPost struct {
 
 // Validate validates FederationUserPost
 func (f *FederationUserPost) Validate(tx *sql.Tx) error {
-	return nil
+	return validation.ValidateStruct(f,
+		validation.Field(&f.IDs, validation.NotNil),
```
Comment (ocket8888) [inline lib/go-tc/federation.go]: Does this also check for "not empty"?

Comment (ocket8888) [reply lib/go-tc/federation.go]: You know what, that doesn't matter. The best anyone could hope for passing `userIds` as `null` or `undefined` is that it would do nothing. Specific status codes in response to certain requests aren't reliably documented (intentionally) so this isn't even a breaking change.

Comment (mhoppa) [reply lib/go-tc/federation.go]: Perl did check if userIDs is defined and an array https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/API/FederationUser.pm#L61

Comment (ocket8888) [reply lib/go-tc/federation.go]: Nice
