### PR TITLE
Fixes missing staticdns query parameters

### LINKED ISSUE #2575: StaticDNS API missing query parameters
/api/1.3/staticdnsentries is unable to narrow down by the following query parameters

```
id=,address=,cachegroup=,cachegroupId=,deliveryserviceId=,host=,ttl=,type=,typeId=

### PR DESCRIPTION
**Pull request by dewrich**
Fixes #2575 
Also added more validation rules that were missed from the Perl conversion

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2135/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2136/
Test PASSed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2137/
Test PASSed.

File: traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go [hunk 1]
```diff
@@ -81,8 +82,8 @@ func (staticDNSEntry *TOStaticDNSEntry) SetKeys(keys map[string]interface{}) {
 // Validate fulfills the api.Validator interface
 func (staticDNSEntry TOStaticDNSEntry) Validate() error {
 	errs := validation.Errors{
-		"host":    validation.Validate(staticDNSEntry.Host, validation.Required),
-		"address": validation.Validate(staticDNSEntry.Address, validation.Required),
+		"host":    validation.Validate(staticDNSEntry.Host, validation.Required, is.DNSName),
+		"address": validation.Validate(staticDNSEntry.Address, validation.Required, is.Host),
 		"dsname":  validation.Validate(staticDNSEntry.DeliveryService, validation.Required),
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go]: Why is the dsname (which maps the to xml_id) required? Shouldn't it be the DS ID since that's what's used in the insert statement?

Same goes for "type", which is the type name -- I think "typeId" should be required instead.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2138/
Test PASSed.

File: traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go [hunk 2]
```diff
@@ -81,8 +82,8 @@ func (staticDNSEntry *TOStaticDNSEntry) SetKeys(keys map[string]interface{}) {
 // Validate fulfills the api.Validator interface
 func (staticDNSEntry TOStaticDNSEntry) Validate() error {
 	errs := validation.Errors{
-		"host":    validation.Validate(staticDNSEntry.Host, validation.Required),
-		"address": validation.Validate(staticDNSEntry.Address, validation.Required),
+		"host":    validation.Validate(staticDNSEntry.Host, validation.Required, is.DNSName),
+		"address": validation.Validate(staticDNSEntry.Address, validation.Required, is.Host),
```
Comment (rawlinp) [inline traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go]: To get 100% coverage I think we need to vary the validation based upon the type, i.e. 'A_RECORD' should be is.IPv4, 'AAAA_RECORD` should be is.IPv6, and 'CNAME_RECORD' should be is.DNSName.

Since I'm adding type validation in https://github.com/apache/trafficcontrol/pull/2572, I could also add those checks if you want.

Comment (dewrich) [reply traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go]: @rawlinp So you are centralizing *all* type validation?  If that's the case then sure and just let me know and I'll refer to it.

Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go]: Centralizing in the sense that everything that requires types from the types table can/will use the same shared function that also returns the type name when valid. So once that's in, you could just check the type name here and vary the validation based on the type name.

**Comment by dewrich** [comment]
@rawlinp @dangogh I updated the validation rules accordingly.  @rawlinp Lemme know about the `type` validations, because we'll need to coordinate that PR as well.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/2141/
Test PASSed.

File: traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go [hunk 3]
```diff
@@ -82,11 +82,11 @@ func (staticDNSEntry *TOStaticDNSEntry) SetKeys(keys map[string]interface{}) {
...
 func (staticDNSEntry TOStaticDNSEntry) Validate() error {
 	errs := validation.Errors{
-		"host":    validation.Validate(staticDNSEntry.Host, validation.Required, is.DNSName),
-		"address": validation.Validate(staticDNSEntry.Address, validation.Required, is.Host),
-		"dsname":  validation.Validate(staticDNSEntry.DeliveryService, validation.Required),
-		"ttl":     validation.Validate(staticDNSEntry.TTL, validation.Required),
-		"type":    validation.Validate(staticDNSEntry.Type, validation.Required),
+		"host":              validation.Validate(staticDNSEntry.Host, validation.Required, is.DNSName),
+		"address":           validation.Validate(staticDNSEntry.Address, validation.Required, is.Host),
+		"deliveryserviceId": validation.Validate(staticDNSEntry.DeliveryServiceID, validation.Required),
```
Comment (dewrich) [inline traffic_ops/traffic_ops_golang/staticdnsentry/staticdnsentry.go]: @dangogh does this address your concerns?
