### PR TITLE
Removed extra newline in LE cert chain

### LINKED ISSUE #5331: Let's Encrypt certs have a blank line in the chain
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:

When using Let's Encrypt there is a blank line inserted in the certificate chain. This causes TR to not be able to use the certificate.

## Expected behavior:

There should not be a blank line in the cert chain

## Minimal reproduction of the problem with instructions:

Create a cert using Let's Encrypt.

Version:
4.1.1

### PR DESCRIPTION
**Pull request by mattjackson220**
## What does this PR (Pull Request) do?

- [x] This PR fixes #5331  

This PR removes the extra new line in the LE cert chain

## Which Traffic Control components are affected by this PR?

- Traffic Ops

## What is the best way to verify this PR?

Generate new certs with Let's Encrypt, verify that the extra line is removed, verify that the cert can be deployed to TR / edges and is functioning as before

## The following criteria are ALL met by this PR

small bug fix so no tests, docs, changelog updates
- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/deliveryservice/letsencryptcert.go [hunk 1]
```diff
@@ -355,7 +355,10 @@ func GetLetsEncryptCertificates(cfg *config.Config, req tc.DeliveryServiceLetsEn
 	}
 	keyPem := keyBuf.Bytes()
 
-	dsSSLKeys.Certificate = tc.DeliveryServiceSSLKeysCertificate{Crt: string(EncodePEMToLegacyPerlRiakFormat(certificates.Certificate)), Key: string(EncodePEMToLegacyPerlRiakFormat(keyPem)), CSR: ""}
+	// remove extra line if LE returns it
+	trimmedCert := bytes.ReplaceAll(certificates.Certificate, []byte("\n\n"), []byte("\n"))
```
Comment (TaylorCFrey) [inline traffic_ops/traffic_ops_golang/deliveryservice/letsencryptcert.go:359]: Any reason to ever expect a Microsoft style carriage return that would also need to be filtered/removed?

Also, the `EncodePEMToLegacyPerlRiakFormat` (hilarious comments BTW) reintroduces newline characters. Any chance they could end up doubled up again? Or maybe we don't need newlines at all before being passed into `EncodePEMToLegacyPerlRiakFormat`?

Comment (mattjackson220) [reply traffic_ops/traffic_ops_golang/deliveryservice/letsencryptcert.go:359]: since this only interacts with Let's Encrypt i wouldnt expect it to ever be different unless they change on their side. so i dont think we need to account for those but i guess it also wouldnt hurt

I think `EncodePEMToLegacyPerlRiakFormat` only adds new line characters between every 76 chars and at the very end so that shouldnt impact this. this is fixing because the LE certs had a new line in the middle of the cert chain that was causing issues.  at least i havent seen any issues with it in testing

also i with i could take credit for the funny comments haha. not from me but i really appreciate them

Comment (TaylorCFrey) [reply traffic_ops/traffic_ops_golang/deliveryservice/letsencryptcert.go:359]: @mattjackson220 So I can see the (_obvious_) fix, but how do I go about testing this? Is there someway for me to generate a LE cert and verify the newlines before and after?

**Review by TaylorCFrey — APPROVED** [review]
Reviewed code, addressed my comments.
Did peer screen share for verification and validation as well.
