### PR TITLE
Ciab.ssl.lock.fix

### LINKED ISSUE #3486: CIAB race condition on SSL variables
On a clean checkout of master when attempting to run the TO API tests and TP UI tests, I see intermittent failures for the CIAB to come up completely.  More specifically, TO never comes up fully because the SSL cert and key paths are missing from the cdn.conf and therefore everything else downstream waits forever.  Not entirely sure how with the present lockfile this would be going on, but I suspect issues around filesystem syncronization issues with docker.

**TO Perl Docker log**:
```2019-04-10T23:03:40.051888334Z  Creating x509v3 request for cn=*.demo3.mycdn.ciab.test type ...
2019-04-10T23:03:43.903986397Z  Create X509 Req RetCode=0
2019-04-10T23:03:43.904014030Z  Signing x509v3 request for cn=*.demo3.mycdn.ciab.test type ...
2019-04-10T23:03:43.959847906Z  Sign X509 Req RetCode=0
2019-04-10T23:03:45.511471961Z  sending incremental file list
```

**TO Golang Docker Log**:
```
2019-04-10T23:03:35.667512974Z  + '[' -f /shared/ssl/completed ']'
2019-04-10T23:03:35.669332493Z  + [[ -x /config.sh ]]
2019-04-10T23:03:35.669344997Z  + /config.sh
2019-04-10T23:03:38.363566912Z  crt=
2019-04-10T23:03:38.363615810Z  key=
```

**ls on lockfile**:
```
-rw-rw-rw-. 1 root root    0 2019-04-10 23:03:45.500688973 +0000 completed
```

### PR DESCRIPTION
**Pull request by jhg03a**
## What does this PR (Pull Request) do?

There is an intermittent race condition it seems with regard to our TO API and TP UI tests and how the required CIAB environment comes up in a clean checkout with no modifications.

- [x] This PR fixes #3486 

## Which Traffic Control components are affected by this PR?

- CDN in a Box

## What is the best way to verify this PR?

Run the TO API tests or the TP UI tests.

## If this is a bug fix, what versions of Traffic Ops are affected?

- master
- 3.0.0
- 3.0.1 (RC1)

## The following criteria are ALL met by this PR

- [ ] This PR includes tests OR I have explained why tests are unnecessary
- [ ] This PR includes documentation OR I have explained why documentation is unnecessary
- [ ] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [ ] This PR includes any and all required license headers
- [ ] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/config/config.go [hunk 1]
```diff
@@ -292,8 +292,16 @@ func ParseConfig(cfg Config) (Config, error) {
 		if cfg.URL, err = url.Parse(listen); err != nil {
 			invalidTOURLStr = fmt.Sprintf("invalid Traffic Ops URL '%s': %v", listen, err)
 		}
+
 		cfg.KeyPath = cfg.GetKeyPath()
+		if cfg.KeyPath == "" {
+			return Config{}, fmt.Errorf("key in %s cannot be blank", listen)
+		}
+
 		cfg.CertPath = cfg.GetCertPath()
```
Comment (dangogh) [inline traffic_ops/traffic_ops_golang/config/config.go]: seems you picked up a change from my other PR #3480 that was reverted.   This check is done in the main package instead so the error doesn't get lost.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3521/
Test FAILed.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/trafficcontrol-PR/3522/
Test PASSed.
