### PR TITLE
TP: adds tr request and response header fields to steering* ds forms

### LINKED ISSUE #4271: TR request/response headers are missing from the STEERING* delivery service form
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
TR response headers and TR request headers fields are missing from the STEERING and CLIENT_STEERING delivery service forms.

## Expected / new behavior:
TR response headers and TR request headers fields should be on the STEERING and CLIENT_STEERING delivery service forms.

## Minimal reproduction of the problem with instructions:
Create a new delivery service of type STEERING and notice that the TR response headers and TR request headers fields are missing.

### PR DESCRIPTION
**Pull request by mitchell852**
## What does this PR (Pull Request) do?

- [x] This PR fixes #4271 

## Which Traffic Control components are affected by this PR?

- Traffic Portal

## What is the best way to verify this PR?
Create or update a STEERING or CLIENT_STEERING delivery service and ensure that the TR Request / Response Headers are listed under Routing Configuration Settings.

## If this is a bug fix, what versions of Traffic Control are affected?

- master (0c04aac)
- 4.0.0 (RC1)

## The following criteria are ALL met by this PR

- [x] This PR includes tests OR I have explained why tests are unnecessary
- [x] This PR includes documentation OR I have explained why documentation is unnecessary
- [x] This PR includes an update to CHANGELOG.md OR such an update is not necessary
- [x] This PR includes any and all required license headers
- [x] This PR ensures that database migration sequence is correct OR this PR does not include a database migration
- [x] This PR **DOES NOT FIX A SERIOUS SECURITY VULNERABILITY** (see [the Apache Software Foundation's security guidelines](https://www.apache.org/security/) for details)

### CODE REVIEW

File: traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js [hunk 1]
```diff
@@ -202,10 +202,13 @@ var FormEditDeliveryServiceController = function(deliveryService, origin, type,
 				if (options.status.id == $scope.COMPLETE) {
 					createDeliveryServiceUpdateRequest(dsRequest, options.comment, true).then(
 						function() {
-							deliveryServiceService.updateDeliveryService(deliveryService);
-						}).then(function() {
-							$state.reload(); // reloads all the resolves for the view
-							messageModel.setMessages([ { level: 'success', text: 'Delivery Service [ ' + deliveryService.xmlId + ' ] updated' } ], false);
+							deliveryServiceService.updateDeliveryService(deliveryService).
```
Comment (mitchell852) [inline traffic_portal/app/src/common/modules/form/deliveryService/edit/FormEditDeliveryServiceController.js]: I mistakenly branched off another branch that has a PR that has yet to be merged. Once PR#4273 is merged. This should go away.
