### PR TITLE
Fix TO Go CRConfig generation to ignore active ANY_MAP DSes

### LINKED ISSUE #1121: Traffic Ops does not ignore active ANY_MAP Delivery Services when generating CRConfig
According to the documentation for Delivery Services:
> ANY_MAP is not known to Traffic Router. For this deliveryservice, the “Raw remap text” field in the input form will be used as the remap line on the cache.

However, Traffic Ops treats it similarly to an HTTP Delivery Service when generating CRConfig, and this is only avoided by setting the ANY_MAP Delivery Service to inactive. Rather, Traffic Ops should filter out ANY_MAP Delivery Services when generating the CRConfig so that Traffic Router doesn't treat them like an HTTP Delivery Service.

### PR DESCRIPTION
**Pull request by rawlinp**
This is a regression from the Perl version of the CRConfig generation
which ignores active ANY_MAP DSes.

Fixes #1121

### CODE REVIEW

File: traffic_ops/traffic_ops_golang/crconfig/deliveryservice.go [hunk 1]
```diff
@@ -76,6 +76,7 @@ inner join type as t on t.id = d.type
 left outer join profile as p on p.id = d.profile
 where d.cdn_id = (select id from cdn where name = $1)
 and d.active = true
+and t.name != 'ANY_MAP'
```
Comment (rob05c) [inline traffic_ops/traffic_ops_golang/crconfig/deliveryservice.go]: Can you change this to `tc.DSTypeAnyMap`?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/incubator-trafficcontrol-PR/1863/
Test PASSed.

File: traffic_ops/traffic_ops_golang/crconfig/deliveryservice.go (hunk 1 above)
Comment (rawlinp) [reply traffic_ops/traffic_ops_golang/crconfig/deliveryservice.go]: done
